package model.conf;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.Key;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
import oracle.jbo.RowIterator;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class Cnf_SoOpmedicoImpl extends EntityImpl {


    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Idop {
            public Object get(Cnf_SoOpmedicoImpl obj) {
                return obj.getIdop();
            }

            public void put(Cnf_SoOpmedicoImpl obj, Object value) {
                obj.setIdop((Integer) value);
            }
        }
        ,
        Codop {
            public Object get(Cnf_SoOpmedicoImpl obj) {
                return obj.getCodop();
            }

            public void put(Cnf_SoOpmedicoImpl obj, Object value) {
                obj.setCodop((Integer) value);
            }
        }
        ,
        Idcentro {
            public Object get(Cnf_SoOpmedicoImpl obj) {
                return obj.getIdcentro();
            }

            public void put(Cnf_SoOpmedicoImpl obj, Object value) {
                obj.setIdcentro((Integer) value);
            }
        }
        ,
        Cognome {
            public Object get(Cnf_SoOpmedicoImpl obj) {
                return obj.getCognome();
            }

            public void put(Cnf_SoOpmedicoImpl obj, Object value) {
                obj.setCognome((String) value);
            }
        }
        ,
        Nome {
            public Object get(Cnf_SoOpmedicoImpl obj) {
                return obj.getNome();
            }

            public void put(Cnf_SoOpmedicoImpl obj, Object value) {
                obj.setNome((String) value);
            }
        }
        ,
        Titolo {
            public Object get(Cnf_SoOpmedicoImpl obj) {
                return obj.getTitolo();
            }

            public void put(Cnf_SoOpmedicoImpl obj, Object value) {
                obj.setTitolo((String) value);
            }
        }
        ,
        Dtfinevalopmedico {
            public Object get(Cnf_SoOpmedicoImpl obj) {
                return obj.getDtfinevalopmedico();
            }

            public void put(Cnf_SoOpmedicoImpl obj, Object value) {
                obj.setDtfinevalopmedico((Date) value);
            }
        }
        ,
        Tpscr {
            public Object get(Cnf_SoOpmedicoImpl obj) {
                return obj.getTpscr();
            }

            public void put(Cnf_SoOpmedicoImpl obj, Object value) {
                obj.setTpscr((String) value);
            }
        }
        ,
        Ulss {
            public Object get(Cnf_SoOpmedicoImpl obj) {
                return obj.getUlss();
            }

            public void put(Cnf_SoOpmedicoImpl obj, Object value) {
                obj.setUlss((String) value);
            }
        }
        ,
        Idpool {
            public Object get(Cnf_SoOpmedicoImpl obj) {
                return obj.getIdpool();
            }

            public void put(Cnf_SoOpmedicoImpl obj, Object value) {
                obj.setIdpool((Integer) value);
            }
        }
        ,
        Cf {
            public Object get(Cnf_SoOpmedicoImpl obj) {
                return obj.getCf();
            }

            public void put(Cnf_SoOpmedicoImpl obj, Object value) {
                obj.setCf((String) value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(Cnf_SoOpmedicoImpl object);

        public abstract void put(Cnf_SoOpmedicoImpl object, Object value);

        public int index() {
            return Cnf_SoOpmedicoImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return Cnf_SoOpmedicoImpl.AttributesEnum.firstIndex() + Cnf_SoOpmedicoImpl.AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = Cnf_SoOpmedicoImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDOP = AttributesEnum.Idop.index();
    public static final int CODOP = AttributesEnum.Codop.index();
    public static final int IDCENTRO = AttributesEnum.Idcentro.index();
    public static final int COGNOME = AttributesEnum.Cognome.index();
    public static final int NOME = AttributesEnum.Nome.index();
    public static final int TITOLO = AttributesEnum.Titolo.index();
    public static final int DTFINEVALOPMEDICO = AttributesEnum.Dtfinevalopmedico.index();
    public static final int TPSCR = AttributesEnum.Tpscr.index();
    public static final int ULSS = AttributesEnum.Ulss.index();
    public static final int IDPOOL = AttributesEnum.Idpool.index();
    public static final int CF = AttributesEnum.Cf.index();

    /**
     *
     *  This is the default constructor (do not remove)
     */
  public Cnf_SoOpmedicoImpl()
  {
  }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.conf.Cnf_SoOpmedico");
    }


    /**
     *
     *  Gets the attribute value for Idop, using the alias name Idop
     */
    public Integer getIdop()
  {
        return (Integer) getAttributeInternal(IDOP);
    }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idop
   */
  public void setIdop(Integer value)
  {
    setAttributeInternal(IDOP, value);
  }

  /**
     *
     *  Gets the attribute value for Codop, using the alias name Codop
     */
    public Integer getCodop()
  {
        return (Integer) getAttributeInternal(CODOP);
    }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Codop
   */
  public void setCodop(Integer value)
  {
    setAttributeInternal(CODOP, value);
  }

  /**
     *
     *  Gets the attribute value for Idcentro, using the alias name Idcentro
     */
    public Integer getIdcentro()
  {
        return (Integer) getAttributeInternal(IDCENTRO);
    }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idcentro
   */
  public void setIdcentro(Integer value)
  {
    setAttributeInternal(IDCENTRO, value);
  }

  /**
   * 
   *  Gets the attribute value for Cognome, using the alias name Cognome
   */
  public String getCognome()
  {
    return (String)getAttributeInternal(COGNOME);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Cognome
   */
  public void setCognome(String value)
  {
    setAttributeInternal(COGNOME, value);
  }

  /**
   * 
   *  Gets the attribute value for Nome, using the alias name Nome
   */
  public String getNome()
  {
    return (String)getAttributeInternal(NOME);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Nome
   */
  public void setNome(String value)
  {
    setAttributeInternal(NOME, value);
  }

  /**
   * 
   *  Gets the attribute value for Titolo, using the alias name Titolo
   */
  public String getTitolo()
  {
    return (String)getAttributeInternal(TITOLO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Titolo
   */
  public void setTitolo(String value)
  {
    setAttributeInternal(TITOLO, value);
  }

  /**
   * 
   *  Gets the attribute value for Dtfinevalopmedico, using the alias name Dtfinevalopmedico
   */
  public Date getDtfinevalopmedico()
  {
    return (Date)getAttributeInternal(DTFINEVALOPMEDICO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Dtfinevalopmedico
   */
  public void setDtfinevalopmedico(Date value)
  {
    setAttributeInternal(DTFINEVALOPMEDICO, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @param idop key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer idop) {
        return new Key(new Object[] { idop });
    }

    protected void doDML(int operation, TransactionEvent e)
  {
    if(operation==this.DML_INSERT)
    {//inserisco il codice da sequenza
      SequenceImpl s = new SequenceImpl("SO_OPMEDICO_SEQ", getDBTransaction());     
      this.setIdop(s.getSequenceNumber().intValue());

      
    }
      
    super.doDML(operation, e);
  }


  /**
   * 
   *  Gets the attribute value for Tpscr, using the alias name Tpscr
   */
  public String getTpscr()
  {
    return (String)getAttributeInternal(TPSCR);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Tpscr
   */
  public void setTpscr(String value)
  {
    setAttributeInternal(TPSCR, value);
  }

  /**
   * 
   *  Gets the attribute value for Ulss, using the alias name Ulss
   */
  public String getUlss()
  {
    return (String)getAttributeInternal(ULSS);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Ulss
   */
  public void setUlss(String value)
  {
    setAttributeInternal(ULSS, value);
  }

    /**
     * Gets the attribute value for Idpool, using the alias name Idpool.
     * @return the value of Idpool
     */
    public Integer getIdpool() {
        return (Integer) getAttributeInternal(IDPOOL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Idpool.
     * @param value value to set the Idpool
     */
    public void setIdpool(Integer value) {
        setAttributeInternal(IDPOOL, value);
    }

    /**
     * Gets the attribute value for Cf, using the alias name Cf.
     * @return the value of Cf
     */
    public String getCf() {
        return (String)getAttributeInternal(CF);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cf.
     * @param value value to set the Cf
     */
    public void setCf(String value) {
        setAttributeInternal(CF, value);
    }


}
