package model.conf;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 15 09:34:04 CEST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Cnf_SoCnfInvitiFastCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public Cnf_SoCnfInvitiFastCollImpl() {
    }
}

