package model.conf;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 03 13:43:21 CET 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Cnf_SoCnfSdoSpsElencoViewDefImpl extends ViewDefImpl {
    public Cnf_SoCnfSdoSpsElencoViewDefImpl(String name) {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public Cnf_SoCnfSdoSpsElencoViewDefImpl() {
    }
}

