package model.conf;


import model.conf.common.Cnf_SoCnfSdoSpsElencoViewRow;

import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 03 13:43:16 CET 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Cnf_SoCnfSdoSpsElencoViewRowImpl extends ViewRowImpl implements Cnf_SoCnfSdoSpsElencoViewRow {


    public static final int ENTITY_CNF_SOCNFSDOSPS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Codsdosps {
            public Object get(Cnf_SoCnfSdoSpsElencoViewRowImpl obj) {
                return obj.getCodsdosps();
            }

            public void put(Cnf_SoCnfSdoSpsElencoViewRowImpl obj, Object value) {
                obj.setCodsdosps((String) value);
            }
        }
        ,
        Descrizione {
            public Object get(Cnf_SoCnfSdoSpsElencoViewRowImpl obj) {
                return obj.getDescrizione();
            }

            public void put(Cnf_SoCnfSdoSpsElencoViewRowImpl obj, Object value) {
                obj.setDescrizione((String) value);
            }
        }
        ,
        TipoFlusso {
            public Object get(Cnf_SoCnfSdoSpsElencoViewRowImpl obj) {
                return obj.getTipoFlusso();
            }

            public void put(Cnf_SoCnfSdoSpsElencoViewRowImpl obj, Object value) {
                obj.setTipoFlusso((String) value);
            }
        }
        ,
        DataFineValidita {
            public Object get(Cnf_SoCnfSdoSpsElencoViewRowImpl obj) {
                return obj.getDataFineValidita();
            }

            public void put(Cnf_SoCnfSdoSpsElencoViewRowImpl obj, Object value) {
                obj.setDataFineValidita((Date) value);
            }
        }
        ,
        DataInizioValidita {
            public Object get(Cnf_SoCnfSdoSpsElencoViewRowImpl obj) {
                return obj.getDataInizioValidita();
            }

            public void put(Cnf_SoCnfSdoSpsElencoViewRowImpl obj, Object value) {
                obj.setDataInizioValidita((Date) value);
            }
        }
        ;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public abstract Object get(Cnf_SoCnfSdoSpsElencoViewRowImpl object);

        public abstract void put(Cnf_SoCnfSdoSpsElencoViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CODSDOSPS = AttributesEnum.Codsdosps.index();
    public static final int DESCRIZIONE = AttributesEnum.Descrizione.index();
    public static final int TIPOFLUSSO = AttributesEnum.TipoFlusso.index();
    public static final int DATAFINEVALIDITA = AttributesEnum.DataFineValidita.index();
    public static final int DATAINIZIOVALIDITA = AttributesEnum.DataInizioValidita.index();

    /**
     * This is the default constructor (do not remove).
     */
    public Cnf_SoCnfSdoSpsElencoViewRowImpl() {
    }

    /**
     * Gets Cnf_SoCnfSdosps entity object.
     * @return the Cnf_SoCnfSdosps
     */
    public Cnf_SoCnfSdospsImpl getCnf_SoCnfSdosps() {
        return (Cnf_SoCnfSdospsImpl) getEntity(ENTITY_CNF_SOCNFSDOSPS);
    }


    /**
     * Gets the attribute value for CODSDOSPS using the alias name Codsdosps.
     * @return the CODSDOSPS
     */
    public String getCodsdosps() {
        return (String) getAttributeInternal(CODSDOSPS);
    }

    /**
     * Sets <code>value</code> as attribute value for CODSDOSPS using the alias name Codsdosps.
     * @param value value to set the CODSDOSPS
     */
    public void setCodsdosps(String value) {
        setAttributeInternal(CODSDOSPS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TipoFlusso.
     * @return the TipoFlusso
     */
    public String getTipoFlusso() {
        return (String) getAttributeInternal(TIPOFLUSSO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TipoFlusso.
     * @param value value to set the  TipoFlusso
     */
    public void setTipoFlusso(String value) {
        setAttributeInternal(TIPOFLUSSO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DataInizioValidita.
     * @return the DataInizioValidita
     */
    public Date getDataInizioValidita() {
        return (Date) getAttributeInternal(DATAINIZIOVALIDITA);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DataInizioValidita.
     * @param value value to set the  DataInizioValidita
     */
    public void setDataInizioValidita(Date value) {
        setAttributeInternal(DATAINIZIOVALIDITA, value);
    }


    /**
     * Gets the attribute value for DATA_FINE_VALIDITA using the alias name DataFineValidita.
     * @return the DATA_FINE_VALIDITA
     */
    public Date getDataFineValidita() {
        return (Date) getAttributeInternal(DATAFINEVALIDITA);
    }

    /**
     * Sets <code>value</code> as attribute value for DATA_FINE_VALIDITA using the alias name DataFineValidita.
     * @param value value to set the DATA_FINE_VALIDITA
     */
    public void setDataFineValidita(Date value) {
        setAttributeInternal(DATAFINEVALIDITA, value);
    }

    /**
     * Gets the attribute value for DESCRIZIONE using the alias name Descrizione.
     * @return the DESCRIZIONE
     */
    public String getDescrizione() {
        return (String) getAttributeInternal(DESCRIZIONE);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIZIONE using the alias name Descrizione.
     * @param value value to set the DESCRIZIONE
     */
    public void setDescrizione(String value) {
        setAttributeInternal(DESCRIZIONE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}

