package model.conf;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.Key;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class Cnf_SoCnfComuniZoneParamImpl extends EntityImpl {


    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(Cnf_SoCnfComuniZoneParamImpl obj) {
                return obj.getId();
            }

            public void put(Cnf_SoCnfComuniZoneParamImpl obj, Object value) {
                obj.setId((Integer) value);
            }
        }
        ,
        Codcom {
            public Object get(Cnf_SoCnfComuniZoneParamImpl obj) {
                return obj.getCodcom();
            }

            public void put(Cnf_SoCnfComuniZoneParamImpl obj, Object value) {
                obj.setCodcom((String) value);
            }
        }
        ,
        Coddistrzona {
            public Object get(Cnf_SoCnfComuniZoneParamImpl obj) {
                return obj.getCoddistrzona();
            }

            public void put(Cnf_SoCnfComuniZoneParamImpl obj, Object value) {
                obj.setCoddistrzona((Integer) value);
            }
        }
        ,
        Tpscr {
            public Object get(Cnf_SoCnfComuniZoneParamImpl obj) {
                return obj.getTpscr();
            }

            public void put(Cnf_SoCnfComuniZoneParamImpl obj, Object value) {
                obj.setTpscr((String) value);
            }
        }
        ,
        Altro {
            public Object get(Cnf_SoCnfComuniZoneParamImpl obj) {
                return obj.getAltro();
            }

            public void put(Cnf_SoCnfComuniZoneParamImpl obj, Object value) {
                obj.setAltro((String) value);
            }
        }
        ,
        Ulss {
            public Object get(Cnf_SoCnfComuniZoneParamImpl obj) {
                return obj.getUlss();
            }

            public void put(Cnf_SoCnfComuniZoneParamImpl obj, Object value) {
                obj.setUlss((String) value);
            }
        }
        ,
        ReleaseCodeCom {
            public Object get(Cnf_SoCnfComuniZoneParamImpl obj) {
                return obj.getReleaseCodeCom();
            }

            public void put(Cnf_SoCnfComuniZoneParamImpl obj, Object value) {
                obj.setReleaseCodeCom((Integer) value);
            }
        }
        ,
        Cnf_SoDistrettoZona {
            public Object get(Cnf_SoCnfComuniZoneParamImpl obj) {
                return obj.getCnf_SoDistrettoZona();
            }

            public void put(Cnf_SoCnfComuniZoneParamImpl obj, Object value) {
                obj.setCnf_SoDistrettoZona((Cnf_SoDistrettoZonaImpl) value);
            }
        }
        ,
        Cnf_SoComune {
            public Object get(Cnf_SoCnfComuniZoneParamImpl obj) {
                return obj.getCnf_SoComune();
            }

            public void put(Cnf_SoCnfComuniZoneParamImpl obj, Object value) {
                obj.setCnf_SoComune((Cnf_SoComuneImpl) value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(Cnf_SoCnfComuniZoneParamImpl object);

        public abstract void put(Cnf_SoCnfComuniZoneParamImpl object, Object value);

        public int index() {
            return Cnf_SoCnfComuniZoneParamImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return Cnf_SoCnfComuniZoneParamImpl.AttributesEnum.firstIndex() + Cnf_SoCnfComuniZoneParamImpl.AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = Cnf_SoCnfComuniZoneParamImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int CODCOM = AttributesEnum.Codcom.index();
    public static final int CODDISTRZONA = AttributesEnum.Coddistrzona.index();
    public static final int TPSCR = AttributesEnum.Tpscr.index();
    public static final int ALTRO = AttributesEnum.Altro.index();
    public static final int ULSS = AttributesEnum.Ulss.index();
    public static final int RELEASECODECOM = AttributesEnum.ReleaseCodeCom.index();
    public static final int CNF_SODISTRETTOZONA = AttributesEnum.Cnf_SoDistrettoZona.index();
    public static final int CNF_SOCOMUNE = AttributesEnum.Cnf_SoComune.index();

    /**
     *
     *  This is the default constructor (do not remove)
     */
  public Cnf_SoCnfComuniZoneParamImpl()
  {
  }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.conf.Cnf_SoCnfComuniZoneParam");
    }


    /**
     *
     *  Gets the attribute value for Id, using the alias name Id
     */
    public Integer getId()
  {
    return (Integer)getAttributeInternal(ID);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Integer value)
  {
    setAttributeInternal(ID, value);
  }

  /**
   * 
   *  Gets the attribute value for Codcom, using the alias name Codcom
   */
  public String getCodcom()
  {
    return (String)getAttributeInternal(CODCOM);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Codcom
   */
  public void setCodcom(String value)
  {
    setAttributeInternal(CODCOM, value);
  }

  /**
   * 
   *  Gets the attribute value for Coddistrzona, using the alias name Coddistrzona
   */
  public Integer getCoddistrzona()
  {
    return (Integer)getAttributeInternal(CODDISTRZONA);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Coddistrzona
   */
  public void setCoddistrzona(Integer value)
  {
    setAttributeInternal(CODDISTRZONA, value);
  }

  /**
   * 
   *  Gets the attribute value for Tpscr, using the alias name Tpscr
   */
  public String getTpscr()
  {
    return (String)getAttributeInternal(TPSCR);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Tpscr
   */
  public void setTpscr(String value)
  {
    setAttributeInternal(TPSCR, value);
  }

  /**
   * 
   *  Gets the attribute value for Altro, using the alias name Altro
   */
  public String getAltro()
  {
    return (String)getAttributeInternal(ALTRO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Altro
   */
  public void setAltro(String value)
  {
    setAttributeInternal(ALTRO, value);
  }

  /**
   * 
   *  Gets the attribute value for Ulss, using the alias name Ulss
   */
  public String getUlss()
  {
    return (String)getAttributeInternal(ULSS);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Ulss
   */
  public void setUlss(String value)
  {
    setAttributeInternal(ULSS, value);
  }

    /**
     * Gets the attribute value for ReleaseCodeCom, using the alias name ReleaseCodeCom.
     * @return the value of ReleaseCodeCom
     */
    public Integer getReleaseCodeCom() {
        return (Integer) getAttributeInternal(RELEASECODECOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReleaseCodeCom.
     * @param value value to set the ReleaseCodeCom
     */
    public void setReleaseCodeCom(Integer value) {
        setAttributeInternal(RELEASECODECOM, value);
    }

    /**
     *
     *  getAttrInvokeAccessor: generated method. Do not modify.
     */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

  /**
   * 
   *  Gets the associated entity Cnf_SoDistrettoZonaImpl
   */
  public Cnf_SoDistrettoZonaImpl getCnf_SoDistrettoZona()
  {
    return (Cnf_SoDistrettoZonaImpl)getAttributeInternal(CNF_SODISTRETTOZONA);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity Cnf_SoDistrettoZonaImpl
   */
  public void setCnf_SoDistrettoZona(Cnf_SoDistrettoZonaImpl value)
  {
    setAttributeInternal(CNF_SODISTRETTOZONA, value);
  }


    /**
     * @return the associated entity Cnf_SoComuneImpl.
     */
    public Cnf_SoComuneImpl getCnf_SoComune() {
        return (Cnf_SoComuneImpl) getAttributeInternal(CNF_SOCOMUNE);
    }

    /**
     * Sets <code>value</code> as the associated entity Cnf_SoComuneImpl.
     */
    public void setCnf_SoComune(Cnf_SoComuneImpl value) {
        setAttributeInternal(CNF_SOCOMUNE, value);
    }


    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer id) {
        return new Key(new Object[] { id });
    }

    public boolean validateDipendenza() {
        //deve essere indicato o il comune o la zona
        if(this.getCodcom()==null && this.getCoddistrzona()==null)
            return false;
        
        //deve essere indicato SOLO il comune o SOLO la zona
        if(this.getCodcom()!=null && this.getCoddistrzona()!=null)
            return false;
        
        return true;
    }
    
    protected void doDML(int operation, TransactionEvent e) {
        if(operation==this.DML_INSERT){
            //inserisco il codice da sequenza
            SequenceImpl s = new SequenceImpl("SO_COM_ZONE_PARAM_SEQ", getDBTransaction());     
            this.setId(s.getSequenceNumber().intValue());
        }  
        super.doDML(operation, e);
    }

}
