package model.conf;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 18 14:31:59 CEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Cnf_SoCnfRefCa1livGRUPPIViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Cnf_SoCnfRefCa1livGRUPPIViewImpl() {
    }
}

