package model.soggetto;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class Sogg_StatoViewImpl extends ViewObjectImpl {
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public Sogg_StatoViewImpl()
  {
  }
}