package model.soggetto;

import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 07 14:54:31 CET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Sogg_SoEsclusioneViewRowImpl extends ViewRowImpl {

    public static final int ENTITY_SOGG_SOESCLUSIONE = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Idescl {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getIdescl();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setIdescl((Integer) value);
            }
        }
        ,
        Idcnfescl {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getIdcnfescl();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setIdcnfescl((Integer) value);
            }
        }
        ,
        Idinvito {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getIdinvito();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setIdinvito((Integer) value);
            }
        }
        ,
        Codts {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getCodts();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setCodts((String) value);
            }
        }
        ,
        Dtescl {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getDtescl();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setDtescl((Date) value);
            }
        }
        ,
        Ultima {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getUltima();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setUltima((Integer) value);
            }
        }
        ,
        Dtrichiamo {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getDtrichiamo();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setDtrichiamo((Date) value);
            }
        }
        ,
        Lettrichiamo {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getLettrichiamo();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setLettrichiamo((Integer) value);
            }
        }
        ,
        Roundorgescl {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getRoundorgescl();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setRoundorgescl((Integer) value);
            }
        }
        ,
        Roundindiv {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getRoundindiv();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setRoundindiv((Integer) value);
            }
        }
        ,
        Dtannull {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getDtannull();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setDtannull((Date) value);
            }
        }
        ,
        Dtmodescl {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getDtmodescl();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setDtmodescl((Date) value);
            }
        }
        ,
        Noteescl {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getNoteescl();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setNoteescl((String) value);
            }
        }
        ,
        Ulss {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getUlss();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setUlss((String) value);
            }
        }
        ,
        Tpscr {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getTpscr();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setTpscr((String) value);
            }
        }
        ,
        Tpescl {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getTpescl();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setTpescl((String) value);
            }
        }
        ,
        Dtfine {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getDtfine();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setDtfine((Date) value);
            }
        }
        ,
        Numgg {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getNumgg();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setNumgg((Integer) value);
            }
        }
        ,
        Dtcreazione {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getDtcreazione();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setDtcreazione((Date) value);
            }
        }
        ,
        Opcreazione {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getOpcreazione();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setOpcreazione((String) value);
            }
        }
        ,
        Opmodifica {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getOpmodifica();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setOpmodifica((String) value);
            }
        }
        ,
        Tprich {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getTprich();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setTprich((String) value);
            }
        }
        ,
        EsclFiglie {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getEsclFiglie();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setEsclFiglie((String) value);
            }
        }
        ,
        IdesclPadre {
            public Object get(Sogg_SoEsclusioneViewRowImpl obj) {
                return obj.getIdesclPadre();
            }

            public void put(Sogg_SoEsclusioneViewRowImpl obj, Object value) {
                obj.setIdesclPadre((Integer) value);
            }
        }
        ;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public abstract Object get(Sogg_SoEsclusioneViewRowImpl object);

        public abstract void put(Sogg_SoEsclusioneViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDESCL = AttributesEnum.Idescl.index();
    public static final int IDCNFESCL = AttributesEnum.Idcnfescl.index();
    public static final int IDINVITO = AttributesEnum.Idinvito.index();
    public static final int CODTS = AttributesEnum.Codts.index();
    public static final int DTESCL = AttributesEnum.Dtescl.index();
    public static final int ULTIMA = AttributesEnum.Ultima.index();
    public static final int DTRICHIAMO = AttributesEnum.Dtrichiamo.index();
    public static final int LETTRICHIAMO = AttributesEnum.Lettrichiamo.index();
    public static final int ROUNDORGESCL = AttributesEnum.Roundorgescl.index();
    public static final int ROUNDINDIV = AttributesEnum.Roundindiv.index();
    public static final int DTANNULL = AttributesEnum.Dtannull.index();
    public static final int DTMODESCL = AttributesEnum.Dtmodescl.index();
    public static final int NOTEESCL = AttributesEnum.Noteescl.index();
    public static final int ULSS = AttributesEnum.Ulss.index();
    public static final int TPSCR = AttributesEnum.Tpscr.index();
    public static final int TPESCL = AttributesEnum.Tpescl.index();
    public static final int DTFINE = AttributesEnum.Dtfine.index();
    public static final int NUMGG = AttributesEnum.Numgg.index();
    public static final int DTCREAZIONE = AttributesEnum.Dtcreazione.index();
    public static final int OPCREAZIONE = AttributesEnum.Opcreazione.index();
    public static final int OPMODIFICA = AttributesEnum.Opmodifica.index();
    public static final int TPRICH = AttributesEnum.Tprich.index();
    public static final int ESCLFIGLIE = AttributesEnum.EsclFiglie.index();
    public static final int IDESCLPADRE = AttributesEnum.IdesclPadre.index();

    /**
     * This is the default constructor (do not remove).
     */
    public Sogg_SoEsclusioneViewRowImpl() {
    }

    /**
     * Gets Sogg_SoEsclusione entity object.
     * @return the Sogg_SoEsclusione
     */
    public Sogg_SoEsclusioneImpl getSogg_SoEsclusione() {
        return (Sogg_SoEsclusioneImpl) getEntity(ENTITY_SOGG_SOESCLUSIONE);
    }

    /**
     * Gets the attribute value for IDESCL using the alias name Idescl.
     * @return the IDESCL
     */
    public Integer getIdescl() {
        return (Integer) getAttributeInternal(IDESCL);
    }

    /**
     * Sets <code>value</code> as attribute value for IDESCL using the alias name Idescl.
     * @param value value to set the IDESCL
     */
    public void setIdescl(Integer value) {
        setAttributeInternal(IDESCL, value);
    }

    /**
     * Gets the attribute value for IDCNFESCL using the alias name Idcnfescl.
     * @return the IDCNFESCL
     */
    public Integer getIdcnfescl() {
        return (Integer) getAttributeInternal(IDCNFESCL);
    }

    /**
     * Sets <code>value</code> as attribute value for IDCNFESCL using the alias name Idcnfescl.
     * @param value value to set the IDCNFESCL
     */
    public void setIdcnfescl(Integer value) {
        setAttributeInternal(IDCNFESCL, value);
    }

    /**
     * Gets the attribute value for IDINVITO using the alias name Idinvito.
     * @return the IDINVITO
     */
    public Integer getIdinvito() {
        return (Integer) getAttributeInternal(IDINVITO);
    }

    /**
     * Sets <code>value</code> as attribute value for IDINVITO using the alias name Idinvito.
     * @param value value to set the IDINVITO
     */
    public void setIdinvito(Integer value) {
        setAttributeInternal(IDINVITO, value);
    }

    /**
     * Gets the attribute value for CODTS using the alias name Codts.
     * @return the CODTS
     */
    public String getCodts() {
        return (String) getAttributeInternal(CODTS);
    }

    /**
     * Sets <code>value</code> as attribute value for CODTS using the alias name Codts.
     * @param value value to set the CODTS
     */
    public void setCodts(String value) {
        setAttributeInternal(CODTS, value);
    }

    /**
     * Gets the attribute value for DTESCL using the alias name Dtescl.
     * @return the DTESCL
     */
    public Date getDtescl() {
        return (Date) getAttributeInternal(DTESCL);
    }

    /**
     * Sets <code>value</code> as attribute value for DTESCL using the alias name Dtescl.
     * @param value value to set the DTESCL
     */
    public void setDtescl(Date value) {
        setAttributeInternal(DTESCL, value);
    }

    /**
     * Gets the attribute value for ULTIMA using the alias name Ultima.
     * @return the ULTIMA
     */
    public Integer getUltima() {
        return (Integer) getAttributeInternal(ULTIMA);
    }

    /**
     * Sets <code>value</code> as attribute value for ULTIMA using the alias name Ultima.
     * @param value value to set the ULTIMA
     */
    public void setUltima(Integer value) {
        setAttributeInternal(ULTIMA, value);
    }

    /**
     * Gets the attribute value for DTRICHIAMO using the alias name Dtrichiamo.
     * @return the DTRICHIAMO
     */
    public Date getDtrichiamo() {
        return (Date) getAttributeInternal(DTRICHIAMO);
    }

    /**
     * Sets <code>value</code> as attribute value for DTRICHIAMO using the alias name Dtrichiamo.
     * @param value value to set the DTRICHIAMO
     */
    public void setDtrichiamo(Date value) {
        setAttributeInternal(DTRICHIAMO, value);
    }

    /**
     * Gets the attribute value for LETTRICHIAMO using the alias name Lettrichiamo.
     * @return the LETTRICHIAMO
     */
    public Integer getLettrichiamo() {
        return (Integer) getAttributeInternal(LETTRICHIAMO);
    }

    /**
     * Sets <code>value</code> as attribute value for LETTRICHIAMO using the alias name Lettrichiamo.
     * @param value value to set the LETTRICHIAMO
     */
    public void setLettrichiamo(Integer value) {
        setAttributeInternal(LETTRICHIAMO, value);
    }

    /**
     * Gets the attribute value for ROUNDORGESCL using the alias name Roundorgescl.
     * @return the ROUNDORGESCL
     */
    public Integer getRoundorgescl() {
        return (Integer) getAttributeInternal(ROUNDORGESCL);
    }

    /**
     * Sets <code>value</code> as attribute value for ROUNDORGESCL using the alias name Roundorgescl.
     * @param value value to set the ROUNDORGESCL
     */
    public void setRoundorgescl(Integer value) {
        setAttributeInternal(ROUNDORGESCL, value);
    }

    /**
     * Gets the attribute value for ROUNDINDIV using the alias name Roundindiv.
     * @return the ROUNDINDIV
     */
    public Integer getRoundindiv() {
        return (Integer) getAttributeInternal(ROUNDINDIV);
    }

    /**
     * Sets <code>value</code> as attribute value for ROUNDINDIV using the alias name Roundindiv.
     * @param value value to set the ROUNDINDIV
     */
    public void setRoundindiv(Integer value) {
        setAttributeInternal(ROUNDINDIV, value);
    }

    /**
     * Gets the attribute value for DTANNULL using the alias name Dtannull.
     * @return the DTANNULL
     */
    public Date getDtannull() {
        return (Date) getAttributeInternal(DTANNULL);
    }

    /**
     * Sets <code>value</code> as attribute value for DTANNULL using the alias name Dtannull.
     * @param value value to set the DTANNULL
     */
    public void setDtannull(Date value) {
        setAttributeInternal(DTANNULL, value);
    }

    /**
     * Gets the attribute value for DTMODESCL using the alias name Dtmodescl.
     * @return the DTMODESCL
     */
    public Date getDtmodescl() {
        return (Date) getAttributeInternal(DTMODESCL);
    }

    /**
     * Sets <code>value</code> as attribute value for DTMODESCL using the alias name Dtmodescl.
     * @param value value to set the DTMODESCL
     */
    public void setDtmodescl(Date value) {
        setAttributeInternal(DTMODESCL, value);
    }

    /**
     * Gets the attribute value for NOTEESCL using the alias name Noteescl.
     * @return the NOTEESCL
     */
    public String getNoteescl() {
        return (String) getAttributeInternal(NOTEESCL);
    }

    /**
     * Sets <code>value</code> as attribute value for NOTEESCL using the alias name Noteescl.
     * @param value value to set the NOTEESCL
     */
    public void setNoteescl(String value) {
        setAttributeInternal(NOTEESCL, value);
    }

    /**
     * Gets the attribute value for ULSS using the alias name Ulss.
     * @return the ULSS
     */
    public String getUlss() {
        return (String) getAttributeInternal(ULSS);
    }

    /**
     * Sets <code>value</code> as attribute value for ULSS using the alias name Ulss.
     * @param value value to set the ULSS
     */
    public void setUlss(String value) {
        setAttributeInternal(ULSS, value);
    }

    /**
     * Gets the attribute value for TPSCR using the alias name Tpscr.
     * @return the TPSCR
     */
    public String getTpscr() {
        return (String) getAttributeInternal(TPSCR);
    }

    /**
     * Sets <code>value</code> as attribute value for TPSCR using the alias name Tpscr.
     * @param value value to set the TPSCR
     */
    public void setTpscr(String value) {
        setAttributeInternal(TPSCR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Tpescl.
     * @return the Tpescl
     */
    public String getTpescl() {
        return (String) getAttributeInternal(TPESCL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Tpescl.
     * @param value value to set the  Tpescl
     */
    public void setTpescl(String value) {
        setAttributeInternal(TPESCL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Dtfine.
     * @return the Dtfine
     */
    public Date getDtfine() {
        return (Date) getAttributeInternal(DTFINE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Dtfine.
     * @param value value to set the  Dtfine
     */
    public void setDtfine(Date value) {
        setAttributeInternal(DTFINE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Numgg.
     * @return the Numgg
     */
    public Integer getNumgg() {
        return (Integer) getAttributeInternal(NUMGG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Numgg.
     * @param value value to set the  Numgg
     */
    public void setNumgg(Integer value) {
        setAttributeInternal(NUMGG, value);
    }

    /**
     * Gets the attribute value for DTCREAZIONE using the alias name Dtcreazione.
     * @return the DTCREAZIONE
     */
    public Date getDtcreazione() {
        return (Date) getAttributeInternal(DTCREAZIONE);
    }

    /**
     * Sets <code>value</code> as attribute value for DTCREAZIONE using the alias name Dtcreazione.
     * @param value value to set the DTCREAZIONE
     */
    public void setDtcreazione(Date value) {
        setAttributeInternal(DTCREAZIONE, value);
    }

    /**
     * Gets the attribute value for OPCREAZIONE using the alias name Opcreazione.
     * @return the OPCREAZIONE
     */
    public String getOpcreazione() {
        return (String) getAttributeInternal(OPCREAZIONE);
    }

    /**
     * Sets <code>value</code> as attribute value for OPCREAZIONE using the alias name Opcreazione.
     * @param value value to set the OPCREAZIONE
     */
    public void setOpcreazione(String value) {
        setAttributeInternal(OPCREAZIONE, value);
    }

    /**
     * Gets the attribute value for OPMODIFICA using the alias name Opmodifica.
     * @return the OPMODIFICA
     */
    public String getOpmodifica() {
        return (String) getAttributeInternal(OPMODIFICA);
    }

    /**
     * Sets <code>value</code> as attribute value for OPMODIFICA using the alias name Opmodifica.
     * @param value value to set the OPMODIFICA
     */
    public void setOpmodifica(String value) {
        setAttributeInternal(OPMODIFICA, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Tprich.
     * @return the Tprich
     */
    public String getTprich() {
        return (String) getAttributeInternal(TPRICH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Tprich.
     * @param value value to set the  Tprich
     */
    public void setTprich(String value) {
        setAttributeInternal(TPRICH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EsclFiglie.
     * @return the EsclFiglie
     */
    public String getEsclFiglie() {
        return (String) getAttributeInternal(ESCLFIGLIE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EsclFiglie.
     * @param value value to set the  EsclFiglie
     */
    public void setEsclFiglie(String value) {
        setAttributeInternal(ESCLFIGLIE, value);
    }

    /**
     * Gets the attribute value for IDESCL_PADRE using the alias name IdesclPadre.
     * @return the IDESCL_PADRE
     */
    public Integer getIdesclPadre() {
        return (Integer) getAttributeInternal(IDESCLPADRE);
    }

    /**
     * Sets <code>value</code> as attribute value for IDESCL_PADRE using the alias name IdesclPadre.
     * @param value value to set the IDESCL_PADRE
     */
    public void setIdesclPadre(Integer value) {
        setAttributeInternal(IDESCLPADRE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}

