package model.soggetto;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.RowID;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class Sogg_SoCnfTipiDocImpl extends EntityImpl {


    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        IdTipoDoc,
        Ulss,
        Descrizione,
        DescrBreve,
        Dtiniziovalidita,
        Dtfinevalidita,
        Ordine,
        RowID;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int IDTIPODOC = AttributesEnum.IdTipoDoc.index();
    public static final int ULSS = AttributesEnum.Ulss.index();
    public static final int DESCRIZIONE = AttributesEnum.Descrizione.index();
    public static final int DESCRBREVE = AttributesEnum.DescrBreve.index();
    public static final int DTINIZIOVALIDITA = AttributesEnum.Dtiniziovalidita.index();
    public static final int DTFINEVALIDITA = AttributesEnum.Dtfinevalidita.index();
    public static final int ORDINE = AttributesEnum.Ordine.index();
    public static final int ROWID = AttributesEnum.RowID.index();

    /**
     *
     *  This is the default constructor (do not remove)
     */
  public Sogg_SoCnfTipiDocImpl()
  {
  }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.soggetto.Sogg_SoCnfTipiDoc");
    }


    /**
     *
     *  Gets the attribute value for IdTipoDoc, using the alias name IdTipoDoc
     */
  public String getIdTipoDoc()
  {
    return (String)getAttributeInternal(IDTIPODOC);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for IdTipoDoc
   */
  public void setIdTipoDoc(String value)
  {
    setAttributeInternal(IDTIPODOC, value);
  }

  /**
   * 
   *  Gets the attribute value for Ulss, using the alias name Ulss
   */
  public String getUlss()
  {
    return (String)getAttributeInternal(ULSS);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Ulss
   */
  public void setUlss(String value)
  {
    setAttributeInternal(ULSS, value);
  }

  /**
   * 
   *  Gets the attribute value for Descrizione, using the alias name Descrizione
   */
  public String getDescrizione()
  {
    return (String)getAttributeInternal(DESCRIZIONE);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Descrizione
   */
  public void setDescrizione(String value)
  {
    setAttributeInternal(DESCRIZIONE, value);
  }

  /**
   * 
   *  Gets the attribute value for DescrBreve, using the alias name DescrBreve
   */
  public String getDescrBreve()
  {
    return (String)getAttributeInternal(DESCRBREVE);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for DescrBreve
   */
  public void setDescrBreve(String value)
  {
    setAttributeInternal(DESCRBREVE, value);
  }

  /**
   * 
   *  Gets the attribute value for Dtiniziovalidita, using the alias name Dtiniziovalidita
   */
  public Date getDtiniziovalidita()
  {
    return (Date)getAttributeInternal(DTINIZIOVALIDITA);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Dtiniziovalidita
   */
  public void setDtiniziovalidita(Date value)
  {
    setAttributeInternal(DTINIZIOVALIDITA, value);
  }

  /**
   * 
   *  Gets the attribute value for Dtfinevalidita, using the alias name Dtfinevalidita
   */
  public Date getDtfinevalidita()
  {
    return (Date)getAttributeInternal(DTFINEVALIDITA);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Dtfinevalidita
   */
  public void setDtfinevalidita(Date value)
  {
    setAttributeInternal(DTFINEVALIDITA, value);
  }

  /**
   * 
   *  Gets the attribute value for Ordine, using the alias name Ordine
   */
  public Integer getOrdine()
  {
    return (Integer)getAttributeInternal(ORDINE);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Ordine
   */
  public void setOrdine(Integer value)
  {
    setAttributeInternal(ORDINE, value);
  }

  /**
   * 
   *  Gets the attribute value for RowID, using the alias name RowID
   */
  public RowID getRowID()
  {
    return (RowID)getAttributeInternal(ROWID);
  }


}
