package model.soggetto;


import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Date;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class Sogg_SoStoricoConsensoViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_SOGG_SOSTORICOCONSENSO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Idstorico {
            public Object get(Sogg_SoStoricoConsensoViewRowImpl obj) {
                return obj.getIdstorico();
            }

            public void put(Sogg_SoStoricoConsensoViewRowImpl obj, Object value) {
                obj.setIdstorico((Integer) value);
            }
        }
        ,
        Codts {
            public Object get(Sogg_SoStoricoConsensoViewRowImpl obj) {
                return obj.getCodts();
            }

            public void put(Sogg_SoStoricoConsensoViewRowImpl obj, Object value) {
                obj.setCodts((String) value);
            }
        }
        ,
        Ulss {
            public Object get(Sogg_SoStoricoConsensoViewRowImpl obj) {
                return obj.getUlss();
            }

            public void put(Sogg_SoStoricoConsensoViewRowImpl obj, Object value) {
                obj.setUlss((String) value);
            }
        }
        ,
        Tpscr {
            public Object get(Sogg_SoStoricoConsensoViewRowImpl obj) {
                return obj.getTpscr();
            }

            public void put(Sogg_SoStoricoConsensoViewRowImpl obj, Object value) {
                obj.setTpscr((String) value);
            }
        }
        ,
        Valore {
            public Object get(Sogg_SoStoricoConsensoViewRowImpl obj) {
                return obj.getValore();
            }

            public void put(Sogg_SoStoricoConsensoViewRowImpl obj, Object value) {
                obj.setValore((Integer) value);
            }
        }
        ,
        InizioVal {
            public Object get(Sogg_SoStoricoConsensoViewRowImpl obj) {
                return obj.getInizioVal();
            }

            public void put(Sogg_SoStoricoConsensoViewRowImpl obj, Object value) {
                obj.setInizioVal((Date) value);
            }
        }
        ,
        OpIns {
            public Object get(Sogg_SoStoricoConsensoViewRowImpl obj) {
                return obj.getOpIns();
            }

            public void put(Sogg_SoStoricoConsensoViewRowImpl obj, Object value) {
                obj.setOpIns((String) value);
            }
        }
        ,
        FineVal {
            public Object get(Sogg_SoStoricoConsensoViewRowImpl obj) {
                return obj.getFineVal();
            }

            public void put(Sogg_SoStoricoConsensoViewRowImpl obj, Object value) {
                obj.setFineVal((Date) value);
            }
        }
        ,
        OpMod {
            public Object get(Sogg_SoStoricoConsensoViewRowImpl obj) {
                return obj.getOpMod();
            }

            public void put(Sogg_SoStoricoConsensoViewRowImpl obj, Object value) {
                obj.setOpMod((String) value);
            }
        }
        ,
        Tipo {
            public Object get(Sogg_SoStoricoConsensoViewRowImpl obj) {
                return obj.getTipo();
            }

            public void put(Sogg_SoStoricoConsensoViewRowImpl obj, Object value) {
                obj.setTipo((String) value);
            }
        }
        ;
        static AttributesEnum[] vals = null;
        ;
        private static int firstIndex = 0;

        public abstract Object get(Sogg_SoStoricoConsensoViewRowImpl object);

        public abstract void put(Sogg_SoStoricoConsensoViewRowImpl object, Object value);

        public int index() {
            return Sogg_SoStoricoConsensoViewRowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return Sogg_SoStoricoConsensoViewRowImpl.AttributesEnum.firstIndex() + Sogg_SoStoricoConsensoViewRowImpl.AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = Sogg_SoStoricoConsensoViewRowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDSTORICO = AttributesEnum.Idstorico.index();
    public static final int CODTS = AttributesEnum.Codts.index();
    public static final int ULSS = AttributesEnum.Ulss.index();
    public static final int TPSCR = AttributesEnum.Tpscr.index();
    public static final int VALORE = AttributesEnum.Valore.index();
    public static final int INIZIOVAL = AttributesEnum.InizioVal.index();
    public static final int OPINS = AttributesEnum.OpIns.index();
    public static final int FINEVAL = AttributesEnum.FineVal.index();
    public static final int OPMOD = AttributesEnum.OpMod.index();
    public static final int TIPO = AttributesEnum.Tipo.index();

    /**
     *
     *  This is the default constructor (do not remove)
     */
  public Sogg_SoStoricoConsensoViewRowImpl()
  {
  }

  /**
   * 
   *  Gets Sogg_SoStoricoConsenso entity object.
   */
  public Sogg_SoStoricoConsensoImpl getSogg_SoStoricoConsenso()
  {
    return (Sogg_SoStoricoConsensoImpl)getEntity(0);
  }

  /**
     *
     *  Gets the attribute value for IDSTORICO using the alias name Idstorico
     */
    public Integer getIdstorico()
  {
        return (Integer) getAttributeInternal(IDSTORICO);
    }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDSTORICO using the alias name Idstorico
   */
  public void setIdstorico(Integer value)
  {
    setAttributeInternal(IDSTORICO, value);
  }

  /**
   * 
   *  Gets the attribute value for CODTS using the alias name Codts
   */
  public String getCodts()
  {
    return (String)getAttributeInternal(CODTS);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for CODTS using the alias name Codts
   */
  public void setCodts(String value)
  {
    setAttributeInternal(CODTS, value);
  }

  /**
   * 
   *  Gets the attribute value for ULSS using the alias name Ulss
   */
  public String getUlss()
  {
    return (String)getAttributeInternal(ULSS);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for ULSS using the alias name Ulss
   */
  public void setUlss(String value)
  {
    setAttributeInternal(ULSS, value);
  }

  /**
   * 
   *  Gets the attribute value for TPSCR using the alias name Tpscr
   */
  public String getTpscr()
  {
    return (String)getAttributeInternal(TPSCR);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for TPSCR using the alias name Tpscr
   */
  public void setTpscr(String value)
  {
    setAttributeInternal(TPSCR, value);
  }

  /**
     *
     *  Gets the attribute value for VALORE using the alias name Valore
     */
    public Integer getValore()
  {
        return (Integer) getAttributeInternal(VALORE);
    }

  /**
   * 
   *  Sets <code>value</code> as attribute value for VALORE using the alias name Valore
   */
  public void setValore(Integer value)
  {
    setAttributeInternal(VALORE, value);
  }

  /**
   * 
   *  Gets the attribute value for INIZIO_VAL using the alias name InizioVal
   */
  public Date getInizioVal()
  {
    return (Date)getAttributeInternal(INIZIOVAL);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for INIZIO_VAL using the alias name InizioVal
   */
  public void setInizioVal(Date value)
  {
    setAttributeInternal(INIZIOVAL, value);
  }

  /**
   * 
   *  Gets the attribute value for OP_INS using the alias name OpIns
   */
  public String getOpIns()
  {
    return (String)getAttributeInternal(OPINS);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for OP_INS using the alias name OpIns
   */
  public void setOpIns(String value)
  {
    setAttributeInternal(OPINS, value);
  }

  /**
   * 
   *  Gets the attribute value for FINE_VAL using the alias name FineVal
   */
  public Date getFineVal()
  {
    return (Date)getAttributeInternal(FINEVAL);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for FINE_VAL using the alias name FineVal
   */
  public void setFineVal(Date value)
  {
    setAttributeInternal(FINEVAL, value);
  }

  /**
   * 
   *  Gets the attribute value for OP_MOD using the alias name OpMod
   */
  public String getOpMod()
  {
    return (String)getAttributeInternal(OPMOD);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for OP_MOD using the alias name OpMod
   */
  public void setOpMod(String value)
  {
    setAttributeInternal(OPMOD, value);
  }

    /**
     * Gets the attribute value for TIPO using the alias name Tipo.
     * @return the TIPO
     */
    public String getTipo() {
        return (String) getAttributeInternal(TIPO);
    }

    /**
     * Sets <code>value</code> as attribute value for TIPO using the alias name Tipo.
     * @param value value to set the TIPO
     */
    public void setTipo(String value) {
        setAttributeInternal(TIPO, value);
    }

    /**
     *
     *  getAttrInvokeAccessor: generated method. Do not modify.
     */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}