package model.soggetto;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 16 14:50:01 CEST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Sogg_StInvitiAllegBckViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Sogg_StInvitiAllegBckViewImpl() {
    }
}

