package model.referto.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 04 10:03:44 CEST 2018
// ---------------------------------------------------------------------
public interface Ref_SoCnfIndicazioniViewRow extends Row {
    String getDescrizione();


    String getGruppo();

    Integer getIdcnfref();


    void setDescrizione(String value);


    void setGruppo(String value);

    void setIdcnfref(Integer value);

    oracle.jbo.domain.Number getDx();

    oracle.jbo.domain.Number getSx();

    void setDx(oracle.jbo.domain.Number value);

    void setSx(oracle.jbo.domain.Number value);
}

