package model.pianolavoro.client;

import java.math.BigDecimal;

import oracle.jbo.RowIterator;
import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Date;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class PL_SoAppuntamentoExtendedViewRowClient extends RowImpl implements model.pianolavoro.common.PL_SoAppuntamentoExtendedViewRow 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public PL_SoAppuntamentoExtendedViewRowClient()
  {
  }


    public BigDecimal getNumvetrino() {
        return (BigDecimal) getAttribute("Numvetrino");
    }

    public void setNumvetrino(BigDecimal value) {
        setAttribute("Numvetrino", value);
    }


    public BigDecimal getCodCampione() {
        return (BigDecimal)getAttribute("CodCampione");
    }


    public void setCodCampione(BigDecimal value) {
        setAttribute("CodCampione", value);
    }


    public RowIterator getPL_SoEsclusioneDEFExtendedView() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this, "getPL_SoEsclusioneDEFExtendedView", null, null);
        return (RowIterator) _ret;
    }

    public RowIterator getPL_SoEsclusioneTEMPExtendedView() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this, "getPL_SoEsclusioneTEMPExtendedView", null, null);
        return (RowIterator) _ret;
    }

    public String getCap() {
        return (String) getAttribute("Cap");
    }

    public String getCap1() {
        return (String) getAttribute("Cap1");
    }

    public String getCap2() {
        return (String) getAttribute("Cap2");
    }

    public String getCentro() {
        return (String) getAttribute("Centro");
    }

    public String getCf() {
        return (String) getAttribute("Cf");
    }

    public String getCodRichiesta() {
        return (String) getAttribute("CodRichiesta");
    }

    public String getCodcom() {
        return (String) getAttribute("Codcom");
    }

    public String getCodcom1() {
        return (String) getAttribute("Codcom1");
    }

    public String getCodcom2() {
        return (String) getAttribute("Codcom2");
    }

    public String getCodcomscr() {
        return (String) getAttribute("Codcomscr");
    }

    public String getCodesitoinvito() {
        return (String) getAttribute("Codesitoinvito");
    }

    public String getCodesitoinvito1() {
        return (String) getAttribute("Codesitoinvito1");
    }

    public String getCodpr() {
        return (String) getAttribute("Codpr");
    }

    public String getCodpr1() {
        return (String) getAttribute("Codpr1");
    }

    public String getCodpr2() {
        return (String) getAttribute("Codpr2");
    }

    public String getCodts() {
        return (String) getAttribute("Codts");
    }

    public String getCodts1() {
        return (String) getAttribute("Codts1");
    }

    public String getCognome() {
        return (String) getAttribute("Cognome");
    }

    public String getComune() {
        return (String) getAttribute("Comune");
    }

    public Date getDataNascita() {
        return (Date) getAttribute("DataNascita");
    }

    public String getDescrizione() {
        return (String) getAttribute("Descrizione");
    }

    public String getDescrizione1() {
        return (String) getAttribute("Descrizione1");
    }

    public Integer getDispslot() {
        return (Integer) getAttribute("Dispslot");
    }

    public Date getDtapp() {
        return (Date) getAttribute("Dtapp");
    }

    public String getEsitoinvito() {
        return (String) getAttribute("Esitoinvito");
    }

    public Integer getIdacc1liv() {
        return (Integer) getAttribute("Idacc1liv");
    }

    public Integer getIdaccco1liv() {
        return (Integer) getAttribute("Idaccco1liv");
    }

    public Integer getIdaccma1liv() {
        return (Integer) getAttribute("Idaccma1liv");
    }

    public Integer getIdapp() {
        return (Integer) getAttribute("Idapp");
    }

    public Integer getIdapp1() {
        return (Integer) getAttribute("Idapp1");
    }

    public Integer getIdcentro() {
        return (Integer) getAttribute("Idcentro");
    }

    public Integer getIdcentro1() {
        return (Integer) getAttribute("Idcentro1");
    }

    public Integer getIdinvito() {
        return (Integer) getAttribute("Idinvito");
    }

    public Integer getIdinvito1() {
        return (Integer) getAttribute("Idinvito1");
    }

    public String getIdtpinvito() {
        return (String) getAttribute("Idtpinvito");
    }

    public String getIdtpinvito1() {
        return (String) getAttribute("Idtpinvito1");
    }

    public String getIndirizzoDom() {
        return (String) getAttribute("IndirizzoDom");
    }

    public String getIndirizzoRes() {
        return (String) getAttribute("IndirizzoRes");
    }

    public String getIndirizzoRes1() {
        return (String) getAttribute("IndirizzoRes1");
    }

    public String getIndirizzoScr() {
        return (String) getAttribute("IndirizzoScr");
    }

    public Integer getLivesito() {
        return (Integer) getAttribute("Livesito");
    }

    public Integer getLivesito1() {
        return (Integer) getAttribute("Livesito1");
    }

    public Integer getMinapp() {
        return (Integer) getAttribute("Minapp");
    }

    public String getNome() {
        return (String) getAttribute("Nome");
    }

    public Integer getOraapp() {
        return (Integer) getAttribute("Oraapp");
    }

    public String getTel() {
        return (String) getAttribute("Tel");
    }

    public String getTel1() {
        return (String) getAttribute("Tel1");
    }

    public String getTel2() {
        return (String) getAttribute("Tel2");
    }

    public String getTipoInvito() {
        return (String) getAttribute("TipoInvito");
    }

    public String getTpscr() {
        return (String) getAttribute("Tpscr");
    }

    public String getTpscr1() {
        return (String) getAttribute("Tpscr1");
    }

    public String getTpsrc() {
        return (String) getAttribute("Tpsrc");
    }

    public String getUlss() {
        return (String) getAttribute("Ulss");
    }

    public String getUlss1() {
        return (String) getAttribute("Ulss1");
    }

    public String getUlss2() {
        return (String) getAttribute("Ulss2");
    }

    public String getUlss3() {
        return (String) getAttribute("Ulss3");
    }

    public void setCentro(String value) {
        setAttribute("Centro", value);
    }

    public void setCf(String value) {
        setAttribute("Cf", value);
    }

    public void setCodcom(String value) {
        setAttribute("Codcom", value);
    }

    public void setCodcom1(String value) {
        setAttribute("Codcom1", value);
    }

    public void setCodcom2(String value) {
        setAttribute("Codcom2", value);
    }

    public void setCodcomscr(String value) {
        setAttribute("Codcomscr", value);
    }

    public void setCodesitoinvito(String value) {
        setAttribute("Codesitoinvito", value);
    }

    public void setCodesitoinvito1(String value) {
        setAttribute("Codesitoinvito1", value);
    }

    public void setCodpr(String value) {
        setAttribute("Codpr", value);
    }

    public void setCodpr1(String value) {
        setAttribute("Codpr1", value);
    }

    public void setCodpr2(String value) {
        setAttribute("Codpr2", value);
    }

    public void setCodts(String value) {
        setAttribute("Codts", value);
    }

    public void setCodts1(String value) {
        setAttribute("Codts1", value);
    }

    public void setCognome(String value) {
        setAttribute("Cognome", value);
    }

    public void setComune(String value) {
        setAttribute("Comune", value);
    }

    public void setDataNascita(Date value) {
        setAttribute("DataNascita", value);
    }

    public void setDescrizione(String value) {
        setAttribute("Descrizione", value);
    }

    public void setDescrizione1(String value) {
        setAttribute("Descrizione1", value);
    }

    public void setDispslot(Integer value) {
        setAttribute("Dispslot", value);
    }

    public void setDtapp(Date value) {
        setAttribute("Dtapp", value);
    }

    public void setEsitoinvito(String value) {
        setAttribute("Esitoinvito", value);
    }

    public void setIdacc1liv(Integer value) {
        setAttribute("Idacc1liv", value);
    }

    public void setIdaccco1liv(Integer value) {
        setAttribute("Idaccco1liv", value);
    }

    public void setIdaccma1liv(Integer value) {
        setAttribute("Idaccma1liv", value);
    }

    public void setIdapp(Integer value) {
        setAttribute("Idapp", value);
    }

    public void setIdapp1(Integer value) {
        setAttribute("Idapp1", value);
    }

    public void setIdcentro(Integer value) {
        setAttribute("Idcentro", value);
    }

    public void setIdcentro1(Integer value) {
        setAttribute("Idcentro1", value);
    }

    public void setIdinvito(Integer value) {
        setAttribute("Idinvito", value);
    }

    public void setIdinvito1(Integer value) {
        setAttribute("Idinvito1", value);
    }

    public void setIdtpinvito(String value) {
        setAttribute("Idtpinvito", value);
    }

    public void setIdtpinvito1(String value) {
        setAttribute("Idtpinvito1", value);
    }

    public void setIndirizzoDom(String value) {
        setAttribute("IndirizzoDom", value);
    }

    public void setIndirizzoRes(String value) {
        setAttribute("IndirizzoRes", value);
    }

    public void setIndirizzoRes1(String value) {
        setAttribute("IndirizzoRes1", value);
    }

    public void setIndirizzoScr(String value) {
        setAttribute("IndirizzoScr", value);
    }

    public void setLivesito(Integer value) {
        setAttribute("Livesito", value);
    }

    public void setLivesito1(Integer value) {
        setAttribute("Livesito1", value);
    }

    public void setMinapp(Integer value) {
        setAttribute("Minapp", value);
    }

    public void setNome(String value) {
        setAttribute("Nome", value);
    }

    public void setOraapp(Integer value) {
        setAttribute("Oraapp", value);
    }

    public void setTel(String value) {
        setAttribute("Tel", value);
    }

    public void setTel1(String value) {
        setAttribute("Tel1", value);
    }

    public void setTel2(String value) {
        setAttribute("Tel2", value);
    }

    public void setTipoInvito(String value) {
        setAttribute("TipoInvito", value);
    }

    public void setTpscr(String value) {
        setAttribute("Tpscr", value);
    }

    public void setTpscr1(String value) {
        setAttribute("Tpscr1", value);
    }

    public void setTpsrc(String value) {
        setAttribute("Tpsrc", value);
    }

    public void setUlss(String value) {
        setAttribute("Ulss", value);
    }

    public void setUlss1(String value) {
        setAttribute("Ulss1", value);
    }

    public void setUlss2(String value) {
        setAttribute("Ulss2", value);
    }

    public void setUlss3(String value) {
        setAttribute("Ulss3", value);
    }
}
