package model;

import model.accettazione.A_SoAccCito1livView1Impl;
import model.accettazione.A_SoAccCito2livViewImpl;
import model.accettazione.A_SoAccColon1livViewImpl;
import model.accettazione.A_SoAccColon2livViewImpl;
import model.accettazione.A_SoAccMammo1livViewImpl;
import model.accettazione.A_SoAccMammo2livViewImpl;
import model.accettazione.A_SoAccPfas1livViewImpl;

import model.common.A_AppModule;

import model.commons.Parent_AppModuleImpl;

import model.global.A_SoAllegatoViewImpl;
import model.global.A_SoAppuntamentoViewImpl;
import model.global.A_SoAziendaViewImpl;
import model.global.A_SoCentroPrelRefViewImpl;
import model.global.A_SoCnfComuniZoneParamViewImpl;
import model.global.A_SoCnfLetteracentroViewImpl;
import model.global.A_SoCnfParametriSistemaViewImpl;
import model.global.A_SoCnfPartemplateViewImpl;
import model.global.A_SoCnfTpinvitoViewImpl;
import model.global.A_SoCnfTpscrViewImpl;
import model.global.A_SoEsclusioneViewImpl;
import model.global.A_SoInvitoViewImpl;
import model.global.A_SoMedicoViewImpl;
import model.global.A_SoOldDocsViewImpl;
import model.global.A_SoRoundorgViewImpl;
import model.global.A_SoSoggScrViewImpl;
import model.global.A_SoSoggettoViewImpl;
import model.global.A_SoTemplateViewImpl;

import model.round.Round_SoCnfAnagScrViewImpl;
import model.round.Round_SoCnfTpscrViewImpl;
import model.round.Round_SoEsclusioneViewImpl;
import model.round.Round_SoSoggettiFilteredViewImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 02 15:21:26 CET 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class A_AppModuleImpl extends Parent_AppModuleImpl implements A_AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public A_AppModuleImpl() {
    }

    /**
     * Container's getter for A_SoAllegatoView1.
     * @return A_SoAllegatoView1
     */
    public A_SoAllegatoViewImpl getA_SoAllegatoView1() {
        return (A_SoAllegatoViewImpl)findViewObject("A_SoAllegatoView1");
    }

    /**
     * Container's getter for A_SoAppuntamentoView1.
     * @return A_SoAppuntamentoView1
     */
    public A_SoAppuntamentoViewImpl getA_SoAppuntamentoView1() {
        return (A_SoAppuntamentoViewImpl)findViewObject("A_SoAppuntamentoView1");
    }

    /**
     * Container's getter for A_SoAziendaView1.
     * @return A_SoAziendaView1
     */
    public A_SoAziendaViewImpl getA_SoAziendaView1() {
        return (A_SoAziendaViewImpl)findViewObject("A_SoAziendaView1");
    }

    /**
     * Container's getter for A_SoCentroPrelRefView1.
     * @return A_SoCentroPrelRefView1
     */
    public A_SoCentroPrelRefViewImpl getA_SoCentroPrelRefView1() {
        return (A_SoCentroPrelRefViewImpl)findViewObject("A_SoCentroPrelRefView1");
    }

    /**
     * Container's getter for A_SoCnfLetteracentroView1.
     * @return A_SoCnfLetteracentroView1
     */
    public A_SoCnfLetteracentroViewImpl getA_SoCnfLetteracentroView1() {
        return (A_SoCnfLetteracentroViewImpl)findViewObject("A_SoCnfLetteracentroView1");
    }

    /**
     * Container's getter for A_SoCnfTpscrView1.
     * @return A_SoCnfTpscrView1
     */
    public A_SoCnfTpscrViewImpl getA_SoCnfTpscrView1() {
        return (A_SoCnfTpscrViewImpl)findViewObject("A_SoCnfTpscrView1");
    }

    /**
     * Container's getter for A_SoInvitoView1.
     * @return A_SoInvitoView1
     */
    public A_SoInvitoViewImpl getA_SoInvitoView1() {
        return (A_SoInvitoViewImpl)findViewObject("A_SoInvitoView1");
    }

    /**
     * Container's getter for A_SoMedicoView1.
     * @return A_SoMedicoView1
     */
    public A_SoMedicoViewImpl getA_SoMedicoView1() {
        return (A_SoMedicoViewImpl)findViewObject("A_SoMedicoView1");
    }

    /**
     * Container's getter for A_SoRoundorgView1.
     * @return A_SoRoundorgView1
     */
    public A_SoRoundorgViewImpl getA_SoRoundorgView1() {
        return (A_SoRoundorgViewImpl)findViewObject("A_SoRoundorgView1");
    }

    /**
     * Container's getter for A_SoSoggScrView1.
     * @return A_SoSoggScrView1
     */
    public A_SoSoggScrViewImpl getA_SoSoggScrView1() {
        return (A_SoSoggScrViewImpl)findViewObject("A_SoSoggScrView1");
    }

    /**
     * Container's getter for A_SoTemplateView1.
     * @return A_SoTemplateView1
     */
    public A_SoTemplateViewImpl getA_SoTemplateView1() {
        return (A_SoTemplateViewImpl)findViewObject("A_SoTemplateView1");
    }

    /**
     * Container's getter for A_SoCnfPartemplateView1.
     * @return A_SoCnfPartemplateView1
     */
    public A_SoCnfPartemplateViewImpl getA_SoCnfPartemplateView1() {
        return (A_SoCnfPartemplateViewImpl)findViewObject("A_SoCnfPartemplateView1");
    }

    /**
     * Container's getter for A_SoSoggettoView1.
     * @return A_SoSoggettoView1
     */
    public A_SoSoggettoViewImpl getA_SoSoggettoView1() {
        return (A_SoSoggettoViewImpl)findViewObject("A_SoSoggettoView1");
    }

    /**
     * Container's getter for Round_SoSoggettiFilteredView1.
     * @return Round_SoSoggettiFilteredView1
     */
    public Round_SoSoggettiFilteredViewImpl getRound_SoSoggettiFilteredView1() {
        return (Round_SoSoggettiFilteredViewImpl)findViewObject("Round_SoSoggettiFilteredView1");
    }

    /**
     * Container's getter for A_SoCnfTpinvitoView1.
     * @return A_SoCnfTpinvitoView1
     */
    public A_SoCnfTpinvitoViewImpl getA_SoCnfTpinvitoView1() {
        return (A_SoCnfTpinvitoViewImpl)findViewObject("A_SoCnfTpinvitoView1");
    }

    /**
     * Container's getter for A_SoAccColon1livView1.
     * @return A_SoAccColon1livView1
     */
    public A_SoAccColon1livViewImpl getA_SoAccColon1livView1() {
        return (A_SoAccColon1livViewImpl)findViewObject("A_SoAccColon1livView1");
    }

    /**
     * Container's getter for A_SoCnfComuniZoneParamView1.
     * @return A_SoCnfComuniZoneParamView1
     */
    public A_SoCnfComuniZoneParamViewImpl getA_SoCnfComuniZoneParamView1() {
        return (A_SoCnfComuniZoneParamViewImpl)findViewObject("A_SoCnfComuniZoneParamView1");
    }

    /**
     * Container's getter for A_SoCnfParametriSistemaView1.
     * @return A_SoCnfParametriSistemaView1
     */
    public A_SoCnfParametriSistemaViewImpl getA_SoCnfParametriSistemaView1() {
        return (A_SoCnfParametriSistemaViewImpl)findViewObject("A_SoCnfParametriSistemaView1");
    }

    /**
     * Container's getter for A_SoAccMammo1livView1.
     * @return A_SoAccMammo1livView1
     */
    public A_SoAccMammo1livViewImpl getA_SoAccMammo1livView1() {
        return (A_SoAccMammo1livViewImpl)findViewObject("A_SoAccMammo1livView1");
    }

    /**
     * Container's getter for A_SoAccMammo2livView1.
     * @return A_SoAccMammo2livView1
     */
    public A_SoAccMammo2livViewImpl getA_SoAccMammo2livView1() {
        return (A_SoAccMammo2livViewImpl)findViewObject("A_SoAccMammo2livView1");
    }

    /**
     * Container's getter for A_SoAccCito1livView1_1.
     * @return A_SoAccCito1livView1_1
     */
    public A_SoAccCito1livView1Impl getA_SoAccCito1livView1_1() {
        return (A_SoAccCito1livView1Impl)findViewObject("A_SoAccCito1livView1_1");
    }

    /**
     * Container's getter for Round_SoEsclusioneView1.
     * @return Round_SoEsclusioneView1
     */
    public Round_SoEsclusioneViewImpl getRound_SoEsclusioneView1() {
        return (Round_SoEsclusioneViewImpl)findViewObject("Round_SoEsclusioneView1");
    }

    /**
     * Container's getter for Round_SoCnfAnagScrView1.
     * @return Round_SoCnfAnagScrView1
     */
    public Round_SoCnfAnagScrViewImpl getRound_SoCnfAnagScrView1() {
        return (Round_SoCnfAnagScrViewImpl)findViewObject("Round_SoCnfAnagScrView1");
    }

    /**
     * Container's getter for Round_SoCnfTpscrView1.
     * @return Round_SoCnfTpscrView1
     */
    public Round_SoCnfTpscrViewImpl getRound_SoCnfTpscrView1() {
        return (Round_SoCnfTpscrViewImpl)findViewObject("Round_SoCnfTpscrView1");
    }

    /**
     * Container's getter for A_SoOldDocsView1.
     * @return A_SoOldDocsView1
     */
    public A_SoOldDocsViewImpl getA_SoOldDocsView1() {
        return (A_SoOldDocsViewImpl)findViewObject("A_SoOldDocsView1");
    }

    /**
     * Container's getter for A_SoAllegatoView2.
     * @return A_SoAllegatoView2
     */
    public A_SoAllegatoViewImpl getA_SoAllegatoView2() {
        return (A_SoAllegatoViewImpl)findViewObject("A_SoAllegatoView2");
    }

    /**
     * Container's getter for A_SoEsclusioneView1.
     * @return A_SoEsclusioneView1
     */
    public A_SoEsclusioneViewImpl getA_SoEsclusioneView1() {
        return (A_SoEsclusioneViewImpl)findViewObject("A_SoEsclusioneView1");
    }

    /**
     * Container's getter for A_SoAccColon2livView1.
     * @return A_SoAccColon2livView1
     */
    public A_SoAccColon2livViewImpl getA_SoAccColon2livView1() {
        return (A_SoAccColon2livViewImpl) findViewObject("A_SoAccColon2livView1");
    }

    /**
     * Container's getter for A_SoAccCito2livView1.
     * @return A_SoAccCito2livView1
     */
    public A_SoAccCito2livViewImpl getA_SoAccCito2livView1() {
        return (A_SoAccCito2livViewImpl) findViewObject("A_SoAccCito2livView1");
    }

    /**
     * Container's getter for A_SoAccPfas1livView1.
     * @return A_SoAccPfas1livView1
     */
    public A_SoAccPfas1livViewImpl getA_SoAccPfas1livView1() {
        return (A_SoAccPfas1livViewImpl) findViewObject("A_SoAccPfas1livView1");
    }
}
