package model;


import model.accettazione.A_SoAccColon1livViewImpl;
import model.accettazione.A_SoAccMammo1livViewImpl;
import model.accettazione.A_SoAccMammo2livViewImpl;
import model.accettazione.AccMa_AnamnesiSoggViewImpl;
import model.accettazione.AccMa_CnfEsitoViewImpl;
import model.accettazione.AccMa_EsitoViewImpl;
import model.accettazione.AccMa_MotInterventoViewImpl;
import model.accettazione.AccMa_OpAnamViewImpl;
import model.accettazione.AccMa_RicInvitiViewImpl;
import model.accettazione.AccMa_SediInterventoViewImpl;
import model.accettazione.AccMa_SediSintViewImpl;
import model.accettazione.AccMa_SelCprelViewImpl;
import model.accettazione.AccMa_SinondViewImpl;
import model.accettazione.AccMa_SintomiViewImpl;
import model.accettazione.AccMa_SoAccMammo1livViewImpl;
import model.accettazione.AccMa_SoAccMammo2livViewImpl;
import model.accettazione.AccMa_SoAnamnesimxSintomiViewImpl;
import model.accettazione.AccMa_SoAnamnesimxViewImpl;
import model.accettazione.AccMa_SoAziendaViewImpl;
import model.accettazione.AccMa_SoCnfPartemplateViewImpl;
import model.accettazione.AccMa_SoInvitoViewImpl;
import model.accettazione.AccMa_TpInterventoViewImpl;

import model.commons.Parent_AppModuleImpl;

import model.conf.Cnf_SoCnfComuneViewImpl;
import model.conf.Cnf_SoCnfUtentiOperatoriViewImpl;

import model.global.A_SoAllegatoViewImpl;
import model.global.A_SoAppuntamentoViewImpl;
import model.global.A_SoAziendaViewImpl;
import model.global.A_SoCentroPrelRefViewImpl;
import model.global.A_SoCnfComuniZoneParamViewImpl;
import model.global.A_SoCnfLetteracentroViewImpl;
import model.global.A_SoCnfParametriSistemaViewImpl;
import model.global.A_SoCnfPartemplateViewImpl;
import model.global.A_SoCnfTpinvitoViewImpl;
import model.global.A_SoCnfTpscrViewImpl;
import model.global.A_SoComuneViewImpl;
import model.global.A_SoInvitoViewImpl;
import model.global.A_SoMedicoViewImpl;
import model.global.A_SoRoundorgViewImpl;
import model.global.A_SoSoggScrViewImpl;
import model.global.A_SoSoggettoViewImpl;
import model.global.A_SoTemplateViewImpl;

import model.impexp.Impexp_SoCnfImpexpViewImpl;

import oracle.jbo.server.ViewObjectImpl;

//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class AccMa_AppModuleImpl extends Parent_AppModuleImpl implements model.common.AccMa_AppModule 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public AccMa_AppModuleImpl()
  {
  }

  /**
   * 
   *  Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args)
  {
    launchTester("model", "AccMa_AppModuleLocal");
  }

  /**
     *
     *  Container's getter for AccMa_RicInvitiView1
     */
    public AccMa_RicInvitiViewImpl getAccMa_RicInvitiView1()
  {
    return (AccMa_RicInvitiViewImpl) findViewObject("AccMa_RicInvitiView1");
  }

  /**
     *
     *  Container's getter for AccMa_SelCprelView1
     */
    public AccMa_SelCprelViewImpl getAccMa_SelCprelView1()
  {
    return (AccMa_SelCprelViewImpl)findViewObject("AccMa_SelCprelView1");
  }

  /**
     *
     *  Container's getter for AccMa_SoInvitoView1
     */
    public AccMa_SoInvitoViewImpl getAccMa_SoInvitoView1()
  {
    return (AccMa_SoInvitoViewImpl) findViewObject("AccMa_SoInvitoView1");
  }

  /**
     *
     *  Container's getter for AccMa_SoAccMammo1livView1
     */
    public AccMa_SoAccMammo1livViewImpl getAccMa_SoAccMammo1livView1()
  {
    return (AccMa_SoAccMammo1livViewImpl)findViewObject("AccMa_SoAccMammo1livView1");
  }

  /**
     *
     *  Container's getter for AccMa_SoAccMammo2livView1
     */
    public AccMa_SoAccMammo2livViewImpl getAccMa_SoAccMammo2livView1()
  {
    return (AccMa_SoAccMammo2livViewImpl)findViewObject("AccMa_SoAccMammo2livView1");
  }

  /**
     *
     *  Container's getter for AccMa_EsitoView1
     */
    public AccMa_EsitoViewImpl getAccMa_EsitoView1()
  {
    return (AccMa_EsitoViewImpl)findViewObject("AccMa_EsitoView1");
  }

  /**
     *
     *  Container's getter for A_SoAllegatoView1
     */
    public A_SoAllegatoViewImpl getA_SoAllegatoView1()
  {
    return (A_SoAllegatoViewImpl)findViewObject("A_SoAllegatoView1");
  }

  /**
     *
     *  Container's getter for A_SoAppuntamentoView1
     */
    public A_SoAppuntamentoViewImpl getA_SoAppuntamentoView1()
  {
    return (A_SoAppuntamentoViewImpl)findViewObject("A_SoAppuntamentoView1");
  }

  /**
     *
     *  Container's getter for A_SoAziendaView1
     */
    public A_SoAziendaViewImpl getA_SoAziendaView1()
  {
    return (A_SoAziendaViewImpl)findViewObject("A_SoAziendaView1");
  }

  /**
     *
     *  Container's getter for A_SoCentroPrelRefView1
     */
    public A_SoCentroPrelRefViewImpl getA_SoCentroPrelRefView1()
  {
    return (A_SoCentroPrelRefViewImpl)findViewObject("A_SoCentroPrelRefView1");
  }

  /**
     *
     *  Container's getter for A_SoCnfLetteracentroView1
     */
    public A_SoCnfLetteracentroViewImpl getA_SoCnfLetteracentroView1()
  {
    return (A_SoCnfLetteracentroViewImpl)findViewObject("A_SoCnfLetteracentroView1");
  }

  /**
     *
     *  Container's getter for A_SoCnfTpscrView1
     */
    public A_SoCnfTpscrViewImpl getA_SoCnfTpscrView1()
  {
    return (A_SoCnfTpscrViewImpl)findViewObject("A_SoCnfTpscrView1");
  }

  /**
     *
     *  Container's getter for A_SoInvitoView1
     */
    public A_SoInvitoViewImpl getA_SoInvitoView1()
  {
    return (A_SoInvitoViewImpl)findViewObject("A_SoInvitoView1");
  }

  /**
     *
     *  Container's getter for A_SoMedicoView1
     */
    public A_SoMedicoViewImpl getA_SoMedicoView1()
  {
    return (A_SoMedicoViewImpl)findViewObject("A_SoMedicoView1");
  }

  /**
     *
     *  Container's getter for A_SoRoundorgView1
     */
    public A_SoRoundorgViewImpl getA_SoRoundorgView1()
  {
    return (A_SoRoundorgViewImpl)findViewObject("A_SoRoundorgView1");
  }

  /**
     *
     *  Container's getter for A_SoSoggScrView1
     */
    public A_SoSoggScrViewImpl getA_SoSoggScrView1()
  {
    return (A_SoSoggScrViewImpl)findViewObject("A_SoSoggScrView1");
  }

  /**
     *
     *  Container's getter for A_SoTemplateView1
     */
    public A_SoTemplateViewImpl getA_SoTemplateView1()
  {
    return (A_SoTemplateViewImpl)findViewObject("A_SoTemplateView1");
  }

  /**
     *
     *  Container's getter for A_SoCnfPartemplateView1
     */
    public A_SoCnfPartemplateViewImpl getA_SoCnfPartemplateView1()
  {
    return (A_SoCnfPartemplateViewImpl)findViewObject("A_SoCnfPartemplateView1");
  }

  /**
     *
     *  Container's getter for A_SoComuneView1
     */
    public A_SoComuneViewImpl getA_SoComuneView1()
  {
    return (A_SoComuneViewImpl)findViewObject("A_SoComuneView1");
  }

  /**
     *
     *  Container's getter for A_SoSoggettoView1
     */
    public A_SoSoggettoViewImpl getA_SoSoggettoView1()
  {
    return (A_SoSoggettoViewImpl)findViewObject("A_SoSoggettoView1");
  }

  /**
     *
     *  Container's getter for A_SoCnfTpinvitoView1
     */
    public A_SoCnfTpinvitoViewImpl getA_SoCnfTpinvitoView1()
  {
    return (A_SoCnfTpinvitoViewImpl)findViewObject("A_SoCnfTpinvitoView1");
  }



  /**
     *
     *  Container's getter for A_SoAccColon1livView1
     */
    public A_SoAccColon1livViewImpl getA_SoAccColon1livView1()
  {
    return (A_SoAccColon1livViewImpl)findViewObject("A_SoAccColon1livView1");
  }

  /**
     *
     *  Container's getter for A_SoCnfComuniZoneParamView1
     */
    public A_SoCnfComuniZoneParamViewImpl getA_SoCnfComuniZoneParamView1()
  {
    return (A_SoCnfComuniZoneParamViewImpl)findViewObject("A_SoCnfComuniZoneParamView1");
  }

  /**
     *
     *  Container's getter for AccMa_CnfEsitoView1
     */
    public AccMa_CnfEsitoViewImpl getAccMa_CnfEsitoView1()
  {
    return (AccMa_CnfEsitoViewImpl)findViewObject("AccMa_CnfEsitoView1");
  }

  /**
     *
     *  Container's getter for AccMa_SoAnamnesimxView1
     */
    public AccMa_SoAnamnesimxViewImpl getAccMa_SoAnamnesimxView1()
  {
    return (AccMa_SoAnamnesimxViewImpl) findViewObject("AccMa_SoAnamnesimxView1");
  }

  /**
     *
     *  Container's getter for AccMa_OpAnamView1
     */
    public AccMa_OpAnamViewImpl getAccMa_OpAnamView1()
  {
    return (AccMa_OpAnamViewImpl)findViewObject("AccMa_OpAnamView1");
  }

  /**
     *
     *  Container's getter for AccMa_SinondViewTer
     */
    public AccMa_SinondViewImpl getAccMa_SinondViewTer()
  {
    return (AccMa_SinondViewImpl)findViewObject("AccMa_SinondViewTer");
  }

  /**
     *
     *  Container's getter for AccMa_SinondViewInt
     */
    public AccMa_SinondViewImpl getAccMa_SinondViewInt()
  {
    return (AccMa_SinondViewImpl)findViewObject("AccMa_SinondViewInt");
  }

  /**
     *
     *  Container's getter for AccMa_TpInterventoView1
     */
    public AccMa_TpInterventoViewImpl getAccMa_TpInterventoView1()
  {
    return (AccMa_TpInterventoViewImpl)findViewObject("AccMa_TpInterventoView1");
  }

  /**
     *
     *  Container's getter for AccMa_SediInterventoView1
     */
    public AccMa_SediInterventoViewImpl getAccMa_SediInterventoView1()
  {
    return (AccMa_SediInterventoViewImpl)findViewObject("AccMa_SediInterventoView1");
  }

  /**
     *
     *  Container's getter for AccMa_MotInterventoView1
     */
    public AccMa_MotInterventoViewImpl getAccMa_MotInterventoView1()
  {
    return (AccMa_MotInterventoViewImpl)findViewObject("AccMa_MotInterventoView1");
  }

  /**
     *
     *  Container's getter for AccMa_AnamnesiSoggView1
     */
    public AccMa_AnamnesiSoggViewImpl getAccMa_AnamnesiSoggView1()
  {
    return (AccMa_AnamnesiSoggViewImpl)findViewObject("AccMa_AnamnesiSoggView1");
  }

  /**
     *
     *  Container's getter for AccMa_SinondViewFam
     */
    public AccMa_SinondViewImpl getAccMa_SinondViewFam()
  {
    return (AccMa_SinondViewImpl)findViewObject("AccMa_SinondViewFam");
  }

  /**
     *
     *  Container's getter for AccMa_SoAnamnesimxSintomiView1
     */
    public AccMa_SoAnamnesimxSintomiViewImpl getAccMa_SoAnamnesimxSintomiView1()
  {
    return (AccMa_SoAnamnesimxSintomiViewImpl)findViewObject("AccMa_SoAnamnesimxSintomiView1");
  }

  /**
     *
     *  Container's getter for AccMa_SintomiView1
     */
    public AccMa_SintomiViewImpl getAccMa_SintomiView1()
  {
    return (AccMa_SintomiViewImpl)findViewObject("AccMa_SintomiView1");
  }

  /**
     *
     *  Container's getter for AccMa_SediSintViewDX
     */
    public AccMa_SediSintViewImpl getAccMa_SediSintViewDX()
  {
    return (AccMa_SediSintViewImpl)findViewObject("AccMa_SediSintViewDX");
  }

  /**
     *
     *  Container's getter for AccMa_SediSintViewSX
     */
    public AccMa_SediSintViewImpl getAccMa_SediSintViewSX()
  {
    return (AccMa_SediSintViewImpl)findViewObject("AccMa_SediSintViewSX");
  }

  /**
     *
     *  Container's getter for A_SoAccMammo1livView1
     */
    public A_SoAccMammo1livViewImpl getA_SoAccMammo1livView1()
  {
    return (A_SoAccMammo1livViewImpl)findViewObject("A_SoAccMammo1livView1");
  }

  /**
     *
     *  Container's getter for A_SoAccMammo2livView1
     */
    public A_SoAccMammo2livViewImpl getA_SoAccMammo2livView1()
  {
    return (A_SoAccMammo2livViewImpl)findViewObject("A_SoAccMammo2livView1");
  }

  /**
     *
     *  Container's getter for AccMa_SoAziendaView1
     */
    public AccMa_SoAziendaViewImpl getAccMa_SoAziendaView1()
  {
    return (AccMa_SoAziendaViewImpl)findViewObject("AccMa_SoAziendaView1");
  }

  /**
     *
     *  Container's getter for AccMa_SoCnfPartemplateView1
     */
    public AccMa_SoCnfPartemplateViewImpl getAccMa_SoCnfPartemplateView1()
  {
    return (AccMa_SoCnfPartemplateViewImpl)findViewObject("AccMa_SoCnfPartemplateView1");
  }

  /**
     *
     *  Container's getter for Cnf_SoCnfComuneView1
     */
    public Cnf_SoCnfComuneViewImpl getCnf_SoCnfComuneView1()
  {
    return (Cnf_SoCnfComuneViewImpl)findViewObject("Cnf_SoCnfComuneView1");
  }

  /**
     *
     *  Container's getter for Impexp_SoCnfImpexpView1
     */
    public Impexp_SoCnfImpexpViewImpl getImpexp_SoCnfImpexpView1()
  {
    return (Impexp_SoCnfImpexpViewImpl)findViewObject("Impexp_SoCnfImpexpView1");
  }

  /**
     *
     *  Container's getter for A_SoCnfParametriSistemaView1
     */
    public A_SoCnfParametriSistemaViewImpl getA_SoCnfParametriSistemaView1()
  {
    return (A_SoCnfParametriSistemaViewImpl)findViewObject("A_SoCnfParametriSistemaView1");
  }

    /**
     * Container's getter for Cnf_SoCnfUtentiOperatoriView1.
     * @return Cnf_SoCnfUtentiOperatoriView1
     */
    public Cnf_SoCnfUtentiOperatoriViewImpl getCnf_SoCnfUtentiOperatoriView1() {
        return (Cnf_SoCnfUtentiOperatoriViewImpl) findViewObject("Cnf_SoCnfUtentiOperatoriView1");
    }
}
