package model;


import java.util.List;
import java.util.Map;

import model.accettazione.A_SoAccCito1livView1Impl;
import model.accettazione.A_SoAccColon1livViewImpl;
import model.accettazione.A_SoAccPfas1livViewImpl;

import model.common.Print_AppModule;

import model.commons.AccessManager;
import model.commons.Parent_AppModuleImpl;

import model.conf.Cnf_SoInsertoViewImpl;

import model.global.A_SoAppuntamentoViewImpl;
import model.global.A_SoAziendaViewImpl;
import model.global.A_SoCnfComuniZoneParamViewImpl;
import model.global.A_SoCnfLetteracentroViewImpl;
import model.global.A_SoCnfParametriSistemaViewImpl;
import model.global.A_SoCnfPartemplateViewImpl;
import model.global.A_SoCnfSiNoNdViewImpl;
import model.global.A_SoInvitoViewImpl;
import model.global.A_SoOldDocsViewImpl;
import model.global.A_SoSoggettoViewImpl;
import model.global.A_SoTemplateViewImpl;

import model.print.Print_DatiQuestCAViewImpl;
import model.print.Print_DatiQuestPFViewImpl;
import model.print.Print_EsamiPfasViewImpl;
import model.print.Print_SoAllegatoInvitiViewImpl;
import model.print.Print_SoAllegatoRefCAViewImpl;
import model.print.Print_SoAllegatoRefCOViewImpl;
import model.print.Print_SoAllegatoRefMAViewImpl;
import model.print.Print_SoAllegatoRefPFViewImpl;
import model.print.Print_SoAllegatoRefViewImpl;
import model.print.Print_SoAllegatoViewImpl;
import model.print.Print_SoCentroPrelRefViewImpl;
import model.print.Print_SoCnfSugg1livViewImpl;
import model.print.Print_SoCnfSugg2livViewImpl;
import model.print.Print_SoCnfSugg3livViewImpl;
import model.print.Print_SoCnfTpinvitoViewImpl;
import model.print.Print_SoElencoSoggettiViewImpl;
import model.print.Print_SoInterventocitoViewImpl;
import model.print.Print_SoPosteltxtViewImpl;
import model.print.Print_SoRefertocardioViewImpl;
import model.print.Print_SoRefertocito1livViewImpl;
import model.print.Print_SoRefertocito2livViewImpl;
import model.print.Print_SoRefertocolon1livViewImpl;
import model.print.Print_SoRefertocolon2livViewImpl;
import model.print.Print_SoRefertomammo1livViewImpl;
import model.print.Print_SoRefertomammo2livViewImpl;
import model.print.Print_SoRefertopfasViewImpl;
import model.print.Print_SoSuggerimentiViewImpl;
import model.print.Print_SoTemplateElenchiSoggViewImpl;
import model.print.Print_SoTemplateEtichetteViewImpl;

import model.trial.A_SelTrialBraccioViewImpl;
import model.trial.A_SelTrialStatoViewImpl;

import oracle.adf.share.ADFContext;

import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class Print_AppModuleImpl extends Parent_AppModuleImpl implements Print_AppModule {
      /**
       * 
       *  This is the default constructor (do not remove)
       */
      public Print_AppModuleImpl()
      {
      }

      /**
       * 
       *  Container's getter for Print_SoAllegatoView1
       */
      public Print_SoAllegatoViewImpl getPrint_SoAllegatoView1()
      {
        return (Print_SoAllegatoViewImpl)findViewObject("Print_SoAllegatoView1");
      }

      /**
       * 
       *  Sample main for debugging Business Components code using the tester.
       */
      public static void main(String[] args)
      {
        launchTester("model", "Print_AppModuleLocal");
      }
      
      
            /**
             * Metodo che si occupa di filtrare tutti i viewObject di configurazione in base
             * al tipo di screening e di ulss
             */
            public void filterConfiguration(String ulss, String scr, String codregionale, 
                    boolean regionale, String centri_in, Integer centro_fisico, Integer idTrial)
            {
                    String where = "TPSCR='" + scr + "'";
                    
                    String where2 = null;
                    if (!regionale) {
                            where2 = "ULSS='" + ulss + "'";
                    }
                    
                    //inviti da stampare: azzero il contenuto
                    ViewObject vo = this.getPrint_SoAllegatoInvitiView1();
                    vo.setWhereClause("1=2");
                    vo.executeQuery();
                    
                    vo = this.getPrint_SoAllegatoRefCOView1();
                    vo.setWhereClause("1=2");
                    vo.executeQuery();
                    
                    vo = this.getPrint_SoAllegatoRefMAView1();
                    vo.setWhereClause("1=2");
                    vo.executeQuery();
                    
                    vo = this.getPrint_SoAllegatoRefView1();
                    vo.setWhereClause("1=2");
                    vo.executeQuery();
                    
        vo = this.getPrint_SoAllegatoRefPFView1();
        vo.setWhereClause("1=2");
                    vo.executeQuery();
                    
                    //tipi di invito che visualizzo (dipendono dalla ulss e dal tipo di screening)
                    vo = this.getPrint_SoCnfTpinvitoView1();
                    String entity = vo.getDefName().substring(0, vo.getDefName().indexOf("View"));
                    String ad_hoc = entity + "." + where;
                    if (where2 != null)
                            ad_hoc+=" AND "+entity+"."+where2;
                    vo.setWhereClause(ad_hoc);
                    vo.executeQuery();
                    
                    //centri di prelievo: solo quelli della ulss e del tipo di screening
                    vo = this.getPrint_SoCentroPrelRefView1();
                    entity = vo.getDefName().substring(0, vo.getDefName().indexOf("View"));
                    ad_hoc = entity + "." + where;
                    if (where2 != null)
                            ad_hoc += " AND " + entity + "." + where2;

                    //se l'utente è legato ad un centro fisico, si filtra ulteriormente
                    if (centri_in != null)
                            ad_hoc += " AND (" + entity + ".IDCENTRO IN " + centri_in + ")"; // OR "+entity+".TIPOCENTRO=3)";
                    
                    //controllo se l'utente ha delle limitazioni sui centri
                    try{
                        AccessManager.checkPermission("SOLimiteCentri");
                        ADFContext adfCtx = ADFContext.getCurrent();
                        Map sessionMap = adfCtx.getSessionScope();
                        List<Integer> centriAutorizzati = (List<Integer>) sessionMap.get("centriautorizzati");
                        String centri = "";
                        if (centriAutorizzati != null && !centriAutorizzati.isEmpty()){
                            for (int i = 0; i < centriAutorizzati.size(); i++) {
                                centri += "" + centriAutorizzati.get(i) + ",";
                            }
                            centri = centri.substring(0, centri.length() - 1);                           
                            ad_hoc += " AND (" + entity + ".IDCENTRO IN (" + centri + "))";
                        } else {
                            ad_hoc += " AND 1=2 ";
                        }           
                    } catch (IllegalAccessException e){                                      
                       // non faccio niente
                    }

                    vo.setWhereClause(ad_hoc + " AND TIPOCENTRO<>3");
                    vo.executeQuery();
                    
                    //centri di refertazione
                    vo = this.getPrint_SoCentroPrelRefView2();
                    entity = vo.getDefName().substring(0, vo.getDefName().indexOf("View"));
                    ad_hoc = entity + "." + where;
                    if (where2 != null)
                            ad_hoc += " AND " + entity + "." + where2;

                    vo.setWhereClause(ad_hoc + " AND TIPOCENTRO=3");
                    vo.executeQuery();
                    
                    //ETICHETTE: le filtro entrando nella stampa
                    /*   vo=this.getPrint_SoTemplateEtichetteView1();
                    entity="Print_SoTemplate";
                    ad_hoc=entity+"."+where;
                    if(where2!=null)
                    ad_hoc+=" AND ("+entity+"."+where2+" OR "+entity+".ULSS='"+codregionale+"')";
                    vo.setWhereClause(ad_hoc);
                    vo.executeQuery();*/
                    
                    //suggerimenti, tutti e tre i tipi
                    vo=this.getPrint_SoSuggerimentiView1();
                    ad_hoc = where;
                    if (where2 != null)
                            ad_hoc += " AND " + where2;
                    vo.setWhereClause(ad_hoc);
                    vo.executeQuery();
        
                    // Trial
                    Object[] trialParams = new Object[]{idTrial, scr};
                    vo = getA_SelTrialStatoView1();
                    vo.setWhereClauseParams(trialParams);
                    vo = getA_SelTrialBraccioView1();
                    vo.setWhereClauseParams(trialParams);
            }

      /**
     *
     *  Container's getter for Print_SoAllegatoInvitiView1
     */
    public Print_SoAllegatoInvitiViewImpl getPrint_SoAllegatoInvitiView1()
      {
        return (Print_SoAllegatoInvitiViewImpl) findViewObject("Print_SoAllegatoInvitiView1");
      }

      /**
       * 
       *  Container's getter for Print_SoCnfTpinvitoView1
       */
      public Print_SoCnfTpinvitoViewImpl getPrint_SoCnfTpinvitoView1()
      {
        return (Print_SoCnfTpinvitoViewImpl)findViewObject("Print_SoCnfTpinvitoView1");
      }

      /**
       * 
       *  Container's getter for Print_SoCentroPrelRefView1
       */
      public Print_SoCentroPrelRefViewImpl getPrint_SoCentroPrelRefView1()
      {
        return (Print_SoCentroPrelRefViewImpl)findViewObject("Print_SoCentroPrelRefView1");
      }

      /**
       * 
       *  Container's getter for Print_SoTemplateEtichetteView1
       */
      public Print_SoTemplateEtichetteViewImpl getPrint_SoTemplateEtichetteView1()
      {
        return (Print_SoTemplateEtichetteViewImpl)findViewObject("Print_SoTemplateEtichetteView1");
      }

      /**
       * 
       *  Container's getter for Print_SoCnfSugg1livView1
       */
      public Print_SoCnfSugg1livViewImpl getPrint_SoCnfSugg1livView1()
      {
        return (Print_SoCnfSugg1livViewImpl)findViewObject("Print_SoCnfSugg1livView1");
      }

      /**
       * 
       *  Container's getter for Print_SoCnfSugg2livView1
       */
      public Print_SoCnfSugg2livViewImpl getPrint_SoCnfSugg2livView1()
      {
        return (Print_SoCnfSugg2livViewImpl)findViewObject("Print_SoCnfSugg2livView1");
      }

      /**
       * 
       *  Container's getter for Print_SoCnfSugg3livView1
       */
      public Print_SoCnfSugg3livViewImpl getPrint_SoCnfSugg3livView1()
      {
        return (Print_SoCnfSugg3livViewImpl)findViewObject("Print_SoCnfSugg3livView1");
      }

      /**
       * 
       *  Container's getter for Print_SoInterventocitoView1
       */
      public Print_SoInterventocitoViewImpl getPrint_SoInterventocitoView1()
      {
        return (Print_SoInterventocitoViewImpl)findViewObject("Print_SoInterventocitoView1");
      }

      /**
       * 
       *  Container's getter for Print_SoRefertocito1livView1
       */
      public Print_SoRefertocito1livViewImpl getPrint_SoRefertocito1livView1()
      {
        return (Print_SoRefertocito1livViewImpl)findViewObject("Print_SoRefertocito1livView1");
      }

      /**
       * 
       *  Container's getter for Print_SoRefertocito2livView1
       */
      public Print_SoRefertocito2livViewImpl getPrint_SoRefertocito2livView1()
      {
        return (Print_SoRefertocito2livViewImpl)findViewObject("Print_SoRefertocito2livView1");
      }

      /**
       * 
       *  Container's getter for Print_SoAllegatoRefView1
       */
      public Print_SoAllegatoRefViewImpl getPrint_SoAllegatoRefView1()
      {
        return (Print_SoAllegatoRefViewImpl)findViewObject("Print_SoAllegatoRefView1");
      }

      /**
       * 
       *  Container's getter for Print_SoAllegatoView2
       */
      public Print_SoAllegatoViewImpl getPrint_SoAllegatoView2()
      {
        return (Print_SoAllegatoViewImpl)findViewObject("Print_SoAllegatoView2");
      }

      /**
       * 
       *  Container's getter for Print_FKAllegatoRefAllegatoLink1
       */
      public ViewLinkImpl getPrint_FKAllegatoRefAllegatoLink1()
      {
        return (ViewLinkImpl)findViewLink("Print_FKAllegatoRefAllegatoLink1");
      }

      /**
       * 
       *  Container's getter for Print_SoSuggerimentiView1
       */
      public Print_SoSuggerimentiViewImpl getPrint_SoSuggerimentiView1()
      {
        return (Print_SoSuggerimentiViewImpl)findViewObject("Print_SoSuggerimentiView1");
      }

      /**
       * 
       *  Container's getter for Print_SoRefertocito1livView2
       */
      public Print_SoRefertocito1livViewImpl getPrint_SoRefertocito1livView2()
      {
        return (Print_SoRefertocito1livViewImpl)findViewObject("Print_SoRefertocito1livView2");
      }

      /**
       * 
       *  Container's getter for Print_SoRefertocito2livView2
       */
      public Print_SoRefertocito2livViewImpl getPrint_SoRefertocito2livView2()
      {
        return (Print_SoRefertocito2livViewImpl)findViewObject("Print_SoRefertocito2livView2");
      }

      /**
       * 
       *  Container's getter for Print_FKAllegatoRefRef1livLink1
       */
      public ViewLinkImpl getPrint_FKAllegatoRefRef1livLink1()
      {
        return (ViewLinkImpl)findViewLink("Print_FKAllegatoRefRef1livLink1");
      }

      /**
       * 
       *  Container's getter for Print_FKAllegatoRefRef2livLink1
       */
      public ViewLinkImpl getPrint_FKAllegatoRefRef2livLink1()
      {
        return (ViewLinkImpl)findViewLink("Print_FKAllegatoRefRef2livLink1");
      }

      /**
       * 
       *  Container's getter for A_SoAziendaView1
       */
      public A_SoAziendaViewImpl getA_SoAziendaView1()
      {
        return (A_SoAziendaViewImpl)findViewObject("A_SoAziendaView1");
      }

      /**
       * 
       *  Container's getter for A_SoCnfPartemplateView1
       */
      public A_SoCnfPartemplateViewImpl getA_SoCnfPartemplateView1()
      {
        return (A_SoCnfPartemplateViewImpl)findViewObject("A_SoCnfPartemplateView1");
      }

      /**
       * 
       *  Container's getter for Print_SoCentroPrelRefView2
       */
      public Print_SoCentroPrelRefViewImpl getPrint_SoCentroPrelRefView2()
      {
        return (Print_SoCentroPrelRefViewImpl)findViewObject("Print_SoCentroPrelRefView2");
      }


      /**
       * 
       *  Container's getter for Print_SoTemplateElenchiSoggView1
       */
      public Print_SoTemplateElenchiSoggViewImpl getPrint_SoTemplateElenchiSoggView1()
      {
        return (Print_SoTemplateElenchiSoggViewImpl)findViewObject("Print_SoTemplateElenchiSoggView1");
      }

      /**
       * 
       *  Container's getter for Print_SoElencoSoggettiView1
       */
      public Print_SoElencoSoggettiViewImpl getPrint_SoElencoSoggettiView1()
      {
        return (Print_SoElencoSoggettiViewImpl)findViewObject("Print_SoElencoSoggettiView1");
      }

      /**
       * 
       *  Container's getter for Print_SoAllegatoRefCOView1
       */
      public Print_SoAllegatoRefCOViewImpl getPrint_SoAllegatoRefCOView1()
      {
        return (Print_SoAllegatoRefCOViewImpl)findViewObject("Print_SoAllegatoRefCOView1");
      }

      /**
       * 
       *  Container's getter for Print_SoRefertocolon1livView1
       */
      public Print_SoRefertocolon1livViewImpl getPrint_SoRefertocolon1livView1()
      {
        return (Print_SoRefertocolon1livViewImpl)findViewObject("Print_SoRefertocolon1livView1");
      }

      /**
       * 
       *  Container's getter for Print_SoRefertocolon2livView1
       */
      public Print_SoRefertocolon2livViewImpl getPrint_SoRefertocolon2livView1()
      {
        return (Print_SoRefertocolon2livViewImpl)findViewObject("Print_SoRefertocolon2livView1");
      }

      /**
       * 
       *  Container's getter for Print_SoAllegatoView3
       */
      public Print_SoAllegatoViewImpl getPrint_SoAllegatoView3()
      {
        return (Print_SoAllegatoViewImpl)findViewObject("Print_SoAllegatoView3");
      }



      /**
       * 
       *  Container's getter for FKAllegatoRefCo_AllegatoLink1
       */
      public ViewLinkImpl getFKAllegatoRefCo_AllegatoLink1()
      {
        return (ViewLinkImpl)findViewLink("FKAllegatoRefCo_AllegatoLink1");
      }

      /**
       * 
       *  Container's getter for Print_SoRefertocolon1livView2
       */
      public Print_SoRefertocolon1livViewImpl getPrint_SoRefertocolon1livView2()
      {
        return (Print_SoRefertocolon1livViewImpl)findViewObject("Print_SoRefertocolon1livView2");
      }

      /**
       * 
       *  Container's getter for Print_SoRefertocolon2livView2
       */
      public Print_SoRefertocolon2livViewImpl getPrint_SoRefertocolon2livView2()
      {
        return (Print_SoRefertocolon2livViewImpl)findViewObject("Print_SoRefertocolon2livView2");
      }

      /**
       * 
       *  Container's getter for Print_SoAllegatiRefCo_Ref1liv1
       */
      public ViewLinkImpl getPrint_SoAllegatiRefCo_Ref1liv1()
      {
        return (ViewLinkImpl)findViewLink("Print_SoAllegatiRefCo_Ref1liv1");
      }

      /**
       * 
       *  Container's getter for Print_SoAllegatiRefCo_Ref2liv1
       */
      public ViewLinkImpl getPrint_SoAllegatiRefCo_Ref2liv1()
      {
        return (ViewLinkImpl)findViewLink("Print_SoAllegatiRefCo_Ref2liv1");
      }

      /**
       * 
       *  Container's getter for A_SoAccColon1livView1
       */
      public A_SoAccColon1livViewImpl getA_SoAccColon1livView1()
      {
        return (A_SoAccColon1livViewImpl)findViewObject("A_SoAccColon1livView1");
      }

      /**
       * 
       *  Container's getter for Print_SoAllegatoRefMAView1
       */
      public Print_SoAllegatoRefMAViewImpl getPrint_SoAllegatoRefMAView1()
      {
        return (Print_SoAllegatoRefMAViewImpl)findViewObject("Print_SoAllegatoRefMAView1");
      }

      /**
       * 
       *  Container's getter for Print_SoRefertomammo1livView1
       */
      public Print_SoRefertomammo1livViewImpl getPrint_SoRefertomammo1livView1()
      {
        return (Print_SoRefertomammo1livViewImpl)findViewObject("Print_SoRefertomammo1livView1");
      }

      /**
       * 
       *  Container's getter for Print_SoRefertomammo2livView1
       */
      public Print_SoRefertomammo2livViewImpl getPrint_SoRefertomammo2livView1()
      {
        return (Print_SoRefertomammo2livViewImpl)findViewObject("Print_SoRefertomammo2livView1");
      }

      /**
       * 
       *  Container's getter for Print_SoRefertomammo1livView2
       */
      public Print_SoRefertomammo1livViewImpl getPrint_SoRefertomammo1livView2()
      {
        return (Print_SoRefertomammo1livViewImpl)findViewObject("Print_SoRefertomammo1livView2");
      }

      /**
       * 
       *  Container's getter for Print_SoRefertomammo2livView2
       */
      public Print_SoRefertomammo2livViewImpl getPrint_SoRefertomammo2livView2()
      {
        return (Print_SoRefertomammo2livViewImpl)findViewObject("Print_SoRefertomammo2livView2");
      }

      /**
       * 
       *  Container's getter for Print_SoAllegatiRef1livMALink1
       */
      public ViewLinkImpl getPrint_SoAllegatiRef1livMALink1()
      {
        return (ViewLinkImpl)findViewLink("Print_SoAllegatiRef1livMALink1");
      }

      /**
       * 
       *  Container's getter for Print_SoAllegatiRef2livMALink1
       */
      public ViewLinkImpl getPrint_SoAllegatiRef2livMALink1()
      {
        return (ViewLinkImpl)findViewLink("Print_SoAllegatiRef2livMALink1");
      }

      /**
       * 
       *  Container's getter for Print_SoAllegatoView4
       */
      public Print_SoAllegatoViewImpl getPrint_SoAllegatoView4()
      {
        return (Print_SoAllegatoViewImpl)findViewObject("Print_SoAllegatoView4");
      }

      /**
       * 
       *  Container's getter for Print_SoAllegatiMA_AllegatoLink1
       */
      public ViewLinkImpl getPrint_SoAllegatiMA_AllegatoLink1()
      {
        return (ViewLinkImpl)findViewLink("Print_SoAllegatiMA_AllegatoLink1");
      }

      /**
       * 
       *  Container's getter for A_SoCnfParametriSistemaView1
       */
      public A_SoCnfParametriSistemaViewImpl getA_SoCnfParametriSistemaView1()
      {
        return (A_SoCnfParametriSistemaViewImpl)findViewObject("A_SoCnfParametriSistemaView1");
      }

      /**
       * 
       *  Container's getter for Cnf_SoInsertoView1
       */
      public Cnf_SoInsertoViewImpl getCnf_SoInsertoView1()
      {
        return (Cnf_SoInsertoViewImpl)findViewObject("Cnf_SoInsertoView1");
      }

      /**
       * 
       *  Container's getter for Print_SoPosteltxtView1
       */
      public Print_SoPosteltxtViewImpl getPrint_SoPosteltxtView1()
      {
        return (Print_SoPosteltxtViewImpl)findViewObject("Print_SoPosteltxtView1");
      }

      /**
       * 
       *  Container's getter for A_SoOldDocsView1
       */
      public A_SoOldDocsViewImpl getA_SoOldDocsView1()
      {
        return (A_SoOldDocsViewImpl)findViewObject("A_SoOldDocsView1");
      }

      /**
       * 
       *  Container's getter for A_SoSoggettoView1
       */
      public A_SoSoggettoViewImpl getA_SoSoggettoView1()
      {
        return (A_SoSoggettoViewImpl)findViewObject("A_SoSoggettoView1");
      }

      /**
       * 
       *  Container's getter for A_SoInvitoView1
       */
      public A_SoInvitoViewImpl getA_SoInvitoView1()
      {
        return (A_SoInvitoViewImpl)findViewObject("A_SoInvitoView1");
      }

      /**
       * 
       *  Container's getter for A_SoAppuntamentoView1
       */
      public A_SoAppuntamentoViewImpl getA_SoAppuntamentoView1()
      {
        return (A_SoAppuntamentoViewImpl)findViewObject("A_SoAppuntamentoView1");
      }

      /**
       * 
       *  Container's getter for A_SoAccCito1livView1_1
       */
      public A_SoAccCito1livView1Impl getA_SoAccCito1livView1_1()
      {
        return (A_SoAccCito1livView1Impl)findViewObject("A_SoAccCito1livView1_1");
      }

      /**
       * 
       *  Container's getter for A_SoCnfLetteracentroView1
       */
      public A_SoCnfLetteracentroViewImpl getA_SoCnfLetteracentroView1()
      {
        return (A_SoCnfLetteracentroViewImpl)findViewObject("A_SoCnfLetteracentroView1");
      }

      /**
       * 
       *  Container's getter for A_SoTemplateView1
       */
      public A_SoTemplateViewImpl getA_SoTemplateView1()
      {
        return (A_SoTemplateViewImpl)findViewObject("A_SoTemplateView1");
      }

      /**
       * 
       *  Container's getter for A_SoCnfComuniZoneParamView1
       */
      public A_SoCnfComuniZoneParamViewImpl getA_SoCnfComuniZoneParamView1()
      {
        return (A_SoCnfComuniZoneParamViewImpl)findViewObject("A_SoCnfComuniZoneParamView1");
      }

            /**
             * 
             *  Container's getter for A_SelTrialStatoView1
             */
            public A_SelTrialStatoViewImpl getA_SelTrialStatoView1() {
                    return (A_SelTrialStatoViewImpl)findViewObject("A_SelTrialStatoView1");
            }

            /**
             * 
             *  Container's getter for A_SelTrialBraccioView1
             */
            public A_SelTrialBraccioViewImpl getA_SelTrialBraccioView1() {
                    return (A_SelTrialBraccioViewImpl)findViewObject("A_SelTrialBraccioView1");
            }

            /**
             * 
             *  Container's getter for Print_SoAllegatoRefCAView1
             */
            public Print_SoAllegatoRefCAViewImpl getPrint_SoAllegatoRefCAView1() {
                    return (Print_SoAllegatoRefCAViewImpl)findViewObject("Print_SoAllegatoRefCAView1");
            }


            /**
             * 
             *  Container's getter for Print_SoAllegatiRefCa_Ref1
             */
            public ViewLinkImpl getPrint_SoAllegatiRefCa_Ref1() {
        return (ViewLinkImpl)findViewLink("Print_SoAllegatiRefCa_Ref1");
            }

            /**
             * 
             *  Container's getter for Print_SoRefertocardioView2
             */
            public Print_SoRefertocardioViewImpl getPrint_SoRefertocardioView2() {
                    return (Print_SoRefertocardioViewImpl)findViewObject("Print_SoRefertocardioView2");
            }
            

    /**
     *
     *  Container's getter for Print_DatiQuestCAView1
     */
            public Print_DatiQuestCAViewImpl getPrint_DatiQuestCAView1() {
                    return (Print_DatiQuestCAViewImpl)findViewObject("Print_DatiQuestCAView1");
            }

            /**
             * 
             *  Container's getter for A_SoCnfSiNoNdView1
             */
            public A_SoCnfSiNoNdViewImpl getA_SoCnfSiNoNdView1() {
                    return (A_SoCnfSiNoNdViewImpl)findViewObject("A_SoCnfSiNoNdView1");
            }

      /**
       * 
       *  Container's getter for Print_SoAllegatoRefPFView1
       */
      public Print_SoAllegatoRefPFViewImpl getPrint_SoAllegatoRefPFView1()
      {
        return (Print_SoAllegatoRefPFViewImpl)findViewObject("Print_SoAllegatoRefPFView1");
      }

      /**
       * 
       *  Container's getter for Print_SoRefertopfasView1
       */
      public Print_SoRefertopfasViewImpl getPrint_SoRefertopfasView1()
      {
        return (Print_SoRefertopfasViewImpl)findViewObject("Print_SoRefertopfasView1");
      }

      /**
       * 
       *  Container's getter for Print_SoRefertopfasView2
       */
      public Print_SoRefertopfasViewImpl getPrint_SoRefertopfasView2()
      {
        return (Print_SoRefertopfasViewImpl)findViewObject("Print_SoRefertopfasView2");
      }

      /**
       * 
       *  Container's getter for Print_SoAllegatiRefPF_RefVL1
       */
      public ViewLinkImpl getPrint_SoAllegatiRefPF_RefVL1()
      {
        return (ViewLinkImpl)findViewLink("Print_SoAllegatiRefPF_RefVL1");
      }

      /**
       * 
       *  Container's getter for Print_SoAllegatoView6
       */
      public Print_SoAllegatoViewImpl getPrint_SoAllegatoView6()
      {
        return (Print_SoAllegatoViewImpl)findViewObject("Print_SoAllegatoView6");
      }

      /**
       * 
       *  Container's getter for Print_SoAllRefPF_Allegato1
       */
      public ViewLinkImpl getPrint_SoAllRefPF_Allegato1()
      {
        return (ViewLinkImpl)findViewLink("Print_SoAllRefPF_Allegato1");
      }

      /**
       * 
       *  Container's getter for Print_DatiQuestPFView1
       */
      public Print_DatiQuestPFViewImpl getPrint_DatiQuestPFView1()
      {
        return (Print_DatiQuestPFViewImpl)findViewObject("Print_DatiQuestPFView1");
      }

      /**
       * 
       *  Container's getter for Print_EsamiPfasView1
       */
      public Print_EsamiPfasViewImpl getPrint_EsamiPfasView1()
      {
        return (Print_EsamiPfasViewImpl)findViewObject("Print_EsamiPfasView1");
      }

      /**
       * 
       *  Container's getter for A_SoAccPfas1livView1
       */
      public A_SoAccPfas1livViewImpl getA_SoAccPfas1livView1()
      {
        return (A_SoAccPfas1livViewImpl)findViewObject("A_SoAccPfas1livView1");
      }

    /**
     * Container's getter for Print_SoTemplateOrchReportView1.
     * @return Print_SoTemplateOrchReportView1
     */
    public ViewObjectImpl getPrint_SoTemplateOrchReportView1() {
        return (ViewObjectImpl) findViewObject("Print_SoTemplateOrchReportView1");
    }

    

    /**
     * Container's getter for Print_SoAllegatoView5.
     * @return Print_SoAllegatoView5
     */
    public Print_SoAllegatoViewImpl getPrint_SoAllegatoView5() {
        return (Print_SoAllegatoViewImpl) findViewObject("Print_SoAllegatoView5");
    }

    /**
     * Container's getter for Print_SoAllegatiCA_AllegatoLink1.
     * @return Print_SoAllegatiCA_AllegatoLink1
     */
    public ViewLinkImpl getPrint_SoAllegatiCA_AllegatoLink1() {
        return (ViewLinkImpl) findViewLink("Print_SoAllegatiCA_AllegatoLink1");
    }

    /**
     * Container's getter for Print_SoInterventomammo1.
     * @return Print_SoInterventomammo1
     */
    public ViewObjectImpl getPrint_SoInterventomammo1() {
        return (ViewObjectImpl) findViewObject("Print_SoInterventomammo1");
    }

    /**
     * Container's getter for Print_SoInterventocolonView1.
     * @return Print_SoInterventocolonView1
     */
    public ViewObjectImpl getPrint_SoInterventocolonView1() {
        return (ViewObjectImpl) findViewObject("Print_SoInterventocolonView1");
    }

    /**
     * Container's getter for Print_SoCnfClassePopView1.
     * @return Print_SoCnfClassePopView1
     */
    public ViewObjectImpl getPrint_SoCnfClassePopView1() {
        return (ViewObjectImpl) findViewObject("Print_SoCnfClassePopView1");
    }

    /**
     * Container's getter for Print_SoAllegatoBckView1.
     * @return Print_SoAllegatoBckView1
     */
    public ViewObjectImpl getPrint_SoAllegatoBckView1() {
        return (ViewObjectImpl) findViewObject("Print_SoAllegatoBckView1");
    }
}
