package model;


import model.commons.ConfigurationConstants;
import model.commons.Parent_AppModuleImpl;

import model.conf.Cnf_SoCnfCategTpinvitoViewImpl;
import model.conf.Cnf_SoCnfComuneViewImpl;
import model.conf.Cnf_SoCnfTrialBraccioViewImpl;
import model.conf.Cnf_SoCnfTrialStatoViewImpl;
import model.conf.Cnf_SoDistrettoZonaViewImpl;

import model.global.A_SoAziendaViewImpl;
import model.global.A_SoCentroPrelRefViewImpl;
import model.global.A_SoCnfParametriSistemaViewImpl;
import model.global.A_SoCnfPartemplateViewImpl;
import model.global.A_SoCnfTpinvitoViewImpl;
import model.global.A_SoComuneViewImpl;
import model.global.A_SoMedicoViewImpl;
import model.global.A_SoSoggScrViewImpl;
import model.global.A_SoSoggettoViewImpl;

import model.referto.Ref_SelTipiDocViewImpl;
import model.referto.Ref_SoAccCito1livViewImpl;
import model.referto.Ref_SoAllegatoViewImpl;
import model.referto.Ref_SoAmbIstricViewImpl;
import model.referto.Ref_SoCentroPreievo2livViewImpl;
import model.referto.Ref_SoCentroPrelRefViewImpl;
import model.referto.Ref_SoCentroPrelievoViewImpl;
import model.referto.Ref_SoCentroRefertoViewImpl;
import model.referto.Ref_SoCnfCategTpinvitoImpl;
import model.referto.Ref_SoCnfEsitoinvitoViewImpl;
import model.referto.Ref_SoCnfLetteracentroViewImpl;
import model.referto.Ref_SoCnfPartemplateViewImpl;
import model.referto.Ref_SoCnfRef1LivHPES_ViewImpl;
import model.referto.Ref_SoCnfRef1livADEPREViewImpl;
import model.referto.Ref_SoCnfRef1livGIUDIAViewImpl;
import model.referto.Ref_SoCnfRef1livHPVES1ViewImpl;
import model.referto.Ref_SoCnfRef1livHPVTP1ViewImpl;
import model.referto.Ref_SoCnfRef1livINALIMViewImpl;
import model.referto.Ref_SoCnfRef1livMODREAViewImpl;
import model.referto.Ref_SoCnfRef1livPOSITIViewImpl;
import model.referto.Ref_SoCnfRef1livViewImpl;
import model.referto.Ref_SoCnfRef2livBIODIAViewImpl;
import model.referto.Ref_SoCnfRef2livCITOPOSViewImpl;
import model.referto.Ref_SoCnfRef2livCOLPESViewImpl;
import model.referto.Ref_SoCnfRef2livCOLPPBViewImpl;
import model.referto.Ref_SoCnfRef2livCOLPPCViewImpl;
import model.referto.Ref_SoCnfRef2livCOLPREViewImpl;
import model.referto.Ref_SoCnfRef2livCOLPVLViewImpl;
import model.referto.Ref_SoCnfRef2livGIUDIAViewImpl;
import model.referto.Ref_SoCnfRef2livHPVES2ViewImpl;
import model.referto.Ref_SoCnfRef2livINTMIEViewImpl;
import model.referto.Ref_SoCnfRef2livINTTIPViewImpl;
import model.referto.Ref_SoCnfRef2livINTVALViewImpl;
import model.referto.Ref_SoCnfRef2livISTDIAViewImpl;
import model.referto.Ref_SoCnfRef2livISTGRAViewImpl;
import model.referto.Ref_SoCnfRef2livISTOLMViewImpl;
import model.referto.Ref_SoCnfRef2livISTOPNViewImpl;
import model.referto.Ref_SoCnfRef2livISTOPTViewImpl;
import model.referto.Ref_SoCnfRef2livMODREAViewImpl;
import model.referto.Ref_SoCnfRef2livRACDIAViewImpl;
import model.referto.Ref_SoCnfRef2livSTADIOViewImpl;
import model.referto.Ref_SoCnfRef2livViewImpl;
import model.referto.Ref_SoCnfSugg1livViewImpl;
import model.referto.Ref_SoCnfSugg2livViewImpl;
import model.referto.Ref_SoCnfSugg3livViewImpl;
import model.referto.Ref_SoCnfSuggCrit1livCitoViewImpl;
import model.referto.Ref_SoCnfTpinvitoViewImpl;
import model.referto.Ref_SoCodref1livcADEPREViewImpl;
import model.referto.Ref_SoCodref1livcGIUDIAViewImpl;
import model.referto.Ref_SoCodref1livcINALIMViewImpl;
import model.referto.Ref_SoCodref1livcViewImpl;
import model.referto.Ref_SoCodref2livc2BIODIAViewImpl;
import model.referto.Ref_SoCodref2livc2ViewImpl;
import model.referto.Ref_SoEsitoSuggViewImpl;
import model.referto.Ref_SoInterventocitoISTDIAViewImpl;
import model.referto.Ref_SoInterventocitoViewImpl;
import model.referto.Ref_SoInvitiPerRefertiViewImpl;
import model.referto.Ref_SoInvitoPrimoLivViewImpl;
import model.referto.Ref_SoInvitoViewImpl;
import model.referto.Ref_SoOpmedicoCitoscreenerViewImpl;
import model.referto.Ref_SoOpmedicoSupervisoreViewImpl;
import model.referto.Ref_SoOpmedicoViewImpl;
import model.referto.Ref_SoRefertocito1livViewImpl;
import model.referto.Ref_SoRefertocito2livViewImpl;
import model.referto.Ref_SoSoggScrViewImpl;
import model.referto.Ref_SoSoggettoViewImpl;
import model.referto.Ref_SoSuggerimentiViewImpl;
import model.referto.Ref_SoTemplateViewImpl;

import model.trial.A_SelTrialBraccioViewImpl;
import model.trial.A_SelTrialStatoViewImpl;

import oracle.jbo.ViewObject;
import oracle.jbo.server.ViewLinkImpl;

//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class Ref_AppModuleImpl extends Parent_AppModuleImpl implements model.common.Ref_AppModule  
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public Ref_AppModuleImpl()
  {
  }

  /**
     *
     *  Container's getter for Ref_SoAllegatoView1
     */
    public Ref_SoAllegatoViewImpl getRef_SoAllegatoView1()
  {
    return (Ref_SoAllegatoViewImpl)findViewObject("Ref_SoAllegatoView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCentroPrelRefView1
     */
    public Ref_SoCentroPrelRefViewImpl getRef_SoCentroPrelRefView1()
  {
    return (Ref_SoCentroPrelRefViewImpl)findViewObject("Ref_SoCentroPrelRefView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfEsitoinvitoView1
     */
    public Ref_SoCnfEsitoinvitoViewImpl getRef_SoCnfEsitoinvitoView1()
  {
    return (Ref_SoCnfEsitoinvitoViewImpl)findViewObject("Ref_SoCnfEsitoinvitoView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfLetteracentroView1
     */
    public Ref_SoCnfLetteracentroViewImpl getRef_SoCnfLetteracentroView1()
  {
    return (Ref_SoCnfLetteracentroViewImpl)findViewObject("Ref_SoCnfLetteracentroView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfPartemplateView1
     */
    public Ref_SoCnfPartemplateViewImpl getRef_SoCnfPartemplateView1()
  {
    return (Ref_SoCnfPartemplateViewImpl)findViewObject("Ref_SoCnfPartemplateView1");
  }




  /**
     *
     *  Container's getter for Ref_SoCnfTpinvitoView1
     */
    public Ref_SoCnfTpinvitoViewImpl getRef_SoCnfTpinvitoView1()
  {
    return (Ref_SoCnfTpinvitoViewImpl)findViewObject("Ref_SoCnfTpinvitoView1");
  }

  /**
     *
     *  Container's getter for Ref_SoInvitoView1
     */
    public Ref_SoInvitoViewImpl getRef_SoInvitoView1()
  {
    return (Ref_SoInvitoViewImpl)findViewObject("Ref_SoInvitoView1");
  }

  /**
     *
     *  Container's getter for Ref_SoOpmedicoView1
     */
    public Ref_SoOpmedicoViewImpl getRef_SoOpmedicoView1()
  {
    return (Ref_SoOpmedicoViewImpl)findViewObject("Ref_SoOpmedicoView1");
  }

  /**
     *
     *  Container's getter for Ref_SoSoggScrView1
     */
    public Ref_SoSoggScrViewImpl getRef_SoSoggScrView1()
  {
    return (Ref_SoSoggScrViewImpl)findViewObject("Ref_SoSoggScrView1");
  }

  /**
     *
     *  Container's getter for Ref_SoSoggettoView1
     */
    public Ref_SoSoggettoViewImpl getRef_SoSoggettoView1()
  {
    return (Ref_SoSoggettoViewImpl)findViewObject("Ref_SoSoggettoView1");
  }

  /**
     *
     *  Container's getter for Ref_SoTemplateView1
     */
    public Ref_SoTemplateViewImpl getRef_SoTemplateView1()
  {
    return (Ref_SoTemplateViewImpl)findViewObject("Ref_SoTemplateView1");
  }

  /**
   * 
   *  Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args)
  {
    launchTester("model", "Ref_AppModuleLocal");
  }

  /**
     *
     *  Container's getter for Ref_SoInvitiPerRefertiView1
     */
    public Ref_SoInvitiPerRefertiViewImpl getRef_SoInvitiPerRefertiView1()
  {
    return (Ref_SoInvitiPerRefertiViewImpl)findViewObject("Ref_SoInvitiPerRefertiView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCentroPrelievoView1
     */
    public Ref_SoCentroPrelievoViewImpl getRef_SoCentroPrelievoView1()
  {
    return (Ref_SoCentroPrelievoViewImpl)findViewObject("Ref_SoCentroPrelievoView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCentroRefertoView1
     */
    public Ref_SoCentroRefertoViewImpl getRef_SoCentroRefertoView1()
  {
    return (Ref_SoCentroRefertoViewImpl)findViewObject("Ref_SoCentroRefertoView1");
  }


   public void filterConfiguration(String ulss,String scr,String codregionale, 
   boolean regionale, String centri_in, Integer centro_fisico, Number idTrial)
  {
      String where = "TPSCR='" + scr + "'";
                      
                      String where2 = null;
                      if(!regionale) {
                              where2 = "ULSS='" + ulss + "'";
                      }
                      
                      //centri di prelievo e referto
                      ViewObject vo = this.getRef_SoCentroPrelRefView1();
                      String entity = vo.getDefName().substring(0,vo.getDefName().indexOf("View"));
                      String ad_hoc = entity + "." + where;
                      if (where2 != null)
                              ad_hoc += " AND " + entity + "." + where2;
                      vo.setWhereClause(ad_hoc);
                      vo.executeQuery();
          
                      //solo di prelievo
                      vo = this.getRef_SoCentroPrelievoView1();
                      vo.setWhereClause(ad_hoc);
                      vo.executeQuery();
                      
                      //solo di referto
                      vo = this.getRef_SoCentroRefertoView1();
                      vo.setWhereClause(ad_hoc);
                      vo.executeQuery();
                      
                      //PRELIEVO DI SECONDO LIVELLO
                      vo = this.getRef_SoCentroPreievo2livView1();
                      vo.setWhereClause(ad_hoc);
                      vo.executeQuery();
                      
                      //esito di inviti (tpscr e ulss)
                      vo = this.getRef_SoCnfEsitoinvitoView1();
                      entity = vo.getDefName().substring(0,vo.getDefName().indexOf("View"));
                      ad_hoc = entity + "." + where;
                      if (where2 != null)
                              ad_hoc += " AND " + entity + "." + where2;
                      vo.setWhereClause(ad_hoc);
                      vo.executeQuery();
          
                      //tipi di invito
                      vo = this.getRef_SoCnfTpinvitoView1();
                      entity = vo.getDefName().substring(0,vo.getDefName().indexOf("View"));
                      ad_hoc = entity + "." + where;
                      if (where2 != null)
                              ad_hoc += " AND " + entity + "." + where2;
                      vo.setWhereClause(ad_hoc);
                      vo.executeQuery();
                      
                      //DATI PER UN REFERTO DI PRIMO LIVELLO
                      vo = this.getRef_SoCnfRef1livView1();
                      entity = vo.getDefName().substring(0, vo.getDefName().indexOf("View"));
                      ad_hoc = entity + "." + where;
                      if (where2 != null)
                              ad_hoc += " AND " + entity + "." + where2;
                      vo.setWhereClause(ad_hoc);
                      vo.executeQuery();

                      //suggerimenti di primo livello
                      vo = this.getRef_SoCnfSugg1livView1();
                      entity = vo.getDefName().substring(0, vo.getDefName().indexOf("View"));
                      ad_hoc = entity + "." + where;
                      if (where2 != null)
                              ad_hoc += " AND " + entity + "." + where2;
                      vo.setWhereClause(ad_hoc);
                      vo.executeQuery();
                      
                      vo = this.getRef_SoCnfSugg1livView4();
                      vo.setWhereClause(ad_hoc);
                      vo.executeQuery();
                      
                      vo = this.getRef_SoCnfSugg2livView1();
                      entity = vo.getDefName().substring(0, vo.getDefName().indexOf("View"));
                      ad_hoc = entity + "." + where;
                      if (where2 != null)
                              ad_hoc += " AND " + entity + "." + where2;
                      vo.setWhereClause(ad_hoc);
                      vo.executeQuery();
          
                      vo = this.getRef_SoCnfSugg3livView1();
                      entity = vo.getDefName().substring(0, vo.getDefName().indexOf("View"));
                      ad_hoc = entity + "." + where;
                      if (where2 != null)
                              ad_hoc += " AND " + entity + "." + where2;
                      vo.setWhereClause(ad_hoc);
                      vo.executeQuery();
          
          vo = this.getRef_SoCnfSuggCrit1livCitoView1();
          ad_hoc = "Ref_SoCnfSugg1liv." + where;
          if (where2 != null)
            ad_hoc += " AND Ref_SoCnfSugg1liv." + where2;
          vo.setWhereClause(ad_hoc);
          vo.executeQuery();
                      
                      //TUTTI I SUGGERIMENTI
                      vo = this.getRef_SoSuggerimentiView1();
                      ad_hoc = where;
                      if (where2 != null)
                              ad_hoc += " AND " + where2;
                      vo.setWhereClause(ad_hoc);
                      vo.executeQuery();
                      
                      //configurazioni di secondo livello
                      vo = this.getRef_SoCnfRef2livView1();
                      entity = vo.getDefName().substring(0, vo.getDefName().indexOf("View"));
                      ad_hoc = entity + "." + where;
                      if (where2 != null)
                              ad_hoc += " AND " + entity + "." + where2;
                      vo.setWhereClause(ad_hoc);
                      vo.executeQuery();

                      //categorie di tipi di invito
                      vo = this.getCnf_SoCnfCategTpinvitoView1();
                      entity = vo.getDefName().substring(0, vo.getDefName().indexOf("View"));
                      ad_hoc = entity + "." + where;
                      vo.setWhereClause(ad_hoc);
                      vo.executeQuery();

                      //catgeorie per il richiamo (nè solleciti nè volontari)
                      vo = this.getRef_SoCnfCategTpinvito1();
                      ad_hoc = where + " AND IDCATEG<>" + ConfigurationConstants.CODICE_CAT_SOLLECITO +
                              " AND IDCATEG<>" + ConfigurationConstants.CODICE_CAT_VOLONTARIO;
                      vo.setWhereClause(ad_hoc);
                      vo.executeQuery();

                      //altri centri
                      vo = this.getA_SoCentroPrelRefView1();
                      ad_hoc = where;
                      if (where2 != null)
                              ad_hoc += " AND " + where2;
                      vo.setWhereClause(ad_hoc);
                      vo.executeQuery();
                      
                      //opmedico generici
                      vo = this.getRef_SoOpmedicoView1();
                      entity = vo.getDefName().substring(0, vo.getDefName().indexOf("View"));
                      ad_hoc = entity + "." + where;
                      if (where2 != null)
                              ad_hoc += " AND " + entity + "." + where2;
                      vo.setWhereClause(ad_hoc);
                      vo.executeQuery();
                      
                      //filtro per la ricerca referti
                      vo = this.getRef_SoCnfRef1LivHPES_View1();
                      ad_hoc = where;
                      if (where2 != null)
                              ad_hoc += " AND " + where2;
                      vo.setWhereClause(ad_hoc);
                      vo.executeQuery();
          
                      //ambulatori/istituti di ricovero per interventi
                      vo = this.getRef_SoAmbIstricView1();
                      ad_hoc = "TPIST=0 AND " + where;
                      if (where2 != null)
                              ad_hoc += " AND " + where2;
                      vo.setWhereClause(ad_hoc);
                      vo.executeQuery();
                      
                      //ambulatori/istituti di ricovero per HPV
                      vo = this.getRef_SoAmbIstricView2();
                      ad_hoc = "TPIST=1 AND " + where;
                      if (where2 != null)
                              ad_hoc += " AND " + where2;
                      vo.setWhereClause(ad_hoc);
                      vo.executeQuery();
          
          //tipi documenti
          vo = this.getRef_SelTipiDocView1();
          vo.setWhereClauseParams(new Object[]{ulss});
          vo.executeQuery();

                      //bind params: per evitare query pesanti al primo caricamento (UIMODEL)
                      Object[] pars = {ulss, scr};
                      vo = this.getRef_SoInvitiPerRefertiView1();
                      vo.setWhereClauseParams(pars);
                      vo.setWhereClause("1=2");
                      vo.executeQuery();
                      
                      pars = new Object[]{ulss, scr, null};
                      vo = this.getRef_SoInvitoPrimoLivView1();
                      vo.setWhereClauseParams(pars);
                      
                      vo = this.getRef_SoCnfRef1livADEPREView1();
                      vo.setWhereClause("1=2");
          
                      vo = this.getRef_SoCnfRef1livGIUDIAView1();
                      vo.setWhereClause("1=2");
                      
                      vo = this.getRef_SoCnfRef1livINALIMView1();
                      vo.setWhereClause("1=2");
                      
                      vo = this.getRef_SoCnfRef2livCOLPVLView1();
                      vo.setWhereClause("1=2");
                      
                      vo = this.getRef_SoCnfRef2livCOLPESView1();
                      vo.setWhereClause("1=2");
                      
                      /*20080710 MOD: aggiunta stadiazione*/
                      vo = this.getRef_SoCnfRef2livSTADIOView1();
                      vo.setWhereClause("1=2");
                      /*20080710 FINE MOD*/
                      
                      vo = this.getRef_SoCnfRef1livHPVES1View1();
                      vo.setWhereClause("1=2");
                      
                      vo = this.getRef_SoCnfRef1livHPVTP1View1();
                      vo.setWhereClause("1=2");
          
          vo = this.getRef_SoCnfRef2livHPVES2View1();
                      vo.setWhereClause("1=2");
                      
                      vo = this.getRef_SoOpmedicoCitoscreenerView1();
                      vo.setWhereClause("1=2");
                      
                      vo = this.getRef_SoOpmedicoSupervisoreView1();
                      vo.setWhereClause("1=2");
       
                      // Trial
                      pars = new Object[]{idTrial, scr};
                      vo = getA_SelTrialStatoView1();
                      vo.setWhereClauseParams(pars);
                      vo = getA_SelTrialBraccioView1();
                      vo.setWhereClauseParams(pars);
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef1livView1
     */
    public Ref_SoCnfRef1livViewImpl getRef_SoCnfRef1livView1()
  {
    return (Ref_SoCnfRef1livViewImpl)findViewObject("Ref_SoCnfRef1livView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfSugg1livView1
     */
    public Ref_SoCnfSugg1livViewImpl getRef_SoCnfSugg1livView1()
  {
    return (Ref_SoCnfSugg1livViewImpl)findViewObject("Ref_SoCnfSugg1livView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCodref1livcView1
     */
    public Ref_SoCodref1livcViewImpl getRef_SoCodref1livcView1()
  {
    return (Ref_SoCodref1livcViewImpl)findViewObject("Ref_SoCodref1livcView1");
  }

  /**
     *
     *  Container's getter for Ref_SoRefertocito1livView1
     */
    public Ref_SoRefertocito1livViewImpl getRef_SoRefertocito1livView1()
  {
    return (Ref_SoRefertocito1livViewImpl)findViewObject("Ref_SoRefertocito1livView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCodref1livcView2
     */
    public Ref_SoCodref1livcViewImpl getRef_SoCodref1livcView2()
  {
    return (Ref_SoCodref1livcViewImpl)findViewObject("Ref_SoCodref1livcView2");
  }

  /**
     *
     *  Container's getter for Ref_SoCodref1livcView3
     */
    public Ref_SoCodref1livcViewImpl getRef_SoCodref1livcView3()
  {
    return (Ref_SoCodref1livcViewImpl)findViewObject("Ref_SoCodref1livcView3");
  }

  /**
     *
     *  Container's getter for Ref_SoRefertocito1livView2
     */
    public Ref_SoRefertocito1livViewImpl getRef_SoRefertocito1livView2()
  {
    return (Ref_SoRefertocito1livViewImpl)findViewObject("Ref_SoRefertocito1livView2");
  }

  /**
   *
   *  Container's getter for FkSoCodreFkSoCodSoCnfRLink1
   */
    public ViewLinkImpl getFkSoCodreFkSoCodSoCnfRLink1()
  {
        return (ViewLinkImpl)findViewLink("FkSoCodreFkSoCodSoCnfRLink1");
    }

  /**
   *
   *  Container's getter for FkSoCodref1livcSoReferLink1
   */
    public ViewLinkImpl getFkSoCodref1livcSoReferLink1()
  {
        return (ViewLinkImpl)findViewLink("FkSoCodref1livcSoReferLink1");


    }

  /**
   *
   *  Container's getter for FkSoReferHaSuggerSoCnfSLink1
   */
    public ViewLinkImpl getFkSoReferHaSuggerSoCnfSLink1()
  {
        return (ViewLinkImpl)findViewLink("FkSoReferHaSuggerSoCnfSLink1");

    }

  /**
     *
     *  Container's getter for Ref_SoCnfRef1livADEPREView1
     */
    public Ref_SoCnfRef1livADEPREViewImpl getRef_SoCnfRef1livADEPREView1()
  {
    return (Ref_SoCnfRef1livADEPREViewImpl)findViewObject("Ref_SoCnfRef1livADEPREView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef1livGIUDIAView1
     */
    public Ref_SoCnfRef1livGIUDIAViewImpl getRef_SoCnfRef1livGIUDIAView1()
  {
    return (Ref_SoCnfRef1livGIUDIAViewImpl)findViewObject("Ref_SoCnfRef1livGIUDIAView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef1livMODREAView1
     */
    public Ref_SoCnfRef1livMODREAViewImpl getRef_SoCnfRef1livMODREAView1()
  {
    return (Ref_SoCnfRef1livMODREAViewImpl)findViewObject("Ref_SoCnfRef1livMODREAView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef1livINALIMView1
     */
    public Ref_SoCnfRef1livINALIMViewImpl getRef_SoCnfRef1livINALIMView1()
  {
    return (Ref_SoCnfRef1livINALIMViewImpl)findViewObject("Ref_SoCnfRef1livINALIMView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef1livPOSITIView1
     */
    public Ref_SoCnfRef1livPOSITIViewImpl getRef_SoCnfRef1livPOSITIView1()
  {
    return (Ref_SoCnfRef1livPOSITIViewImpl)findViewObject("Ref_SoCnfRef1livPOSITIView1");
  }

  /**
     *
     *  Container's getter for Ref_SoRefertocito1livView3
     */
    public Ref_SoRefertocito1livViewImpl getRef_SoRefertocito1livView3()
  {
    return (Ref_SoRefertocito1livViewImpl)findViewObject("Ref_SoRefertocito1livView3");
  }

  /**
   *
   *  Container's getter for Ref_InvitiReferti1livLink1
   */
    public ViewLinkImpl getRef_InvitiReferti1livLink1()
  {
        return (ViewLinkImpl)findViewLink("Ref_InvitiReferti1livLink1");
    }

  /**
     *
     *  Container's getter for Ref_SoInvitoView2
     */
    public Ref_SoInvitoViewImpl getRef_SoInvitoView2()
  {
    return (Ref_SoInvitoViewImpl)findViewObject("Ref_SoInvitoView2");
  }

  /**
   *
   *  Container's getter for Ref_SoInvitiRefInvitoLink1
   */
    public ViewLinkImpl getRef_SoInvitiRefInvitoLink1()
  {
        return (ViewLinkImpl)findViewLink("Ref_SoInvitiRefInvitoLink1");
    }

  /**
     *
     *  Container's getter for Ref_SoOpmedicoSupervisoreView1
     */
    public Ref_SoOpmedicoSupervisoreViewImpl getRef_SoOpmedicoSupervisoreView1()
  {
    return (Ref_SoOpmedicoSupervisoreViewImpl)findViewObject("Ref_SoOpmedicoSupervisoreView1");
  }

  /**
     *
     *  Container's getter for Ref_SoOpmedicoCitoscreenerView1
     */
    public Ref_SoOpmedicoCitoscreenerViewImpl getRef_SoOpmedicoCitoscreenerView1()
  {
    return (Ref_SoOpmedicoCitoscreenerViewImpl)findViewObject("Ref_SoOpmedicoCitoscreenerView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCodref1livcView4
     */
    public Ref_SoCodref1livcViewImpl getRef_SoCodref1livcView4()
  {
    return (Ref_SoCodref1livcViewImpl)findViewObject("Ref_SoCodref1livcView4");
  }

  /**
     *
     *  Container's getter for Ref_SoCodref1livcADEPREView1
     */
    public Ref_SoCodref1livcADEPREViewImpl getRef_SoCodref1livcADEPREView1()
  {
    return (Ref_SoCodref1livcADEPREViewImpl)findViewObject("Ref_SoCodref1livcADEPREView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCodref1livcGIUDIAView1
     */
    public Ref_SoCodref1livcGIUDIAViewImpl getRef_SoCodref1livcGIUDIAView1()
  {
    return (Ref_SoCodref1livcGIUDIAViewImpl)findViewObject("Ref_SoCodref1livcGIUDIAView1");
  }

  /**
   *
   *  Container's getter for FkSoCodref1livcSoReferLink2
   */
    public ViewLinkImpl getFkSoCodref1livcSoReferLink2()
  {
        return (ViewLinkImpl)findViewLink("FkSoCodref1livcSoReferLink2");
    }

  /**
   *
   *  Container's getter for Ref_SoRefertoCito1livAdepreLink1
   */
    public ViewLinkImpl getRef_SoRefertoCito1livAdepreLink1()
  {
        return (ViewLinkImpl)findViewLink("Ref_SoRefertoCito1livAdepreLink1");
    }

  /**
   *
   *  Container's getter for Ref_SoRefertocito1livGiudiaLink1
   */
    public ViewLinkImpl getRef_SoRefertocito1livGiudiaLink1()
  {
        return (ViewLinkImpl)findViewLink("Ref_SoRefertocito1livGiudiaLink1");
    }




  /**
     *
     *  Container's getter for A_SoAziendaView1
     */
    public A_SoAziendaViewImpl getA_SoAziendaView1()
  {
    return (A_SoAziendaViewImpl)findViewObject("A_SoAziendaView1");
  }

  /**
     *
     *  Container's getter for A_SoCnfPartemplateView1
     */
    public A_SoCnfPartemplateViewImpl getA_SoCnfPartemplateView1()
  {
    return (A_SoCnfPartemplateViewImpl)findViewObject("A_SoCnfPartemplateView1");
  }

  /**
     *
     *  Container's getter for A_SoSoggettoView1
     */
    public A_SoSoggettoViewImpl getA_SoSoggettoView1()
  {
    return (A_SoSoggettoViewImpl)findViewObject("A_SoSoggettoView1");
  }

  /**
     *
     *  Container's getter for A_SoCentroPrelRefView1
     */
    public A_SoCentroPrelRefViewImpl getA_SoCentroPrelRefView1()
  {
    return (A_SoCentroPrelRefViewImpl)findViewObject("A_SoCentroPrelRefView1");
  }

  /**
     *
     *  Container's getter for A_SoComuneView1
     */
    public A_SoComuneViewImpl getA_SoComuneView1()
  {
    return (A_SoComuneViewImpl)findViewObject("A_SoComuneView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfSugg1livView2
     */
    public Ref_SoCnfSugg1livViewImpl getRef_SoCnfSugg1livView2()
  {
    return (Ref_SoCnfSugg1livViewImpl)findViewObject("Ref_SoCnfSugg1livView2");
  }


  /**
     *
     *  Container's getter for Ref_SoAmbIstricView1
     */
    public Ref_SoAmbIstricViewImpl getRef_SoAmbIstricView1()
  {
    return (Ref_SoAmbIstricViewImpl)findViewObject("Ref_SoAmbIstricView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef2livView1
     */
    public Ref_SoCnfRef2livViewImpl getRef_SoCnfRef2livView1()
  {
    return (Ref_SoCnfRef2livViewImpl)findViewObject("Ref_SoCnfRef2livView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfSugg2livView1
     */
    public Ref_SoCnfSugg2livViewImpl getRef_SoCnfSugg2livView1()
  {
    return (Ref_SoCnfSugg2livViewImpl)findViewObject("Ref_SoCnfSugg2livView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfSugg3livView1
     */
    public Ref_SoCnfSugg3livViewImpl getRef_SoCnfSugg3livView1()
  {
    return (Ref_SoCnfSugg3livViewImpl)findViewObject("Ref_SoCnfSugg3livView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCodref2livc2View1
     */
    public Ref_SoCodref2livc2ViewImpl getRef_SoCodref2livc2View1()
  {
    return (Ref_SoCodref2livc2ViewImpl)findViewObject("Ref_SoCodref2livc2View1");
  }

  /**
     *
     *  Container's getter for Ref_SoInterventocitoView1
     */
    public Ref_SoInterventocitoViewImpl getRef_SoInterventocitoView1()
  {
    return (Ref_SoInterventocitoViewImpl)findViewObject("Ref_SoInterventocitoView1");
  }

  /**
     *
     *  Container's getter for Ref_SoRefertocito2livView1
     */
    public Ref_SoRefertocito2livViewImpl getRef_SoRefertocito2livView1()
  {
    return (Ref_SoRefertocito2livViewImpl) findViewObject("Ref_SoRefertocito2livView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCodref2livc2View2
     */
    public Ref_SoCodref2livc2ViewImpl getRef_SoCodref2livc2View2()
  {
    return (Ref_SoCodref2livc2ViewImpl)findViewObject("Ref_SoCodref2livc2View2");
  }

  /**
     *
     *  Container's getter for Ref_SoInterventocitoView2
     */
    public Ref_SoInterventocitoViewImpl getRef_SoInterventocitoView2()
  {
    return (Ref_SoInterventocitoViewImpl)findViewObject("Ref_SoInterventocitoView2");
  }

  /**
     *
     *  Container's getter for Ref_SoInterventocitoView3
     */
    public Ref_SoInterventocitoViewImpl getRef_SoInterventocitoView3()
  {
    return (Ref_SoInterventocitoViewImpl)findViewObject("Ref_SoInterventocitoView3");
  }

  /**
     *
     *  Container's getter for Ref_SoInterventocitoView4
     */
    public Ref_SoInterventocitoViewImpl getRef_SoInterventocitoView4()
  {
    return (Ref_SoInterventocitoViewImpl)findViewObject("Ref_SoInterventocitoView4");
  }

  /**
     *
     *  Container's getter for Ref_SoInterventocitoView5
     */
    public Ref_SoInterventocitoViewImpl getRef_SoInterventocitoView5()
  {
    return (Ref_SoInterventocitoViewImpl)findViewObject("Ref_SoInterventocitoView5");
  }

  /**
     *
     *  Container's getter for Ref_SoCodref2livc2View3
     */
    public Ref_SoCodref2livc2ViewImpl getRef_SoCodref2livc2View3()
  {
    return (Ref_SoCodref2livc2ViewImpl)findViewObject("Ref_SoCodref2livc2View3");
  }


  /**
     *
     *  Container's getter for Ref_SoRefertocito2livView3
     */
    public Ref_SoRefertocito2livViewImpl getRef_SoRefertocito2livView3()
  {
    return (Ref_SoRefertocito2livViewImpl) findViewObject("Ref_SoRefertocito2livView3");
  }

  /**
   *
   *  Container's getter for FkSoCodreSoCnfRef2lLink1
   */
    public ViewLinkImpl getFkSoCodreSoCnfRef2lLink1()
  {
        return (ViewLinkImpl)findViewLink("FkSoCodreSoCnfRef2lLink1");
    }

  /**
   *
   *  Container's getter for FkInterRef2livMotesecLink1
   */
    public ViewLinkImpl getFkInterRef2livMotesecLink1()
  {
        return (ViewLinkImpl)findViewLink("FkInterRef2livMotesecLink1");
    }

  /**
   *
   *  Container's getter for FkInterRef2livMotintLink1
   */
    public ViewLinkImpl getFkInterRef2livMotintLink1()
  {
        return (ViewLinkImpl)findViewLink("FkInterRef2livMotintLink1");
    }

  /**
   *
   *  Container's getter for FkInterRef2livOpzLink1
   */
    public ViewLinkImpl getFkInterRef2livOpzLink1()
  {
        return (ViewLinkImpl)findViewLink("FkInterRef2livOpzLink1");
    }

  /**
   *
   *  Container's getter for FkSoInterSoReferLink1
   */
    public ViewLinkImpl getFkSoInterSoReferLink1()
  {
        return (ViewLinkImpl)findViewLink("FkSoInterSoReferLink1");
    }

  /**
   *
   *  Container's getter for FkSoCodref2livcSoReferLink1
   */
    public ViewLinkImpl getFkSoCodref2livcSoReferLink1()
  {
        return (ViewLinkImpl)findViewLink("FkSoCodref2livcSoReferLink1");
    }


  /**
   *
   *  Container's getter for FkSoReferHaSugg2SoCnfSLink1
   */
    public ViewLinkImpl getFkSoReferHaSugg2SoCnfSLink1()
  {
        return (ViewLinkImpl)findViewLink("FkSoReferHaSugg2SoCnfSLink1");
    }

  /**
     *
     *  Container's getter for Ref_SoRefertocito2livView4
     */
    public Ref_SoRefertocito2livViewImpl getRef_SoRefertocito2livView4()
  {
    return (Ref_SoRefertocito2livViewImpl) findViewObject("Ref_SoRefertocito2livView4");
  }

  /**
   *
   *  Container's getter for Ref_SoInvitiRefRefert2lView1
   */
    public ViewLinkImpl getRef_SoInvitiRefRefert2lView1()
  {
        return (ViewLinkImpl)findViewLink("Ref_SoInvitiRefRefert2lView1");
    }

  /**
     *
     *  Container's getter for Ref_SoCnfSugg3livView2
     */
    public Ref_SoCnfSugg3livViewImpl getRef_SoCnfSugg3livView2()
  {
    return (Ref_SoCnfSugg3livViewImpl)findViewObject("Ref_SoCnfSugg3livView2");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfSugg2livView2
     */
    public Ref_SoCnfSugg2livViewImpl getRef_SoCnfSugg2livView2()
  {
    return (Ref_SoCnfSugg2livViewImpl)findViewObject("Ref_SoCnfSugg2livView2");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef2livCITOPOSView1
     */
    public Ref_SoCnfRef2livCITOPOSViewImpl getRef_SoCnfRef2livCITOPOSView1()
  {
    return (Ref_SoCnfRef2livCITOPOSViewImpl)findViewObject("Ref_SoCnfRef2livCITOPOSView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef2livGIUDIAView1
     */
    public Ref_SoCnfRef2livGIUDIAViewImpl getRef_SoCnfRef2livGIUDIAView1()
  {
    return (Ref_SoCnfRef2livGIUDIAViewImpl)findViewObject("Ref_SoCnfRef2livGIUDIAView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef2livMODREAView1
     */
    public Ref_SoCnfRef2livMODREAViewImpl getRef_SoCnfRef2livMODREAView1()
  {
    return (Ref_SoCnfRef2livMODREAViewImpl)findViewObject("Ref_SoCnfRef2livMODREAView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCodref2livc2View4
     */
    public Ref_SoCodref2livc2ViewImpl getRef_SoCodref2livc2View4()
  {
    return (Ref_SoCodref2livc2ViewImpl)findViewObject("Ref_SoCodref2livc2View4");
  }

  /**
   *
   *  Container's getter for FkSoCodref2livcSoReferLink2
   */
    public ViewLinkImpl getFkSoCodref2livcSoReferLink2()
  {
        return (ViewLinkImpl)findViewLink("FkSoCodref2livcSoReferLink2");
    }

  /**
     *
     *  Container's getter for Ref_SoCnfRef2livCOLPVLView1
     */
    public Ref_SoCnfRef2livCOLPVLViewImpl getRef_SoCnfRef2livCOLPVLView1()
  {
    return (Ref_SoCnfRef2livCOLPVLViewImpl)findViewObject("Ref_SoCnfRef2livCOLPVLView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef2livCOLPESView1
     */
    public Ref_SoCnfRef2livCOLPESViewImpl getRef_SoCnfRef2livCOLPESView1()
  {
    return (Ref_SoCnfRef2livCOLPESViewImpl)findViewObject("Ref_SoCnfRef2livCOLPESView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef2livCOLPPCView1
     */
    public Ref_SoCnfRef2livCOLPPCViewImpl getRef_SoCnfRef2livCOLPPCView1()
  {
    return (Ref_SoCnfRef2livCOLPPCViewImpl)findViewObject("Ref_SoCnfRef2livCOLPPCView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef2livCOLPPBView1
     */
    public Ref_SoCnfRef2livCOLPPBViewImpl getRef_SoCnfRef2livCOLPPBView1()
  {
    return (Ref_SoCnfRef2livCOLPPBViewImpl)findViewObject("Ref_SoCnfRef2livCOLPPBView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef2livCOLPREView1
     */
    public Ref_SoCnfRef2livCOLPREViewImpl getRef_SoCnfRef2livCOLPREView1()
  {
    return (Ref_SoCnfRef2livCOLPREViewImpl)findViewObject("Ref_SoCnfRef2livCOLPREView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef2livISTDIAView1
     */
    public Ref_SoCnfRef2livISTDIAViewImpl getRef_SoCnfRef2livISTDIAView1()
  {
    return (Ref_SoCnfRef2livISTDIAViewImpl)findViewObject("Ref_SoCnfRef2livISTDIAView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef2livISTGRAView1
     */
    public Ref_SoCnfRef2livISTGRAViewImpl getRef_SoCnfRef2livISTGRAView1()
  {
    return (Ref_SoCnfRef2livISTGRAViewImpl)findViewObject("Ref_SoCnfRef2livISTGRAView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef2livRACDIAView1
     */
    public Ref_SoCnfRef2livRACDIAViewImpl getRef_SoCnfRef2livRACDIAView1()
  {
    return (Ref_SoCnfRef2livRACDIAViewImpl)findViewObject("Ref_SoCnfRef2livRACDIAView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef2livISTOLMView1
     */
    public Ref_SoCnfRef2livISTOLMViewImpl getRef_SoCnfRef2livISTOLMView1()
  {
    return (Ref_SoCnfRef2livISTOLMViewImpl)findViewObject("Ref_SoCnfRef2livISTOLMView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef2livISTOPNView1
     */
    public Ref_SoCnfRef2livISTOPNViewImpl getRef_SoCnfRef2livISTOPNView1()
  {
    return (Ref_SoCnfRef2livISTOPNViewImpl)findViewObject("Ref_SoCnfRef2livISTOPNView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef2livISTOPTView1
     */
    public Ref_SoCnfRef2livISTOPTViewImpl getRef_SoCnfRef2livISTOPTView1()
  {
    return (Ref_SoCnfRef2livISTOPTViewImpl)findViewObject("Ref_SoCnfRef2livISTOPTView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef2livBIODIAView1
     */
    public Ref_SoCnfRef2livBIODIAViewImpl getRef_SoCnfRef2livBIODIAView1()
  {
    return (Ref_SoCnfRef2livBIODIAViewImpl)findViewObject("Ref_SoCnfRef2livBIODIAView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCentroPreievo2livView1
     */
    public Ref_SoCentroPreievo2livViewImpl getRef_SoCentroPreievo2livView1()
  {
    return (Ref_SoCentroPreievo2livViewImpl)findViewObject("Ref_SoCentroPreievo2livView1");
  }

  /**
     *
     *  Container's getter for Cnf_SoCnfCategTpinvitoView1
     */
    public Cnf_SoCnfCategTpinvitoViewImpl getCnf_SoCnfCategTpinvitoView1()
  {
    return (Cnf_SoCnfCategTpinvitoViewImpl)findViewObject("Cnf_SoCnfCategTpinvitoView1");
  }

  /**
     *
     *  Container's getter for Ref_SoInterventocitoView6
     */
    public Ref_SoInterventocitoViewImpl getRef_SoInterventocitoView6()
  {
    return (Ref_SoInterventocitoViewImpl)findViewObject("Ref_SoInterventocitoView6");
  }

  /**
   *
   *  Container's getter for FkSoInterSoReferLink2
   */
    public ViewLinkImpl getFkSoInterSoReferLink2()
  {
        return (ViewLinkImpl)findViewLink("FkSoInterSoReferLink2");
    }

  /**
     *
     *  Container's getter for Ref_SoCnfRef2livINTVALView1
     */
    public Ref_SoCnfRef2livINTVALViewImpl getRef_SoCnfRef2livINTVALView1()
  {
    return (Ref_SoCnfRef2livINTVALViewImpl)findViewObject("Ref_SoCnfRef2livINTVALView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef2livINTMIEView1
     */
    public Ref_SoCnfRef2livINTMIEViewImpl getRef_SoCnfRef2livINTMIEView1()
  {
    return (Ref_SoCnfRef2livINTMIEViewImpl)findViewObject("Ref_SoCnfRef2livINTMIEView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef2livINTTIPView1
     */
    public Ref_SoCnfRef2livINTTIPViewImpl getRef_SoCnfRef2livINTTIPView1()
  {
    return (Ref_SoCnfRef2livINTTIPViewImpl)findViewObject("Ref_SoCnfRef2livINTTIPView1");
  }



  /**
     *
     *  Container's getter for A_SoSoggScrView1
     */
    public A_SoSoggScrViewImpl getA_SoSoggScrView1()
  {
    return (A_SoSoggScrViewImpl)findViewObject("A_SoSoggScrView1");
  }

  /**
     *
     *  Container's getter for Ref_SoInvitoPrimoLivView1
     */
    public Ref_SoInvitoPrimoLivViewImpl getRef_SoInvitoPrimoLivView1()
  {
    return (Ref_SoInvitoPrimoLivViewImpl)findViewObject("Ref_SoInvitoPrimoLivView1");
  }

  /**
     *
     *  Container's getter for Cnf_SoDistrettoZonaView1
     */
    public Cnf_SoDistrettoZonaViewImpl getCnf_SoDistrettoZonaView1()
  {
    return (Cnf_SoDistrettoZonaViewImpl)findViewObject("Cnf_SoDistrettoZonaView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCodref2livc2BIODIAView1
     */
    public Ref_SoCodref2livc2BIODIAViewImpl getRef_SoCodref2livc2BIODIAView1()
  {
    return (Ref_SoCodref2livc2BIODIAViewImpl)findViewObject("Ref_SoCodref2livc2BIODIAView1");
  }

  /**
   *
   *  Container's getter for Ref_FKSoRef2livBiodiaLink1
   */
    public ViewLinkImpl getRef_FKSoRef2livBiodiaLink1()
  {
        return (ViewLinkImpl)findViewLink("Ref_FKSoRef2livBiodiaLink1");
    }

  /**
     *
     *  Container's getter for Ref_SoInterventocitoISTDIAView1
     */
    public Ref_SoInterventocitoISTDIAViewImpl getRef_SoInterventocitoISTDIAView1()
  {
    return (Ref_SoInterventocitoISTDIAViewImpl)findViewObject("Ref_SoInterventocitoISTDIAView1");
  }

  /**
   *
   *  Container's getter for Ref_FKRef2livIntISTDIALink1
   */
    public ViewLinkImpl getRef_FKRef2livIntISTDIALink1()
  {
        return (ViewLinkImpl)findViewLink("Ref_FKRef2livIntISTDIALink1");
    }


  /**
   *
   *  Container's getter for Ref_FKInvitoAcc1liv1
   */
    public ViewLinkImpl getRef_FKInvitoAcc1liv1()
  {
        return (ViewLinkImpl)findViewLink("Ref_FKInvitoAcc1liv1");
    }

  /**
     *
     *  Container's getter for Ref_SoAccCito1livView2
     */
    public Ref_SoAccCito1livViewImpl getRef_SoAccCito1livView2()
  {
    return (Ref_SoAccCito1livViewImpl)findViewObject("Ref_SoAccCito1livView2");
  }

  /**
     *
     *  Container's getter for Ref_SoAccCito1livView1
     */
    public Ref_SoAccCito1livViewImpl getRef_SoAccCito1livView1()
  {
    return (Ref_SoAccCito1livViewImpl)findViewObject("Ref_SoAccCito1livView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfSugg1livView3
     */
    public Ref_SoCnfSugg1livViewImpl getRef_SoCnfSugg1livView3()
  {
    return (Ref_SoCnfSugg1livViewImpl)findViewObject("Ref_SoCnfSugg1livView3");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfSugg2livView3
     */
    public Ref_SoCnfSugg2livViewImpl getRef_SoCnfSugg2livView3()
  {
    return (Ref_SoCnfSugg2livViewImpl)findViewObject("Ref_SoCnfSugg2livView3");
  }


  /**
   *
   *  Container's getter for Ref_FKRefcito1livSugg1liv1
   */
    public ViewLinkImpl getRef_FKRefcito1livSugg1liv1()
  {
        return (ViewLinkImpl)findViewLink("Ref_FKRefcito1livSugg1liv1");
    }

  /**
   *
   *  Container's getter for Ref_FKRefcito2livSugg2liv1
   */
    public ViewLinkImpl getRef_FKRefcito2livSugg2liv1()
  {
        return (ViewLinkImpl)findViewLink("Ref_FKRefcito2livSugg2liv1");
    }


  /**
     *
     *  Container's getter for Ref_SoInterventocitoView7
     */
    public Ref_SoInterventocitoViewImpl getRef_SoInterventocitoView7()
  {
    return (Ref_SoInterventocitoViewImpl)findViewObject("Ref_SoInterventocitoView7");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfSugg3livView3
     */
    public Ref_SoCnfSugg3livViewImpl getRef_SoCnfSugg3livView3()
  {
    return (Ref_SoCnfSugg3livViewImpl)findViewObject("Ref_SoCnfSugg3livView3");
  }

  /**
   *
   *  Container's getter for FkSoInterSoReferLink3
   */
    public ViewLinkImpl getFkSoInterSoReferLink3()
  {
        return (ViewLinkImpl)findViewLink("FkSoInterSoReferLink3");
    }

  /**
   *
   *  Container's getter for Ref_FKIntervCitoSugg3liv1
   */
    public ViewLinkImpl getRef_FKIntervCitoSugg3liv1()
  {
        return (ViewLinkImpl)findViewLink("Ref_FKIntervCitoSugg3liv1");
    }

  /**
     *
     *  Container's getter for Ref_SoCodref1livcADEPREView2
     */
    public Ref_SoCodref1livcADEPREViewImpl getRef_SoCodref1livcADEPREView2()
  {
    return (Ref_SoCodref1livcADEPREViewImpl)findViewObject("Ref_SoCodref1livcADEPREView2");
  }

  /**
     *
     *  Container's getter for Ref_SoCodref1livcGIUDIAView2
     */
    public Ref_SoCodref1livcGIUDIAViewImpl getRef_SoCodref1livcGIUDIAView2()
  {
    return (Ref_SoCodref1livcGIUDIAViewImpl)findViewObject("Ref_SoCodref1livcGIUDIAView2");
  }

  /**
     *
     *  Container's getter for Ref_SoCodref1livcINALIMView1
     */
    public Ref_SoCodref1livcINALIMViewImpl getRef_SoCodref1livcINALIMView1()
  {
    return (Ref_SoCodref1livcINALIMViewImpl)findViewObject("Ref_SoCodref1livcINALIMView1");
  }

  /**
   *
   *  Container's getter for Ref_SoPrimoLivAdepreLink1
   */
    public ViewLinkImpl getRef_SoPrimoLivAdepreLink1()
  {
        return (ViewLinkImpl)findViewLink("Ref_SoPrimoLivAdepreLink1");
    }

  /**
   *
   *  Container's getter for Ref_SoPrimoLivGiudiaLink1
   */
    public ViewLinkImpl getRef_SoPrimoLivGiudiaLink1()
  {
        return (ViewLinkImpl)findViewLink("Ref_SoPrimoLivGiudiaLink1");
    }

  /**
   *
   *  Container's getter for Ref_SoPrimoLivInalimLink1
   */
    public ViewLinkImpl getRef_SoPrimoLivInalimLink1()
  {
        return (ViewLinkImpl)findViewLink("Ref_SoPrimoLivInalimLink1");
    }

  /**
     *
     *  Container's getter for Ref_SoOpmedicoView2
     */
    public Ref_SoOpmedicoViewImpl getRef_SoOpmedicoView2()
  {
    return (Ref_SoOpmedicoViewImpl)findViewObject("Ref_SoOpmedicoView2");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfSugg1livView4
     */
    public Ref_SoCnfSugg1livViewImpl getRef_SoCnfSugg1livView4()
  {
    return (Ref_SoCnfSugg1livViewImpl)findViewObject("Ref_SoCnfSugg1livView4");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef2livView2
     */
    public Ref_SoCnfRef2livViewImpl getRef_SoCnfRef2livView2()
  {
    return (Ref_SoCnfRef2livViewImpl)findViewObject("Ref_SoCnfRef2livView2");
  }

  /**
     *
     *  Container's getter for A_SoCnfTpinvitoView1
     */
    public A_SoCnfTpinvitoViewImpl getA_SoCnfTpinvitoView1()
  {
    return (A_SoCnfTpinvitoViewImpl)findViewObject("A_SoCnfTpinvitoView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfCategTpinvito1
     */
    public Ref_SoCnfCategTpinvitoImpl getRef_SoCnfCategTpinvito1()
  {
    return (Ref_SoCnfCategTpinvitoImpl)findViewObject("Ref_SoCnfCategTpinvito1");
  }

  /**
     *
     *  Container's getter for Cnf_SoCnfComuneView1
     */
    public Cnf_SoCnfComuneViewImpl getCnf_SoCnfComuneView1()
  {
    return (Cnf_SoCnfComuneViewImpl)findViewObject("Cnf_SoCnfComuneView1");
  }

  /**
     *
     *  Container's getter for A_SoMedicoView1
     */
    public A_SoMedicoViewImpl getA_SoMedicoView1()
  {
    return (A_SoMedicoViewImpl)findViewObject("A_SoMedicoView1");
  }

  /**
     *
     *  Container's getter for Ref_SoSuggerimentiView1
     */
    public Ref_SoSuggerimentiViewImpl getRef_SoSuggerimentiView1()
  {
    return (Ref_SoSuggerimentiViewImpl)findViewObject("Ref_SoSuggerimentiView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef2livSTADIOView1
     */
    public Ref_SoCnfRef2livSTADIOViewImpl getRef_SoCnfRef2livSTADIOView1()
  {
    return (Ref_SoCnfRef2livSTADIOViewImpl)findViewObject("Ref_SoCnfRef2livSTADIOView1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef1livHPVES1View1
     */
    public Ref_SoCnfRef1livHPVES1ViewImpl getRef_SoCnfRef1livHPVES1View1()
  {
    return (Ref_SoCnfRef1livHPVES1ViewImpl)findViewObject("Ref_SoCnfRef1livHPVES1View1");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef1livHPVTP1View1
     */
    public Ref_SoCnfRef1livHPVTP1ViewImpl getRef_SoCnfRef1livHPVTP1View1()
  {
    return (Ref_SoCnfRef1livHPVTP1ViewImpl)findViewObject("Ref_SoCnfRef1livHPVTP1View1");
  }

  /**
     *
     *  Container's getter for Ref_SoAmbIstricView2
     */
    public Ref_SoAmbIstricViewImpl getRef_SoAmbIstricView2()
  {
    return (Ref_SoAmbIstricViewImpl)findViewObject("Ref_SoAmbIstricView2");
  }

  /**
     *
     *  Container's getter for Ref_SoCnfRef1LivHPES_View1
     */
    public Ref_SoCnfRef1LivHPES_ViewImpl getRef_SoCnfRef1LivHPES_View1()
  {
    return (Ref_SoCnfRef1LivHPES_ViewImpl)findViewObject("Ref_SoCnfRef1LivHPES_View1");
  }

  /**
     *
     *  Container's getter for A_SoCnfParametriSistemaView1
     */
    public A_SoCnfParametriSistemaViewImpl getA_SoCnfParametriSistemaView1()
  {
    return (A_SoCnfParametriSistemaViewImpl)findViewObject("A_SoCnfParametriSistemaView1");
  }

  /**
     *
     *  Container's getter for Ref_SoEsitoSuggView1
     */
    public Ref_SoEsitoSuggViewImpl getRef_SoEsitoSuggView1()
  {
    return (Ref_SoEsitoSuggViewImpl)findViewObject("Ref_SoEsitoSuggView1");
  }


    /**
     * Container's getter for Cnf_SoCnfTrialBraccioView1.
     * @return Cnf_SoCnfTrialBraccioView1
     */
    public Cnf_SoCnfTrialBraccioViewImpl getCnf_SoCnfTrialBraccioView1() {
        return (Cnf_SoCnfTrialBraccioViewImpl) findViewObject("Cnf_SoCnfTrialBraccioView1");
    }

    /**
     * Container's getter for Ref_SoggScr_Braccio1.
     * @return Ref_SoggScr_Braccio1
     */
    public ViewLinkImpl getRef_SoggScr_Braccio1() {
        return (ViewLinkImpl) findViewLink("Ref_SoggScr_Braccio1");
    }

    /**
     * Container's getter for Cnf_SoCnfTrialStatoView1.
     * @return Cnf_SoCnfTrialStatoView1
     */
    public Cnf_SoCnfTrialStatoViewImpl getCnf_SoCnfTrialStatoView1() {
        return (Cnf_SoCnfTrialStatoViewImpl) findViewObject("Cnf_SoCnfTrialStatoView1");
    }

    /**
     * Container's getter for Ref_SoggScr_Stato1.
     * @return Ref_SoggScr_Stato1
     */
    public ViewLinkImpl getRef_SoggScr_Stato1() {
        return (ViewLinkImpl) findViewLink("Ref_SoggScr_Stato1");
    }

    /**
     * Container's getter for Ref_SoCnfRef2livHPVES2View1.
     * @return Ref_SoCnfRef2livHPVES2View1
     */
    public Ref_SoCnfRef2livHPVES2ViewImpl getRef_SoCnfRef2livHPVES2View1() {
        return (Ref_SoCnfRef2livHPVES2ViewImpl) findViewObject("Ref_SoCnfRef2livHPVES2View1");
    }

    /**
     * Container's getter for A_SelTrialBraccioView1.
     * @return A_SelTrialBraccioView1
     */
    public A_SelTrialBraccioViewImpl getA_SelTrialBraccioView1() {
        return (A_SelTrialBraccioViewImpl) findViewObject("A_SelTrialBraccioView1");
    }

    /**
     * Container's getter for A_SelTrialStatoView1.
     * @return A_SelTrialStatoView1
     */
    public A_SelTrialStatoViewImpl getA_SelTrialStatoView1() {
        return (A_SelTrialStatoViewImpl) findViewObject("A_SelTrialStatoView1");
    }

    /**
     * Container's getter for Ref_SelTipiDocView1.
     * @return Ref_SelTipiDocView1
     */
    public Ref_SelTipiDocViewImpl getRef_SelTipiDocView1() {
        return (Ref_SelTipiDocViewImpl) findViewObject("Ref_SelTipiDocView1");
    }

    /**
     * Container's getter for Ref_SoCnfSuggCrit1livCitoView1.
     * @return Ref_SoCnfSuggCrit1livCitoView1
     */
    public Ref_SoCnfSuggCrit1livCitoViewImpl getRef_SoCnfSuggCrit1livCitoView1() {
        return (Ref_SoCnfSuggCrit1livCitoViewImpl) findViewObject("Ref_SoCnfSuggCrit1livCitoView1");
    }
}
