package model.impexp;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class Impexp_SoCodaProcessiViewImpl extends ViewObjectImpl {
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public Impexp_SoCodaProcessiViewImpl()
  {
  }


	/**
	 * Returns the bind variable value for PidNew.
	 * @return bind variable value for PidNew
	 */
	public Integer getPidNew() {
		return (Integer)getNamedWhereClauseParam("PidNew");
	}

	/**
	 * Sets <code>value</code> for bind variable PidNew.
	 * @param value value to bind as PidNew
	 */
	public void setPidNew(Integer value) {
		setNamedWhereClauseParam("PidNew", value);
	}
}
