package model.round;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class Round_SoDistrettoZonaImpl extends EntityImpl {


    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
		Coddistrzona {
			public Object get(Round_SoDistrettoZonaImpl obj) {
				return obj.getCoddistrzona();
			}

			public void put(Round_SoDistrettoZonaImpl obj, Object value) {
				obj.setCoddistrzona((Integer)value);
			}
		}
		,
		Descrizione {
			public Object get(Round_SoDistrettoZonaImpl obj) {
				return obj.getDescrizione();
			}

			public void put(Round_SoDistrettoZonaImpl obj, Object value) {
				obj.setDescrizione((String)value);
			}
		}
		,
		Ulss {
			public Object get(Round_SoDistrettoZonaImpl obj) {
				return obj.getUlss();
			}

			public void put(Round_SoDistrettoZonaImpl obj, Object value) {
				obj.setUlss((String)value);
			}
		}
		,
		Cnf_SoCnfDistrzona {
			public Object get(Round_SoDistrettoZonaImpl obj) {
				return obj.getCnf_SoCnfDistrzona();
			}

			public void put(Round_SoDistrettoZonaImpl obj, Object value) {
				obj.setAttributeInternal(index(), value);
			}
		}
		;
		private static AttributesEnum[] vals = null;
		private static int firstIndex = 0;

        public abstract Object get(Round_SoDistrettoZonaImpl object);

        public abstract void put(Round_SoDistrettoZonaImpl object, Object value);

        public int index() {
            return Round_SoDistrettoZonaImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return Round_SoDistrettoZonaImpl.AttributesEnum.firstIndex() + Round_SoDistrettoZonaImpl.AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = Round_SoDistrettoZonaImpl.AttributesEnum.values();
            }
            return vals;
        }
    }

	public static final int CODDISTRZONA = AttributesEnum.Coddistrzona.index();
	public static final int DESCRIZIONE = AttributesEnum.Descrizione.index();
	public static final int ULSS = AttributesEnum.Ulss.index();
	public static final int CNF_SOCNFDISTRZONA = AttributesEnum.Cnf_SoCnfDistrzona.index();

	/**
	 *
	 *  This is the default constructor (do not remove)
	 */
  public Round_SoDistrettoZonaImpl()
  {
  }


	/**
	 * @return the definition object for this instance class.
	 */
	public static synchronized EntityDefImpl getDefinitionObject() {
		return EntityDefImpl.findDefObject("model.round.Round_SoDistrettoZona");
	}

	/**
	 *
	 *  Gets the attribute value for Coddistrzona, using the alias name Coddistrzona
	 */
    public Integer getCoddistrzona()
  {
    return (Integer)getAttributeInternal(CODDISTRZONA);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Coddistrzona
   */
  public void setCoddistrzona(Integer value)
  {
    setAttributeInternal(CODDISTRZONA, value);
  }





  /**
   * 
   *  Gets the attribute value for Descrizione, using the alias name Descrizione
   */
  public String getDescrizione()
  {
    return (String)getAttributeInternal(DESCRIZIONE);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Descrizione
   */
  public void setDescrizione(String value)
  {
    setAttributeInternal(DESCRIZIONE, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
		if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
			return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
		}
		return super.getAttrInvokeAccessor(index, attrDef);
	}

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
		if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
			AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
			return;
		}
		super.setAttrInvokeAccessor(index, value, attrDef);
	}


  /**
   * 
   *  Gets the attribute value for Ulss, using the alias name Ulss
   */
  public String getUlss()
  {
    return (String)getAttributeInternal(ULSS);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Ulss
   */
  public void setUlss(String value)
  {
    setAttributeInternal(ULSS, value);
  }




  /**
   *
   *  Gets the associated entity oracle.jbo.RowIterator
   */
    public RowIterator getCnf_SoCnfDistrzona()
  {
        return (RowIterator)getAttributeInternal(CNF_SOCNFDISTRZONA);
    }

	/**
	 * @param coddistrzona key constituent
	 * @param ulss key constituent

	 * @return a Key object based on given key constituents.
	 */
	public static Key createPrimaryKey(Integer coddistrzona, String ulss) {
		return new Key(new Object[]{coddistrzona, ulss});
	}


}
