package model.round;

import model.conf.Cnf_SoCentroPrelRefImpl;
import model.conf.Cnf_SoDistrettoZonaImpl;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.Key;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class Round_SoCnfDistrzonaImpl extends EntityImpl {


    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Idcnf {
            public Object get(Round_SoCnfDistrzonaImpl obj) {
                return obj.getIdcnf();
            }

            public void put(Round_SoCnfDistrzonaImpl obj, Object value) {
                obj.setIdcnf((Integer)value);
            }
        }
        ,
        Coddistrzona {
            public Object get(Round_SoCnfDistrzonaImpl obj) {
                return obj.getCoddistrzona();
            }

            public void put(Round_SoCnfDistrzonaImpl obj, Object value) {
                obj.setCoddistrzona((Integer)value);
            }
        }
        ,
        Idcentro1liv {
            public Object get(Round_SoCnfDistrzonaImpl obj) {
                return obj.getIdcentro1liv();
            }

            public void put(Round_SoCnfDistrzonaImpl obj, Object value) {
                obj.setIdcentro1liv((Integer)value);
            }
        }
        ,
        Idcentro2liv {
            public Object get(Round_SoCnfDistrzonaImpl obj) {
                return obj.getIdcentro2liv();
            }

            public void put(Round_SoCnfDistrzonaImpl obj, Object value) {
                obj.setIdcentro2liv((Integer)value);
            }
        }
        ,
        Tpscr {
            public Object get(Round_SoCnfDistrzonaImpl obj) {
                return obj.getTpscr();
            }

            public void put(Round_SoCnfDistrzonaImpl obj, Object value) {
                obj.setTpscr((String)value);
            }
        }
        ,
        Ulss {
            public Object get(Round_SoCnfDistrzonaImpl obj) {
                return obj.getUlss();
            }

            public void put(Round_SoCnfDistrzonaImpl obj, Object value) {
                obj.setUlss((String)value);
            }
        }
        ,
        Cnf_SoCentroPrelRef {
            public Object get(Round_SoCnfDistrzonaImpl obj) {
                return obj.getCnf_SoCentroPrelRef();
            }

            public void put(Round_SoCnfDistrzonaImpl obj, Object value) {
                obj.setCnf_SoCentroPrelRef((Cnf_SoCentroPrelRefImpl)value);
            }
        }
        ,
        Cnf_SoCentroPrelRef1 {
            public Object get(Round_SoCnfDistrzonaImpl obj) {
                return obj.getCnf_SoCentroPrelRef1();
            }

            public void put(Round_SoCnfDistrzonaImpl obj, Object value) {
                obj.setCnf_SoCentroPrelRef1((Cnf_SoCentroPrelRefImpl)value);
            }
        }
        ,
        Cnf_SoDistrettoZona {
            public Object get(Round_SoCnfDistrzonaImpl obj) {
                return obj.getCnf_SoDistrettoZona();
            }

            public void put(Round_SoCnfDistrzonaImpl obj, Object value) {
                obj.setCnf_SoDistrettoZona((Cnf_SoDistrettoZonaImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(Round_SoCnfDistrzonaImpl object);

        public abstract void put(Round_SoCnfDistrzonaImpl object, Object value);

        public int index() {
            return Round_SoCnfDistrzonaImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return Round_SoCnfDistrzonaImpl.AttributesEnum.firstIndex() + Round_SoCnfDistrzonaImpl.AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = Round_SoCnfDistrzonaImpl.AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int IDCNF = AttributesEnum.Idcnf.index();
    public static final int CODDISTRZONA = AttributesEnum.Coddistrzona.index();
    public static final int IDCENTRO1LIV = AttributesEnum.Idcentro1liv.index();
    public static final int IDCENTRO2LIV = AttributesEnum.Idcentro2liv.index();
    public static final int TPSCR = AttributesEnum.Tpscr.index();
    public static final int ULSS = AttributesEnum.Ulss.index();
    public static final int CNF_SOCENTROPRELREF = AttributesEnum.Cnf_SoCentroPrelRef.index();
    public static final int CNF_SOCENTROPRELREF1 = AttributesEnum.Cnf_SoCentroPrelRef1.index();
    public static final int CNF_SODISTRETTOZONA = AttributesEnum.Cnf_SoDistrettoZona.index();

    /**
     *
     *  This is the default constructor (do not remove)
     */
  public Round_SoCnfDistrzonaImpl()
  {
  }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.round.Round_SoCnfDistrzona");
    }

    /**
     *
     *  Gets the attribute value for Idcnf, using the alias name Idcnf
     */
    public Integer getIdcnf()
  {
    return (Integer)getAttributeInternal(IDCNF);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idcnf
   */
  public void setIdcnf(Integer value)
  {
    setAttributeInternal(IDCNF, value);
  }

  /**
   * 
   *  Gets the attribute value for Coddistrzona, using the alias name Coddistrzona
   */
  public Integer getCoddistrzona()
  {
    return (Integer)getAttributeInternal(CODDISTRZONA);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Coddistrzona
   */
  public void setCoddistrzona(Integer value)
  {
    setAttributeInternal(CODDISTRZONA, value);
  }

  /**
   * 
   *  Gets the attribute value for Idcentro1liv, using the alias name Idcentro1liv
   */
  public Integer getIdcentro1liv()
  {
    return (Integer)getAttributeInternal(IDCENTRO1LIV);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idcentro1liv
   */
  public void setIdcentro1liv(Integer value)
  {
    setAttributeInternal(IDCENTRO1LIV, value);
  }

  /**
   * 
   *  Gets the attribute value for Idcentro2liv, using the alias name Idcentro2liv
   */
  public Integer getIdcentro2liv()
  {
    return (Integer)getAttributeInternal(IDCENTRO2LIV);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idcentro2liv
   */
  public void setIdcentro2liv(Integer value)
  {
    setAttributeInternal(IDCENTRO2LIV, value);
  }

  /**
   * 
   *  Gets the attribute value for Tpscr, using the alias name Tpscr
   */
  public String getTpscr()
  {
    return (String)getAttributeInternal(TPSCR);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Tpscr
   */
  public void setTpscr(String value)
  {
    setAttributeInternal(TPSCR, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }



  /**
     *
     *  Gets the associated entity Cnf_SoCentroPrelRefImpl
     */
    public Cnf_SoCentroPrelRefImpl getCnf_SoCentroPrelRef()
  {
    return (Cnf_SoCentroPrelRefImpl)getAttributeInternal(CNF_SOCENTROPRELREF);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity Cnf_SoCentroPrelRefImpl
   */
  public void setCnf_SoCentroPrelRef(Cnf_SoCentroPrelRefImpl value)
  {
    setAttributeInternal(CNF_SOCENTROPRELREF, value);
  }

  /**
     *
     *  Gets the associated entity Cnf_SoCentroPrelRefImpl
     */
    public Cnf_SoCentroPrelRefImpl getCnf_SoCentroPrelRef1()
  {
    return (Cnf_SoCentroPrelRefImpl)getAttributeInternal(CNF_SOCENTROPRELREF1);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity Cnf_SoCentroPrelRefImpl
   */
  public void setCnf_SoCentroPrelRef1(Cnf_SoCentroPrelRefImpl value)
  {
    setAttributeInternal(CNF_SOCENTROPRELREF1, value);
  }

  /**
     *
     *  Gets the associated entity Cnf_SoDistrettoZonaImpl
     */
    public Cnf_SoDistrettoZonaImpl getCnf_SoDistrettoZona()
  {
    return (Cnf_SoDistrettoZonaImpl)getAttributeInternal(CNF_SODISTRETTOZONA);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity Cnf_SoDistrettoZonaImpl
   */
  public void setCnf_SoDistrettoZona(Cnf_SoDistrettoZonaImpl value)
  {
    setAttributeInternal(CNF_SODISTRETTOZONA, value);
  }


    /**
     * @param idcnf key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer idcnf) {
        return new Key(new Object[]{idcnf});
    }

    /**
     *
     *  Gets the attribute value for Ulss, using the alias name Ulss
     */
  public String getUlss()
  {
    return (String)getAttributeInternal(ULSS);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Ulss
   */
  public void setUlss(String value)
  {
    setAttributeInternal(ULSS, value);
  }


}
