package model.accettazione;

import java.math.BigDecimal;

import model.conf.Cnf_SoCnfAnagRegImpl;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class AccCa_SoInvitoImpl extends EntityImpl {


    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Idinvito,
        Codts,
        Idtpinvito,
        Codesitoinvito,
        Livesito,
        Attivo,
        Idcentroprelievo,
        Idcentrorichiamo,
        Idcentroref1liv,
        Idcentroref2liv,
        Idapp,
        Dtapp,
        Oraapp,
        Minapp,
        Dtappiniziale,
        Consenso,
        Dtesamerecente,
        Dtrichiamo,
        Dtinviorichiamo,
        Opmedico,
        Dtinviosollecito,
        Roundcomune,
        Roundindiv,
        Volontaria,
        Dtblocco,
        Chiusuraroundindiv,
        Dtultimamod,
        Dtcreazione,
        Opinserimento,
        Dtmodesclusione,
        Opmodifica,
        Fuorifascia,
        Noteinvito,
        Ulss,
        Tpscr,
        Roundinviti,
        Tprichiamo,
        Livello,
        Idostetrica,
        Codresidenza,
        Coddomicilio,
        Viaresidenza,
        Viadomicilio,
        Statoanag,
        Zona,
        Dtritcont,
        Dtconscont,
        DaConfermare,
        NonSpedireReferto,
        RaccLettInvito,
        RaccLettReferto,
        TestProposto,
        RoundindivHpv,
        ReleaseCodeComRes,
        ReleaseCodeComDom,
        Otp,
        Confermato,
        NoteCittadino,
        Exulss,
        NoteAcc,
        Cnf_SoCnfAnagReg,
        A_SoAccPfas2liv;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDINVITO = AttributesEnum.Idinvito.index();
    public static final int CODTS = AttributesEnum.Codts.index();
    public static final int IDTPINVITO = AttributesEnum.Idtpinvito.index();
    public static final int CODESITOINVITO = AttributesEnum.Codesitoinvito.index();
    public static final int LIVESITO = AttributesEnum.Livesito.index();
    public static final int ATTIVO = AttributesEnum.Attivo.index();
    public static final int IDCENTROPRELIEVO = AttributesEnum.Idcentroprelievo.index();
    public static final int IDCENTRORICHIAMO = AttributesEnum.Idcentrorichiamo.index();
    public static final int IDCENTROREF1LIV = AttributesEnum.Idcentroref1liv.index();
    public static final int IDCENTROREF2LIV = AttributesEnum.Idcentroref2liv.index();
    public static final int IDAPP = AttributesEnum.Idapp.index();
    public static final int DTAPP = AttributesEnum.Dtapp.index();
    public static final int ORAAPP = AttributesEnum.Oraapp.index();
    public static final int MINAPP = AttributesEnum.Minapp.index();
    public static final int DTAPPINIZIALE = AttributesEnum.Dtappiniziale.index();
    public static final int CONSENSO = AttributesEnum.Consenso.index();
    public static final int DTESAMERECENTE = AttributesEnum.Dtesamerecente.index();
    public static final int DTRICHIAMO = AttributesEnum.Dtrichiamo.index();
    public static final int DTINVIORICHIAMO = AttributesEnum.Dtinviorichiamo.index();
    public static final int OPMEDICO = AttributesEnum.Opmedico.index();
    public static final int DTINVIOSOLLECITO = AttributesEnum.Dtinviosollecito.index();
    public static final int ROUNDCOMUNE = AttributesEnum.Roundcomune.index();
    public static final int ROUNDINDIV = AttributesEnum.Roundindiv.index();
    public static final int VOLONTARIA = AttributesEnum.Volontaria.index();
    public static final int DTBLOCCO = AttributesEnum.Dtblocco.index();
    public static final int CHIUSURAROUNDINDIV = AttributesEnum.Chiusuraroundindiv.index();
    public static final int DTULTIMAMOD = AttributesEnum.Dtultimamod.index();
    public static final int DTCREAZIONE = AttributesEnum.Dtcreazione.index();
    public static final int OPINSERIMENTO = AttributesEnum.Opinserimento.index();
    public static final int DTMODESCLUSIONE = AttributesEnum.Dtmodesclusione.index();
    public static final int OPMODIFICA = AttributesEnum.Opmodifica.index();
    public static final int FUORIFASCIA = AttributesEnum.Fuorifascia.index();
    public static final int NOTEINVITO = AttributesEnum.Noteinvito.index();
    public static final int ULSS = AttributesEnum.Ulss.index();
    public static final int TPSCR = AttributesEnum.Tpscr.index();
    public static final int ROUNDINVITI = AttributesEnum.Roundinviti.index();
    public static final int TPRICHIAMO = AttributesEnum.Tprichiamo.index();
    public static final int LIVELLO = AttributesEnum.Livello.index();
    public static final int IDOSTETRICA = AttributesEnum.Idostetrica.index();
    public static final int CODRESIDENZA = AttributesEnum.Codresidenza.index();
    public static final int CODDOMICILIO = AttributesEnum.Coddomicilio.index();
    public static final int VIARESIDENZA = AttributesEnum.Viaresidenza.index();
    public static final int VIADOMICILIO = AttributesEnum.Viadomicilio.index();
    public static final int STATOANAG = AttributesEnum.Statoanag.index();
    public static final int ZONA = AttributesEnum.Zona.index();
    public static final int DTRITCONT = AttributesEnum.Dtritcont.index();
    public static final int DTCONSCONT = AttributesEnum.Dtconscont.index();
    public static final int DACONFERMARE = AttributesEnum.DaConfermare.index();
    public static final int NONSPEDIREREFERTO = AttributesEnum.NonSpedireReferto.index();
    public static final int RACCLETTINVITO = AttributesEnum.RaccLettInvito.index();
    public static final int RACCLETTREFERTO = AttributesEnum.RaccLettReferto.index();
    public static final int TESTPROPOSTO = AttributesEnum.TestProposto.index();
    public static final int ROUNDINDIVHPV = AttributesEnum.RoundindivHpv.index();
    public static final int RELEASECODECOMRES = AttributesEnum.ReleaseCodeComRes.index();
    public static final int RELEASECODECOMDOM = AttributesEnum.ReleaseCodeComDom.index();
    public static final int OTP = AttributesEnum.Otp.index();
    public static final int CONFERMATO = AttributesEnum.Confermato.index();
    public static final int NOTECITTADINO = AttributesEnum.NoteCittadino.index();
    public static final int EXULSS = AttributesEnum.Exulss.index();
    public static final int NOTEACC = AttributesEnum.NoteAcc.index();
    public static final int CNF_SOCNFANAGREG = AttributesEnum.Cnf_SoCnfAnagReg.index();
    public static final int A_SOACCPFAS2LIV = AttributesEnum.A_SoAccPfas2liv.index();

    /**
     *
     *  This is the default constructor (do not remove)
     */
  public AccCa_SoInvitoImpl()
  {
  }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.accettazione.AccCa_SoInvito");
    }


    /**
     *
     *  Gets the attribute value for Idinvito, using the alias name Idinvito
     */
  public Integer getIdinvito()
  {
    return (Integer)getAttributeInternal(IDINVITO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idinvito
   */
  public void setIdinvito(Integer value)
  {
    setAttributeInternal(IDINVITO, value);
  }

  /**
   * 
   *  Gets the attribute value for Codts, using the alias name Codts
   */
  public String getCodts()
  {
    return (String)getAttributeInternal(CODTS);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Codts
   */
  public void setCodts(String value)
  {
    setAttributeInternal(CODTS, value);
  }

  /**
   * 
   *  Gets the attribute value for Idtpinvito, using the alias name Idtpinvito
   */
  public String getIdtpinvito()
  {
    return (String)getAttributeInternal(IDTPINVITO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idtpinvito
   */
  public void setIdtpinvito(String value)
  {
    setAttributeInternal(IDTPINVITO, value);
  }

  /**
   * 
   *  Gets the attribute value for Codesitoinvito, using the alias name Codesitoinvito
   */
  public String getCodesitoinvito()
  {
    return (String)getAttributeInternal(CODESITOINVITO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Codesitoinvito
   */
  public void setCodesitoinvito(String value)
  {
    setAttributeInternal(CODESITOINVITO, value);
  }

  /**
   * 
   *  Gets the attribute value for Livesito, using the alias name Livesito
   */
  public Integer getLivesito()
  {
    return (Integer)getAttributeInternal(LIVESITO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Livesito
   */
  public void setLivesito(Integer value)
  {
    setAttributeInternal(LIVESITO, value);
  }

  /**
     *
     *  Gets the attribute value for Attivo, using the alias name Attivo
     */
    public BigDecimal getAttivo()
  {
        return (BigDecimal) getAttributeInternal(ATTIVO);
    }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Attivo
   */
  public void setAttivo(BigDecimal value)
  {
    setAttributeInternal(ATTIVO, value);
  }

  /**
   * 
   *  Gets the attribute value for Idcentroprelievo, using the alias name Idcentroprelievo
   */
  public Integer getIdcentroprelievo()
  {
    return (Integer)getAttributeInternal(IDCENTROPRELIEVO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idcentroprelievo
   */
  public void setIdcentroprelievo(Integer value)
  {
    setAttributeInternal(IDCENTROPRELIEVO, value);
  }

  /**
   * 
   *  Gets the attribute value for Idcentrorichiamo, using the alias name Idcentrorichiamo
   */
  public Integer getIdcentrorichiamo()
  {
    return (Integer)getAttributeInternal(IDCENTRORICHIAMO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idcentrorichiamo
   */
  public void setIdcentrorichiamo(Integer value)
  {
    setAttributeInternal(IDCENTRORICHIAMO, value);
  }

  /**
   * 
   *  Gets the attribute value for Idcentroref1liv, using the alias name Idcentroref1liv
   */
  public Integer getIdcentroref1liv()
  {
    return (Integer)getAttributeInternal(IDCENTROREF1LIV);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idcentroref1liv
   */
  public void setIdcentroref1liv(Integer value)
  {
    setAttributeInternal(IDCENTROREF1LIV, value);
  }

  /**
   * 
   *  Gets the attribute value for Idcentroref2liv, using the alias name Idcentroref2liv
   */
  public Integer getIdcentroref2liv()
  {
    return (Integer)getAttributeInternal(IDCENTROREF2LIV);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idcentroref2liv
   */
  public void setIdcentroref2liv(Integer value)
  {
    setAttributeInternal(IDCENTROREF2LIV, value);
  }

  /**
   * 
   *  Gets the attribute value for Idapp, using the alias name Idapp
   */
  public Integer getIdapp()
  {
    return (Integer)getAttributeInternal(IDAPP);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idapp
   */
  public void setIdapp(Integer value)
  {
    setAttributeInternal(IDAPP, value);
  }

  /**
   * 
   *  Gets the attribute value for Dtapp, using the alias name Dtapp
   */
  public Date getDtapp()
  {
    return (Date)getAttributeInternal(DTAPP);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Dtapp
   */
  public void setDtapp(Date value)
  {
    setAttributeInternal(DTAPP, value);
  }

  /**
   * 
   *  Gets the attribute value for Oraapp, using the alias name Oraapp
   */
  public Integer getOraapp()
  {
    return (Integer)getAttributeInternal(ORAAPP);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Oraapp
   */
  public void setOraapp(Integer value)
  {
    setAttributeInternal(ORAAPP, value);
  }

  /**
   * 
   *  Gets the attribute value for Minapp, using the alias name Minapp
   */
  public Integer getMinapp()
  {
    return (Integer)getAttributeInternal(MINAPP);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Minapp
   */
  public void setMinapp(Integer value)
  {
    setAttributeInternal(MINAPP, value);
  }

  /**
   * 
   *  Gets the attribute value for Dtappiniziale, using the alias name Dtappiniziale
   */
  public Date getDtappiniziale()
  {
    return (Date)getAttributeInternal(DTAPPINIZIALE);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Dtappiniziale
   */
  public void setDtappiniziale(Date value)
  {
    setAttributeInternal(DTAPPINIZIALE, value);
  }

  /**
     *
     *  Gets the attribute value for Consenso, using the alias name Consenso
     */
    public BigDecimal getConsenso()
  {
        return (BigDecimal) getAttributeInternal(CONSENSO);
    }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Consenso
   */
  public void setConsenso(BigDecimal value)
  {
    setAttributeInternal(CONSENSO, value);
  }

  /**
   * 
   *  Gets the attribute value for Dtesamerecente, using the alias name Dtesamerecente
   */
  public Date getDtesamerecente()
  {
    return (Date)getAttributeInternal(DTESAMERECENTE);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Dtesamerecente
   */
  public void setDtesamerecente(Date value)
  {
    setAttributeInternal(DTESAMERECENTE, value);
  }

  /**
   * 
   *  Gets the attribute value for Dtrichiamo, using the alias name Dtrichiamo
   */
  public Date getDtrichiamo()
  {
    return (Date)getAttributeInternal(DTRICHIAMO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Dtrichiamo
   */
  public void setDtrichiamo(Date value)
  {
    setAttributeInternal(DTRICHIAMO, value);
  }

  /**
   * 
   *  Gets the attribute value for Dtinviorichiamo, using the alias name Dtinviorichiamo
   */
  public Date getDtinviorichiamo()
  {
    return (Date)getAttributeInternal(DTINVIORICHIAMO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Dtinviorichiamo
   */
  public void setDtinviorichiamo(Date value)
  {
    setAttributeInternal(DTINVIORICHIAMO, value);
  }

  /**
   * 
   *  Gets the attribute value for Opmedico, using the alias name Opmedico
   */
  public String getOpmedico()
  {
    return (String)getAttributeInternal(OPMEDICO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Opmedico
   */
  public void setOpmedico(String value)
  {
    setAttributeInternal(OPMEDICO, value);
  }

  /**
   * 
   *  Gets the attribute value for Dtinviosollecito, using the alias name Dtinviosollecito
   */
  public Date getDtinviosollecito()
  {
    return (Date)getAttributeInternal(DTINVIOSOLLECITO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Dtinviosollecito
   */
  public void setDtinviosollecito(Date value)
  {
    setAttributeInternal(DTINVIOSOLLECITO, value);
  }

  /**
   * 
   *  Gets the attribute value for Roundcomune, using the alias name Roundcomune
   */
  public Integer getRoundcomune()
  {
    return (Integer)getAttributeInternal(ROUNDCOMUNE);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Roundcomune
   */
  public void setRoundcomune(Integer value)
  {
    setAttributeInternal(ROUNDCOMUNE, value);
  }

  /**
   * 
   *  Gets the attribute value for Roundindiv, using the alias name Roundindiv
   */
  public Integer getRoundindiv()
  {
    return (Integer)getAttributeInternal(ROUNDINDIV);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Roundindiv
   */
  public void setRoundindiv(Integer value)
  {
    setAttributeInternal(ROUNDINDIV, value);
  }

  /**
     *
     *  Gets the attribute value for Volontaria, using the alias name Volontaria
     */
    public BigDecimal getVolontaria()
  {
        return (BigDecimal) getAttributeInternal(VOLONTARIA);
    }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Volontaria
   */
  public void setVolontaria(BigDecimal value)
  {
    setAttributeInternal(VOLONTARIA, value);
  }

  /**
   * 
   *  Gets the attribute value for Dtblocco, using the alias name Dtblocco
   */
  public Date getDtblocco()
  {
    return (Date)getAttributeInternal(DTBLOCCO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Dtblocco
   */
  public void setDtblocco(Date value)
  {
    setAttributeInternal(DTBLOCCO, value);
  }

  /**
     *
     *  Gets the attribute value for Chiusuraroundindiv, using the alias name Chiusuraroundindiv
     */
    public BigDecimal getChiusuraroundindiv()
  {
        return (BigDecimal) getAttributeInternal(CHIUSURAROUNDINDIV);
    }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Chiusuraroundindiv
   */
  public void setChiusuraroundindiv(BigDecimal value)
  {
    setAttributeInternal(CHIUSURAROUNDINDIV, value);
  }

  /**
   * 
   *  Gets the attribute value for Dtultimamod, using the alias name Dtultimamod
   */
  public Date getDtultimamod()
  {
    return (Date)getAttributeInternal(DTULTIMAMOD);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Dtultimamod
   */
  public void setDtultimamod(Date value)
  {
    setAttributeInternal(DTULTIMAMOD, value);
  }

  /**
   * 
   *  Gets the attribute value for Dtcreazione, using the alias name Dtcreazione
   */
  public Date getDtcreazione()
  {
    return (Date)getAttributeInternal(DTCREAZIONE);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Dtcreazione
   */
  public void setDtcreazione(Date value)
  {
    setAttributeInternal(DTCREAZIONE, value);
  }

  /**
   * 
   *  Gets the attribute value for Opinserimento, using the alias name Opinserimento
   */
  public String getOpinserimento()
  {
    return (String)getAttributeInternal(OPINSERIMENTO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Opinserimento
   */
  public void setOpinserimento(String value)
  {
    setAttributeInternal(OPINSERIMENTO, value);
  }

  /**
   * 
   *  Gets the attribute value for Dtmodesclusione, using the alias name Dtmodesclusione
   */
  public Date getDtmodesclusione()
  {
    return (Date)getAttributeInternal(DTMODESCLUSIONE);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Dtmodesclusione
   */
  public void setDtmodesclusione(Date value)
  {
    setAttributeInternal(DTMODESCLUSIONE, value);
  }

  /**
   * 
   *  Gets the attribute value for Opmodifica, using the alias name Opmodifica
   */
  public String getOpmodifica()
  {
    return (String)getAttributeInternal(OPMODIFICA);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Opmodifica
   */
  public void setOpmodifica(String value)
  {
    setAttributeInternal(OPMODIFICA, value);
  }

  /**
     *
     *  Gets the attribute value for Fuorifascia, using the alias name Fuorifascia
     */
    public BigDecimal getFuorifascia()
  {
        return (BigDecimal) getAttributeInternal(FUORIFASCIA);
    }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Fuorifascia
   */
  public void setFuorifascia(BigDecimal value)
  {
    setAttributeInternal(FUORIFASCIA, value);
  }

  /**
   * 
   *  Gets the attribute value for Noteinvito, using the alias name Noteinvito
   */
  public String getNoteinvito()
  {
    return (String)getAttributeInternal(NOTEINVITO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Noteinvito
   */
  public void setNoteinvito(String value)
  {
    setAttributeInternal(NOTEINVITO, value);
  }

  /**
   * 
   *  Gets the attribute value for Ulss, using the alias name Ulss
   */
  public String getUlss()
  {
    return (String)getAttributeInternal(ULSS);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Ulss
   */
  public void setUlss(String value)
  {
    setAttributeInternal(ULSS, value);
  }

  /**
   * 
   *  Gets the attribute value for Tpscr, using the alias name Tpscr
   */
  public String getTpscr()
  {
    return (String)getAttributeInternal(TPSCR);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Tpscr
   */
  public void setTpscr(String value)
  {
    setAttributeInternal(TPSCR, value);
  }

  /**
   * 
   *  Gets the attribute value for Roundinviti, using the alias name Roundinviti
   */
  public Integer getRoundinviti()
  {
    return (Integer)getAttributeInternal(ROUNDINVITI);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Roundinviti
   */
  public void setRoundinviti(Integer value)
  {
    setAttributeInternal(ROUNDINVITI, value);
  }

  /**
   * 
   *  Gets the attribute value for Tprichiamo, using the alias name Tprichiamo
   */
  public String getTprichiamo()
  {
    return (String)getAttributeInternal(TPRICHIAMO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Tprichiamo
   */
  public void setTprichiamo(String value)
  {
    setAttributeInternal(TPRICHIAMO, value);
  }

  /**
   * 
   *  Gets the attribute value for Livello, using the alias name Livello
   */
  public Integer getLivello()
  {
    return (Integer)getAttributeInternal(LIVELLO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Livello
   */
  public void setLivello(Integer value)
  {
    setAttributeInternal(LIVELLO, value);
  }

  /**
   * 
   *  Gets the attribute value for Idostetrica, using the alias name Idostetrica
   */
  public Integer getIdostetrica()
  {
    return (Integer)getAttributeInternal(IDOSTETRICA);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idostetrica
   */
  public void setIdostetrica(Integer value)
  {
    setAttributeInternal(IDOSTETRICA, value);
  }

  /**
   * 
   *  Gets the attribute value for Codresidenza, using the alias name Codresidenza
   */
  public String getCodresidenza()
  {
    return (String)getAttributeInternal(CODRESIDENZA);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Codresidenza
   */
  public void setCodresidenza(String value)
  {
    setAttributeInternal(CODRESIDENZA, value);
  }

  /**
   * 
   *  Gets the attribute value for Coddomicilio, using the alias name Coddomicilio
   */
  public String getCoddomicilio()
  {
    return (String)getAttributeInternal(CODDOMICILIO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Coddomicilio
   */
  public void setCoddomicilio(String value)
  {
    setAttributeInternal(CODDOMICILIO, value);
  }

  /**
   * 
   *  Gets the attribute value for Viaresidenza, using the alias name Viaresidenza
   */
  public String getViaresidenza()
  {
    return (String)getAttributeInternal(VIARESIDENZA);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Viaresidenza
   */
  public void setViaresidenza(String value)
  {
    setAttributeInternal(VIARESIDENZA, value);
  }

  /**
   * 
   *  Gets the attribute value for Viadomicilio, using the alias name Viadomicilio
   */
  public String getViadomicilio()
  {
    return (String)getAttributeInternal(VIADOMICILIO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Viadomicilio
   */
  public void setViadomicilio(String value)
  {
    setAttributeInternal(VIADOMICILIO, value);
  }

  /**
   * 
   *  Gets the attribute value for Statoanag, using the alias name Statoanag
   */
  public Integer getStatoanag()
  {
    return (Integer)getAttributeInternal(STATOANAG);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Statoanag
   */
  public void setStatoanag(Integer value)
  {
    setAttributeInternal(STATOANAG, value);
  }

  /**
   * 
   *  Gets the attribute value for Zona, using the alias name Zona
   */
  public Integer getZona()
  {
    return (Integer)getAttributeInternal(ZONA);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Zona
   */
  public void setZona(Integer value)
  {
    setAttributeInternal(ZONA, value);
  }

  /**
   * 
   *  Gets the attribute value for Dtritcont, using the alias name Dtritcont
   */
  public Date getDtritcont()
  {
    return (Date)getAttributeInternal(DTRITCONT);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Dtritcont
   */
  public void setDtritcont(Date value)
  {
    setAttributeInternal(DTRITCONT, value);
  }

  /**
   * 
   *  Gets the attribute value for Dtconscont, using the alias name Dtconscont
   */
  public Date getDtconscont()
  {
    return (Date)getAttributeInternal(DTCONSCONT);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Dtconscont
   */
  public void setDtconscont(Date value)
  {
    setAttributeInternal(DTCONSCONT, value);
  }

  /**
   * 
   *  Gets the attribute value for DaConfermare, using the alias name DaConfermare
   */
  public Integer getDaConfermare()
  {
    return (Integer)getAttributeInternal(DACONFERMARE);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for DaConfermare
   */
  public void setDaConfermare(Integer value)
  {
    setAttributeInternal(DACONFERMARE, value);
  }

  /**
   * 
   *  Gets the attribute value for NonSpedireReferto, using the alias name NonSpedireReferto
   */
  public Integer getNonSpedireReferto()
  {
    return (Integer)getAttributeInternal(NONSPEDIREREFERTO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for NonSpedireReferto
   */
  public void setNonSpedireReferto(Integer value)
  {
    setAttributeInternal(NONSPEDIREREFERTO, value);
  }

  /**
   * 
   *  Gets the attribute value for RaccLettInvito, using the alias name RaccLettInvito
   */
  public Integer getRaccLettInvito()
  {
    return (Integer)getAttributeInternal(RACCLETTINVITO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for RaccLettInvito
   */
  public void setRaccLettInvito(Integer value)
  {
    setAttributeInternal(RACCLETTINVITO, value);
  }

  /**
   * 
   *  Gets the attribute value for RaccLettReferto, using the alias name RaccLettReferto
   */
  public Integer getRaccLettReferto()
  {
    return (Integer)getAttributeInternal(RACCLETTREFERTO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for RaccLettReferto
   */
  public void setRaccLettReferto(Integer value)
  {
    setAttributeInternal(RACCLETTREFERTO, value);
  }


    /**
     * Gets the attribute value for TestProposto, using the alias name TestProposto.
     * @return the value of TestProposto
     */
    public String getTestProposto() {
        return (String) getAttributeInternal(TESTPROPOSTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for TestProposto.
     * @param value value to set the TestProposto
     */
    public void setTestProposto(String value) {
        setAttributeInternal(TESTPROPOSTO, value);
    }

    /**
     * Gets the attribute value for RoundindivHpv, using the alias name RoundindivHpv.
     * @return the value of RoundindivHpv
     */
    public Integer getRoundindivHpv() {
        return (Integer) getAttributeInternal(ROUNDINDIVHPV);
    }

    /**
     * Sets <code>value</code> as the attribute value for RoundindivHpv.
     * @param value value to set the RoundindivHpv
     */
    public void setRoundindivHpv(Integer value) {
        setAttributeInternal(ROUNDINDIVHPV, value);
    }

    /**
     * Gets the attribute value for ReleaseCodeComRes, using the alias name ReleaseCodeComRes.
     * @return the value of ReleaseCodeComRes
     */
    public Integer getReleaseCodeComRes() {
        return (Integer) getAttributeInternal(RELEASECODECOMRES);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReleaseCodeComRes.
     * @param value value to set the ReleaseCodeComRes
     */
    public void setReleaseCodeComRes(Integer value) {
        setAttributeInternal(RELEASECODECOMRES, value);
    }

    /**
     * Gets the attribute value for ReleaseCodeComDom, using the alias name ReleaseCodeComDom.
     * @return the value of ReleaseCodeComDom
     */
    public Integer getReleaseCodeComDom() {
        return (Integer) getAttributeInternal(RELEASECODECOMDOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReleaseCodeComDom.
     * @param value value to set the ReleaseCodeComDom
     */
    public void setReleaseCodeComDom(Integer value) {
        setAttributeInternal(RELEASECODECOMDOM, value);
    }

    /**
     * Gets the attribute value for Otp, using the alias name Otp.
     * @return the value of Otp
     */
    public String getOtp() {
        return (String) getAttributeInternal(OTP);
    }

    /**
     * Sets <code>value</code> as the attribute value for Otp.
     * @param value value to set the Otp
     */
    public void setOtp(String value) {
        setAttributeInternal(OTP, value);
    }

    /**
     * Gets the attribute value for Confermato, using the alias name Confermato.
     * @return the value of Confermato
     */
    public Integer getConfermato() {
        return (Integer) getAttributeInternal(CONFERMATO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Confermato.
     * @param value value to set the Confermato
     */
    public void setConfermato(Integer value) {
        setAttributeInternal(CONFERMATO, value);
    }

    /**
     * Gets the attribute value for NoteCittadino, using the alias name NoteCittadino.
     * @return the value of NoteCittadino
     */
    public String getNoteCittadino() {
        return (String) getAttributeInternal(NOTECITTADINO);
    }

    /**
     * Sets <code>value</code> as the attribute value for NoteCittadino.
     * @param value value to set the NoteCittadino
     */
    public void setNoteCittadino(String value) {
        setAttributeInternal(NOTECITTADINO, value);
    }

    /**
     * Gets the attribute value for Exulss, using the alias name Exulss.
     * @return the value of Exulss
     */
    public String getExulss() {
        return (String) getAttributeInternal(EXULSS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Exulss.
     * @param value value to set the Exulss
     */
    public void setExulss(String value) {
        setAttributeInternal(EXULSS, value);
    }

    /**
     * Gets the attribute value for NoteAcc, using the alias name NoteAcc.
     * @return the value of NoteAcc
     */
    public String getNoteAcc() {
        return (String) getAttributeInternal(NOTEACC);
    }

    /**
     * Sets <code>value</code> as the attribute value for NoteAcc.
     * @param value value to set the NoteAcc
     */
    public void setNoteAcc(String value) {
        setAttributeInternal(NOTEACC, value);
    }

    /**
     *
     *  Gets the associated entity Cnf_SoCnfAnagRegImpl
     */
  public Cnf_SoCnfAnagRegImpl getCnf_SoCnfAnagReg()
  {
    return (Cnf_SoCnfAnagRegImpl)getAttributeInternal(CNF_SOCNFANAGREG);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity Cnf_SoCnfAnagRegImpl
   */
  public void setCnf_SoCnfAnagReg(Cnf_SoCnfAnagRegImpl value)
  {
    setAttributeInternal(CNF_SOCNFANAGREG, value);
  }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getA_SoAccPfas2liv() {
        return (EntityImpl) getAttributeInternal(A_SOACCPFAS2LIV);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setA_SoAccPfas2liv(EntityImpl value) {
        setAttributeInternal(A_SOACCPFAS2LIV, value);
    }

    /**
     * @param idinvito key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer idinvito) {
        return new Key(new Object[] { idinvito });
    }


}
