package model.accettazione;

import oracle.jbo.client.remote.RowImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class AccCa_SoInvitoViewRowClient extends RowImpl 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public AccCa_SoInvitoViewRowClient()
  {
  }

  public Integer getAttivo()
  {
    return (Integer)getAttribute("Attivo");
  }

  public Integer getChiusuraroundindiv()
  {
    return (Integer)getAttribute("Chiusuraroundindiv");
  }

  public String getCoddomicilio()
  {
    return (String)getAttribute("Coddomicilio");
  }

  public String getCodesitoinvito()
  {
    return (String)getAttribute("Codesitoinvito");
  }

  public String getCodresidenza()
  {
    return (String)getAttribute("Codresidenza");
  }

  public String getCodts()
  {
    return (String)getAttribute("Codts");
  }

  public Integer getConsenso()
  {
    return (Integer)getAttribute("Consenso");
  }

  public Integer getDaConfermare()
  {
    return (Integer)getAttribute("DaConfermare");
  }

  public oracle.jbo.domain.Date getDtapp()
  {
    return (oracle.jbo.domain.Date)getAttribute("Dtapp");
  }

  public oracle.jbo.domain.Date getDtappiniziale()
  {
    return (oracle.jbo.domain.Date)getAttribute("Dtappiniziale");
  }

  public oracle.jbo.domain.Date getDtblocco()
  {
    return (oracle.jbo.domain.Date)getAttribute("Dtblocco");
  }

  public oracle.jbo.domain.Date getDtconscont()
  {
    return (oracle.jbo.domain.Date)getAttribute("Dtconscont");
  }

  public oracle.jbo.domain.Date getDtcreazione()
  {
    return (oracle.jbo.domain.Date)getAttribute("Dtcreazione");
  }

  public oracle.jbo.domain.Date getDtesamerecente()
  {
    return (oracle.jbo.domain.Date)getAttribute("Dtesamerecente");
  }

  public oracle.jbo.domain.Date getDtinviorichiamo()
  {
    return (oracle.jbo.domain.Date)getAttribute("Dtinviorichiamo");
  }

  public oracle.jbo.domain.Date getDtinviosollecito()
  {
    return (oracle.jbo.domain.Date)getAttribute("Dtinviosollecito");
  }

  public oracle.jbo.domain.Date getDtmodesclusione()
  {
    return (oracle.jbo.domain.Date)getAttribute("Dtmodesclusione");
  }

  public oracle.jbo.domain.Date getDtrichiamo()
  {
    return (oracle.jbo.domain.Date)getAttribute("Dtrichiamo");
  }

  public oracle.jbo.domain.Date getDtritcont()
  {
    return (oracle.jbo.domain.Date)getAttribute("Dtritcont");
  }

  public oracle.jbo.domain.Date getDtultimamod()
  {
    return (oracle.jbo.domain.Date)getAttribute("Dtultimamod");
  }

  public Integer getFuorifascia()
  {
    return (Integer)getAttribute("Fuorifascia");
  }

  public Integer getIdapp()
  {
    return (Integer)getAttribute("Idapp");
  }

  public Integer getIdcentroprelievo()
  {
    return (Integer)getAttribute("Idcentroprelievo");
  }

  public Integer getIdcentroref1liv()
  {
    return (Integer)getAttribute("Idcentroref1liv");
  }

  public Integer getIdcentroref2liv()
  {
    return (Integer)getAttribute("Idcentroref2liv");
  }

  public Integer getIdcentrorichiamo()
  {
    return (Integer)getAttribute("Idcentrorichiamo");
  }

  public Integer getIdinvito()
  {
    return (Integer)getAttribute("Idinvito");
  }

  public Integer getIdostetrica()
  {
    return (Integer)getAttribute("Idostetrica");
  }

  public String getIdtpinvito()
  {
    return (String)getAttribute("Idtpinvito");
  }

  public Integer getLivello()
  {
    return (Integer)getAttribute("Livello");
  }

  public Integer getLivesito()
  {
    return (Integer)getAttribute("Livesito");
  }

  public Integer getMinapp()
  {
    return (Integer)getAttribute("Minapp");
  }

  public Integer getNonSpedireReferto()
  {
    return (Integer)getAttribute("NonSpedireReferto");
  }

  public String getNoteinvito()
  {
    return (String)getAttribute("Noteinvito");
  }

  public String getOpinserimento()
  {
    return (String)getAttribute("Opinserimento");
  }

  public String getOpmedico()
  {
    return (String)getAttribute("Opmedico");
  }

  public String getOpmodifica()
  {
    return (String)getAttribute("Opmodifica");
  }

  public Integer getOraapp()
  {
    return (Integer)getAttribute("Oraapp");
  }

  public Integer getRaccLettInvito()
  {
    return (Integer)getAttribute("RaccLettInvito");
  }

  public Integer getRaccLettReferto()
  {
    return (Integer)getAttribute("RaccLettReferto");
  }

  public Integer getRoundcomune()
  {
    return (Integer)getAttribute("Roundcomune");
  }

  public Integer getRoundindiv()
  {
    return (Integer)getAttribute("Roundindiv");
  }

  public Integer getRoundinviti()
  {
    return (Integer)getAttribute("Roundinviti");
  }

  public Integer getStatoanag()
  {
    return (Integer)getAttribute("Statoanag");
  }

  public String getTprichiamo()
  {
    return (String)getAttribute("Tprichiamo");
  }

  public String getTpscr()
  {
    return (String)getAttribute("Tpscr");
  }

  public String getUlss()
  {
    return (String)getAttribute("Ulss");
  }

  public String getViadomicilio()
  {
    return (String)getAttribute("Viadomicilio");
  }

  public String getViaresidenza()
  {
    return (String)getAttribute("Viaresidenza");
  }

  public Integer getVolontaria()
  {
    return (Integer)getAttribute("Volontaria");
  }

  public Integer getZona()
  {
    return (Integer)getAttribute("Zona");
  }

  public void setAttivo(Integer value)
  {
    setAttribute("Attivo", value);
  }

  public void setChiusuraroundindiv(Integer value)
  {
    setAttribute("Chiusuraroundindiv", value);
  }

  public void setCoddomicilio(String value)
  {
    setAttribute("Coddomicilio", value);
  }

  public void setCodesitoinvito(String value)
  {
    setAttribute("Codesitoinvito", value);
  }

  public void setCodresidenza(String value)
  {
    setAttribute("Codresidenza", value);
  }

  public void setCodts(String value)
  {
    setAttribute("Codts", value);
  }

  public void setConsenso(Integer value)
  {
    setAttribute("Consenso", value);
  }

  public void setDaConfermare(Integer value)
  {
    setAttribute("DaConfermare", value);
  }

  public void setDtapp(oracle.jbo.domain.Date value)
  {
    setAttribute("Dtapp", value);
  }

  public void setDtappiniziale(oracle.jbo.domain.Date value)
  {
    setAttribute("Dtappiniziale", value);
  }

  public void setDtblocco(oracle.jbo.domain.Date value)
  {
    setAttribute("Dtblocco", value);
  }

  public void setDtconscont(oracle.jbo.domain.Date value)
  {
    setAttribute("Dtconscont", value);
  }

  public void setDtcreazione(oracle.jbo.domain.Date value)
  {
    setAttribute("Dtcreazione", value);
  }

  public void setDtesamerecente(oracle.jbo.domain.Date value)
  {
    setAttribute("Dtesamerecente", value);
  }

  public void setDtinviorichiamo(oracle.jbo.domain.Date value)
  {
    setAttribute("Dtinviorichiamo", value);
  }

  public void setDtinviosollecito(oracle.jbo.domain.Date value)
  {
    setAttribute("Dtinviosollecito", value);
  }

  public void setDtmodesclusione(oracle.jbo.domain.Date value)
  {
    setAttribute("Dtmodesclusione", value);
  }

  public void setDtrichiamo(oracle.jbo.domain.Date value)
  {
    setAttribute("Dtrichiamo", value);
  }

  public void setDtritcont(oracle.jbo.domain.Date value)
  {
    setAttribute("Dtritcont", value);
  }

  public void setDtultimamod(oracle.jbo.domain.Date value)
  {
    setAttribute("Dtultimamod", value);
  }

  public void setFuorifascia(Integer value)
  {
    setAttribute("Fuorifascia", value);
  }

  public void setIdapp(Integer value)
  {
    setAttribute("Idapp", value);
  }

  public void setIdcentroprelievo(Integer value)
  {
    setAttribute("Idcentroprelievo", value);
  }

  public void setIdcentroref1liv(Integer value)
  {
    setAttribute("Idcentroref1liv", value);
  }

  public void setIdcentroref2liv(Integer value)
  {
    setAttribute("Idcentroref2liv", value);
  }

  public void setIdcentrorichiamo(Integer value)
  {
    setAttribute("Idcentrorichiamo", value);
  }

  public void setIdinvito(Integer value)
  {
    setAttribute("Idinvito", value);
  }

  public void setIdostetrica(Integer value)
  {
    setAttribute("Idostetrica", value);
  }

  public void setIdtpinvito(String value)
  {
    setAttribute("Idtpinvito", value);
  }

  public void setLivello(Integer value)
  {
    setAttribute("Livello", value);
  }

  public void setLivesito(Integer value)
  {
    setAttribute("Livesito", value);
  }

  public void setMinapp(Integer value)
  {
    setAttribute("Minapp", value);
  }

  public void setNonSpedireReferto(Integer value)
  {
    setAttribute("NonSpedireReferto", value);
  }

  public void setNoteinvito(String value)
  {
    setAttribute("Noteinvito", value);
  }

  public void setOpinserimento(String value)
  {
    setAttribute("Opinserimento", value);
  }

  public void setOpmedico(String value)
  {
    setAttribute("Opmedico", value);
  }

  public void setOpmodifica(String value)
  {
    setAttribute("Opmodifica", value);
  }

  public void setOraapp(Integer value)
  {
    setAttribute("Oraapp", value);
  }

  public void setRaccLettInvito(Integer value)
  {
    setAttribute("RaccLettInvito", value);
  }

  public void setRaccLettReferto(Integer value)
  {
    setAttribute("RaccLettReferto", value);
  }

  public void setRoundcomune(Integer value)
  {
    setAttribute("Roundcomune", value);
  }

  public void setRoundindiv(Integer value)
  {
    setAttribute("Roundindiv", value);
  }

  public void setRoundinviti(Integer value)
  {
    setAttribute("Roundinviti", value);
  }

  public void setStatoanag(Integer value)
  {
    setAttribute("Statoanag", value);
  }

  public void setTprichiamo(String value)
  {
    setAttribute("Tprichiamo", value);
  }

  public void setTpscr(String value)
  {
    setAttribute("Tpscr", value);
  }

  public void setUlss(String value)
  {
    setAttribute("Ulss", value);
  }

  public void setViadomicilio(String value)
  {
    setAttribute("Viadomicilio", value);
  }

  public void setViaresidenza(String value)
  {
    setAttribute("Viaresidenza", value);
  }

  public void setVolontaria(Integer value)
  {
    setAttribute("Volontaria", value);
  }

  public void setZona(Integer value)
  {
    setAttribute("Zona", value);
  }







































































































}