package model.accettazione;

import java.math.BigDecimal;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class AccPf_SoAccPfas1livViewRowImpl extends ViewRowImpl implements model.accettazione.AccPf_SoAccPfas1livViewRow,
                                                                           model.accettazione.common.AccPf_SoAccPfas1livViewRow {


    public static final int ENTITY_ACCPF_SOACCPFAS1LIV = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Idaccpf1liv,
        Idinvito,
        Dtcreazione,
        Opcreazione,
        Dtultmod,
        Opultmod,
        CodCampione,
        CodRichiesta,
        Miteni,
        Donatore;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDACCPF1LIV = AttributesEnum.Idaccpf1liv.index();
    public static final int IDINVITO = AttributesEnum.Idinvito.index();
    public static final int DTCREAZIONE = AttributesEnum.Dtcreazione.index();
    public static final int OPCREAZIONE = AttributesEnum.Opcreazione.index();
    public static final int DTULTMOD = AttributesEnum.Dtultmod.index();
    public static final int OPULTMOD = AttributesEnum.Opultmod.index();
    public static final int CODCAMPIONE = AttributesEnum.CodCampione.index();
    public static final int CODRICHIESTA = AttributesEnum.CodRichiesta.index();
    public static final int MITENI = AttributesEnum.Miteni.index();
    public static final int DONATORE = AttributesEnum.Donatore.index();

    /**
     *
     *  This is the default constructor (do not remove)
     */
  public AccPf_SoAccPfas1livViewRowImpl()
  {
  }

  /**
   * 
   *  Gets AccPf_SoAccPfas1liv entity object.
   */
  public AccPf_SoAccPfas1livImpl getAccPf_SoAccPfas1liv()
  {
    return (AccPf_SoAccPfas1livImpl)getEntity(0);
  }

  /**
     *
     *  Gets the attribute value for IDACCPF_1LIV using the alias name Idaccpf1liv
     */
    public Integer getIdaccpf1liv()
  {
        return (Integer) getAttributeInternal(IDACCPF1LIV);
    }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDACCPF_1LIV using the alias name Idaccpf1liv
   */
  public void setIdaccpf1liv(Integer value)
  {
    setAttributeInternal(IDACCPF1LIV, value);
  }

  /**
     *
     *  Gets the attribute value for IDINVITO using the alias name Idinvito
     */
    public Integer getIdinvito()
  {
        return (Integer) getAttributeInternal(IDINVITO);
    }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDINVITO using the alias name Idinvito
   */
  public void setIdinvito(Integer value)
  {
    setAttributeInternal(IDINVITO, value);
  }

  /**
   * 
   *  Gets the attribute value for DTCREAZIONE using the alias name Dtcreazione
   */
  public Date getDtcreazione()
  {
    return (Date)getAttributeInternal(DTCREAZIONE);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for DTCREAZIONE using the alias name Dtcreazione
   */
  public void setDtcreazione(Date value)
  {
    setAttributeInternal(DTCREAZIONE, value);
  }

  /**
   * 
   *  Gets the attribute value for OPCREAZIONE using the alias name Opcreazione
   */
  public String getOpcreazione()
  {
    return (String)getAttributeInternal(OPCREAZIONE);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for OPCREAZIONE using the alias name Opcreazione
   */
  public void setOpcreazione(String value)
  {
    setAttributeInternal(OPCREAZIONE, value);
  }

  /**
   * 
   *  Gets the attribute value for DTULTMOD using the alias name Dtultmod
   */
  public Date getDtultmod()
  {
    return (Date)getAttributeInternal(DTULTMOD);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for DTULTMOD using the alias name Dtultmod
   */
  public void setDtultmod(Date value)
  {
    setAttributeInternal(DTULTMOD, value);
  }

  /**
   * 
   *  Gets the attribute value for OPULTMOD using the alias name Opultmod
   */
  public String getOpultmod()
  {
    return (String)getAttributeInternal(OPULTMOD);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for OPULTMOD using the alias name Opultmod
   */
  public void setOpultmod(String value)
  {
    setAttributeInternal(OPULTMOD, value);
  }

  /**
     *
     *  Gets the attribute value for COD_CAMPIONE using the alias name CodCampione
     */
    public BigDecimal getCodCampione()
  {
        return (BigDecimal) getAttributeInternal(CODCAMPIONE);
    }

  /**
   * 
   *  Sets <code>value</code> as attribute value for COD_CAMPIONE using the alias name CodCampione
   */
  public void setCodCampione(BigDecimal value)
  {
    setAttributeInternal(CODCAMPIONE, value);
  }

  /**
     *
     *  Gets the attribute value for COD_RICHIESTA using the alias name CodRichiesta
     */
    public BigDecimal getCodRichiesta()
  {
        return (BigDecimal) getAttributeInternal(CODRICHIESTA);
    }

  /**
   * 
   *  Sets <code>value</code> as attribute value for COD_RICHIESTA using the alias name CodRichiesta
   */
  public void setCodRichiesta(BigDecimal value)
  {
    setAttributeInternal(CODRICHIESTA, value);
  }

  /**
     *
     *  Gets the attribute value for MITENI using the alias name Miteni
     */
    public Integer getMiteni()
  {
        return (Integer) getAttributeInternal(MITENI);
    }

  /**
   * 
   *  Sets <code>value</code> as attribute value for MITENI using the alias name Miteni
   */
  public void setMiteni(Integer value)
  {
    setAttributeInternal(MITENI, value);
  }

  /**
     *
     *  Gets the attribute value for DONATORE using the alias name Donatore
     */
    public Integer getDonatore()
  {
        return (Integer) getAttributeInternal(DONATORE);
    }

  /**
   * 
   *  Sets <code>value</code> as attribute value for DONATORE using the alias name Donatore
   */
  public void setDonatore(Integer value)
  {
    setAttributeInternal(DONATORE, value);
  }


}
