package model.agenda;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 12 12:10:57 CET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Agenda_DettAppViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Agenda_DettAppViewImpl() {
    }
}

