package model.accettazione.common;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Timestamp;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 05 09:57:15 CET 2018
// ---------------------------------------------------------------------
public interface Acc_RicInvitiViewRow extends Row {
    String getCentroPrel();

    String getCf();

    BigDecimal getCodRichiesta();

    String getCodesitoinvito();

    String getCodidsoggMx();

    String getCodts();

    String getCognome();
    
    String getChiave();

    Integer getConfermato();

    Integer getConsenso();

    Integer getConsensoCond();

    Date getDataNascita();

    String getDescEsito();

    String getDescTpinv();

    Date getDtapp();

    Timestamp getDtoraapp();

    String getEscl();

    Integer getEta();

    Integer getIdbraccioTrial();

    Integer getIdcentro1liv();

    Integer getIdcentro2liv();

    Integer getIdcentroprelievo();

    Integer getIdcref();

    Integer getIdinvito();

    Integer getIdstatoTrial();

    Integer getLivello();

    String getNome();

    BigDecimal getNumvetrino();

    Integer getPrelievoHpv();

    Boolean getSelezionato();

    Integer getSollecitare();

    String getTestProposto();

    String getTpscr();


    String getTrialBraccioDescrbreve();

    String getTrialStatoDescr();

    String getTrialStatoDescrbreve();

    String getUlss();

    Integer getVaccHpv();

    String getVaccinatoHpv();

    void setCentroPrel(String value);

    void setCf(String value);

    void setCodRichiesta(BigDecimal value);

    void setCodesitoinvito(String value);

    void setCodidsoggMx(String value);

    void setCodts(String value);

    void setCognome(String value);


    void setConsenso(Integer value);

    void setDataNascita(Date value);

    void setDescEsito(String value);

    void setDescTpinv(String value);

    void setDtapp(Date value);

    void setDtoraapp(Timestamp value);

    void setEscl(String value);

    void setEta(Integer value);

    void setIdcentro1liv(Integer value);

    void setIdcentro2liv(Integer value);

    void setIdcentroprelievo(Integer value);

    void setIdcref(Integer value);

    void setIdinvito(Integer value);

    void setLivello(Integer value);

    void setNome(String value);

    void setNumvetrino(BigDecimal value);

    void setSelezionato(Boolean value);

    void setSollecitare(Integer value);

    void setTpscr(String value);

    void setUlss(String value);

    void setVaccHpv(Integer value);

    void setVaccinatoHpv(String value);

    String getTrialBraccioDescr();
}

