package model.common;

import oracle.jbo.Row;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface A_SoOldRoundindivViewRow extends Row 
{
  String getCodts();

  void setCodts(String value);

  Integer getOldRoundindiv();

  void setOldRoundindiv(Integer value);
}