package model.common;

import oracle.jbo.Row;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface A_SoInvitoViewRow extends Row {
    Integer getIdinvito();

  void setIdinvito(Integer value);

  String getCodts();

  void setCodts(String value);

  String getIdtpinvito();

  void setIdtpinvito(String value);

  String getCodesitoinvito();

  void setCodesitoinvito(String value);

    Integer getLivesito();

  void setLivesito(Integer value);

    Integer getAttivo();

  void setAttivo(Integer value);

    Integer getIdcentroprelievo();

  void setIdcentroprelievo(Integer value);

    Integer getIdcentrorichiamo();

  void setIdcentrorichiamo(Integer value);

    Integer getIdcentroref1liv();

  void setIdcentroref1liv(Integer value);

    Integer getIdcentroref2liv();

  void setIdcentroref2liv(Integer value);

    Integer getIdapp();

  void setIdapp(Integer value);

  oracle.jbo.domain.Date getDtapp();

  void setDtapp(oracle.jbo.domain.Date value);

    Integer getOraapp();

  void setOraapp(Integer value);

    Integer getMinapp();

  void setMinapp(Integer value);

  oracle.jbo.domain.Date getDtappiniziale();

  void setDtappiniziale(oracle.jbo.domain.Date value);

    Integer getConsenso();

  void setConsenso(Integer value);

  oracle.jbo.domain.Date getDtesamerecente();

  void setDtesamerecente(oracle.jbo.domain.Date value);

  oracle.jbo.domain.Date getDtrichiamo();

  void setDtrichiamo(oracle.jbo.domain.Date value);

  oracle.jbo.domain.Date getDtinviorichiamo();

  void setDtinviorichiamo(oracle.jbo.domain.Date value);

  String getOpmedico();

  void setOpmedico(String value);

  oracle.jbo.domain.Date getDtinviosollecito();

  void setDtinviosollecito(oracle.jbo.domain.Date value);

    Integer getRoundcomune();

  void setRoundcomune(Integer value);

    Integer getRoundindiv();

  void setRoundindiv(Integer value);

    Integer getVolontaria();

  void setVolontaria(Integer value);

  oracle.jbo.domain.Date getDtblocco();

  void setDtblocco(oracle.jbo.domain.Date value);

    Integer getChiusuraroundindiv();

  void setChiusuraroundindiv(Integer value);

  oracle.jbo.domain.Date getDtultimamod();

  void setDtultimamod(oracle.jbo.domain.Date value);

  oracle.jbo.domain.Date getDtcreazione();

  void setDtcreazione(oracle.jbo.domain.Date value);

  String getOpinserimento();

  void setOpinserimento(String value);

  oracle.jbo.domain.Date getDtmodesclusione();

  void setDtmodesclusione(oracle.jbo.domain.Date value);

  String getOpmodifica();

  void setOpmodifica(String value);

    Integer getFuorifascia();

  void setFuorifascia(Integer value);

  String getNoteinvito();

  void setNoteinvito(String value);

  String getUlss();

  void setUlss(String value);

  String getTpscr();

  void setTpscr(String value);

    Integer getRoundinviti();

  void setRoundinviti(Integer value);

  String getTprichiamo();

  void setTprichiamo(String value);

    Integer getLivello();

  void setLivello(Integer value);

  String getCoddomicilio();

  String getCodresidenza();

    Integer getStatoanag();

  String getViadomicilio();

  String getViaresidenza();

  void setCoddomicilio(String value);

  void setCodresidenza(String value);

  void setStatoanag(Integer value);

  void setViadomicilio(String value);

  void setViaresidenza(String value);

    Integer getDaConfermare();

  oracle.jbo.domain.Date getDtconscont();

  oracle.jbo.domain.Date getDtritcont();

    Integer getIdostetrica();

    Integer getZona();

  void setDaConfermare(Integer value);

  void setDtconscont(oracle.jbo.domain.Date value);

  void setDtritcont(oracle.jbo.domain.Date value);

  void setIdostetrica(Integer value);

  void setZona(Integer value);

    String getTestProposto();

    void setTestProposto(String value);

    String getOtp();

    void setOtp(String value);

    Integer getReleaseCodeComDom();

    Integer getReleaseCodeComRes();

    void setReleaseCodeComDom(Integer value);

    void setReleaseCodeComRes(Integer value);

    oracle.jbo.domain.Number getConfermato();

    void setConfermato(oracle.jbo.domain.Number value);
}
