package model.common;

import java.math.BigDecimal;

import oracle.jbo.Row;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface A_SoAccMammo1livViewRow extends Row {
    Integer getIdaccma1liv();

  void setIdaccma1liv(Integer value);

    Integer getIdinvito();

  void setIdinvito(Integer value);

  oracle.jbo.domain.Date getDtcreazione();

  void setDtcreazione(oracle.jbo.domain.Date value);

  String getOpcreazione();

  void setOpcreazione(String value);

  oracle.jbo.domain.Date getDtultmod();

  void setDtultmod(oracle.jbo.domain.Date value);

  String getOpultmod();

  void setOpultmod(String value);

  String getNote();

  void setNote(String value);

    BigDecimal getCodRichiesta();

  void setCodRichiesta(BigDecimal value);
}