package model.common;

import java.math.BigDecimal;

import oracle.jbo.Row;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface Acc_SoAccCito2livViewRow extends Row {
    Integer getIdacc2liv();

  void setIdacc2liv(Integer value);

    Integer getIdmot();

  void setIdmot(Integer value);

  String getDescrizione();

  void setDescrizione(String value);

    Integer getIdinvito();

  void setIdinvito(Integer value);

  String getNoteacc2liv();

  void setNoteacc2liv(String value);

  String getAltromotultint();

  void setAltromotultint(String value);

  String getTpscr();

  void setTpscr(String value);

    BigDecimal getCodRichiesta();

    void setCodRichiesta(BigDecimal value);
}
