package model.common;

import java.math.BigDecimal;

import oracle.jbo.Row;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface Acc_SoAccCito1livViewRow extends Row {
    String getAltromotultint();

    BigDecimal getCodRichiesta();

    String getDescrizione();

    Integer getIdacc1liv();

    Integer getIdinvito();

    Integer getIdmot();

    Integer getIdtpprelievo();

    String getNoteacc1liv();

    String getNoteprelievo();

    BigDecimal getNumvetrino();

    Integer getPrelievoHpv();

    Integer getTotvetrini();

    String getTpscr();

    void setAltromotultint(String value);

    void setCodRichiesta(BigDecimal value);

    void setDescrizione(String value);

    void setIdacc1liv(Integer value);

    void setIdinvito(Integer value);

    void setIdmot(Integer value);

    void setIdtpprelievo(Integer value);

    void setNoteacc1liv(String value);

    void setNoteprelievo(String value);

    void setNumvetrino(BigDecimal value);

    void setPrelievoHpv(Integer value);

    void setTotvetrini(Integer value);

    void setTpscr(String value);
    }

