package model.common;

import oracle.jbo.Row;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface Ref_SoRefertomammo2livViewRow extends Row {
  Integer getIdreferto();

  void setIdreferto(Integer value);

  Integer getIdinvito();

  void setIdinvito(Integer value);

  String getCodts();

  void setCodts(String value);

  String getUlss();

  void setUlss(String value);

  String getTpscr();

  void setTpscr(String value);

  Integer getMammo();

  void setMammo(Integer value);

  oracle.jbo.domain.Date getMData();

  void setMData(oracle.jbo.domain.Date value);

  Integer getMMedico();

  void setMMedico(Integer value);

  String getMNote();

  void setMNote(String value);

  String getMAltroTipo();

  void setMAltroTipo(String value);

  Integer getEco();

  void setEco(Integer value);

  oracle.jbo.domain.Date getEData();

  void setEData(oracle.jbo.domain.Date value);

  Integer getEMedico();

  void setEMedico(Integer value);

  String getENote();

  void setENote(String value);

  Integer getClinico();

  void setClinico(Integer value);

  oracle.jbo.domain.Date getClData();

  void setClData(oracle.jbo.domain.Date value);

  Integer getClMedico();

  void setClMedico(Integer value);

  String getClNote();

  void setClNote(String value);

  String getNoteRadio();

  void setNoteRadio(String value);

  String getGrExec();

  void setGrExec(String value);

  String getGrLocalizz();

  void setGrLocalizz(String value);

  String getGrEsitoCito();

  void setGrEsitoCito(String value);

  String getGrEsitoAgob();

  void setGrEsitoAgob(String value);

  String getGrTecnicaExec();

  void setGrTecnicaExec(String value);

  Integer getCitologiaDx();

  void setCitologiaDx(Integer value);

  String getCDxAltro();

  void setCDxAltro(String value);

  oracle.jbo.domain.Date getCDxData();

  void setCDxData(oracle.jbo.domain.Date value);

  Integer getCDxMedico();

  void setCDxMedico(Integer value);

  Integer getCDxLocalizz();

  void setCDxLocalizz(Integer value);

  String getCDxNoteEs();

  void setCDxNoteEs(String value);

  Integer getCDxEsito();

  void setCDxEsito(Integer value);

  oracle.jbo.domain.Date getCDxDtref();

  void setCDxDtref(oracle.jbo.domain.Date value);

  Integer getCDxCalcificazioni();

  void setCDxCalcificazioni(Integer value);

  Integer getCDxPatologo();

  void setCDxPatologo(Integer value);

  String getCDxNote();

  void setCDxNote(String value);

  Integer getCitologiaSx();

  void setCitologiaSx(Integer value);

  String getCSxAltro();

  void setCSxAltro(String value);

  oracle.jbo.domain.Date getCSxData();

  void setCSxData(oracle.jbo.domain.Date value);

  Integer getCSxMedico();

  void setCSxMedico(Integer value);

  Integer getCSxLocalizz();

  void setCSxLocalizz(Integer value);

  String getCSxNoteEs();

  void setCSxNoteEs(String value);

  Integer getCSxEsito();

  void setCSxEsito(Integer value);

  oracle.jbo.domain.Date getCSxDtref();

  void setCSxDtref(oracle.jbo.domain.Date value);

  Integer getCSxCalcificazioni();

  void setCSxCalcificazioni(Integer value);

  Integer getCSxPatologo();

  void setCSxPatologo(Integer value);

  String getCSxNote();

  void setCSxNote(String value);

  Integer getAgobDx();

  void setAgobDx(Integer value);

  String getADxAltro();

  void setADxAltro(String value);

  oracle.jbo.domain.Date getADxData();

  void setADxData(oracle.jbo.domain.Date value);

  Integer getADxPrelevatore();

  void setADxPrelevatore(Integer value);

  Integer getADxLocalizz();

  void setADxLocalizz(Integer value);

  Integer getADxEsecuzione();

  void setADxEsecuzione(Integer value);

  String getADxExecAltro();

  void setADxExecAltro(String value);

  String getADxNoteEs();

  void setADxNoteEs(String value);

  oracle.jbo.domain.Date getADxDtref();

  void setADxDtref(oracle.jbo.domain.Date value);

  Integer getADxEsito();

  void setADxEsito(Integer value);

  Integer getADxCalcificazioni();

  void setADxCalcificazioni(Integer value);

  Integer getADxLettore();

  void setADxLettore(Integer value);

  String getADxNote();

  void setADxNote(String value);

  Integer getAgobSx();

  void setAgobSx(Integer value);

  String getASxAltro();

  void setASxAltro(String value);

  oracle.jbo.domain.Date getASxData();

  void setASxData(oracle.jbo.domain.Date value);

  Integer getASxPrelevatore();

  void setASxPrelevatore(Integer value);

  Integer getASxLocalizz();

  void setASxLocalizz(Integer value);

  Integer getASxEsecuzione();

  void setASxEsecuzione(Integer value);

  String getASxExecAltro();

  void setASxExecAltro(String value);

  String getASxNoteEs();

  void setASxNoteEs(String value);

  oracle.jbo.domain.Date getASxDtref();

  void setASxDtref(oracle.jbo.domain.Date value);

  Integer getASxEsito();

  void setASxEsito(Integer value);

  Integer getASxCalcificazioni();

  void setASxCalcificazioni(Integer value);

  Integer getASxLettore();

  void setASxLettore(Integer value);

  String getASxNote();

  void setASxNote(String value);

  String getGrDiagnosi();

  void setGrDiagnosi(String value);

  Integer getDiagnosiPeggiore();

  void setDiagnosiPeggiore(Integer value);

  Integer getIdsugg2l();

  void setIdsugg2l(Integer value);

  oracle.jbo.domain.Date getDtconcl();

  void setDtconcl(oracle.jbo.domain.Date value);

  Integer getIdmedconcl1();

  void setIdmedconcl1(Integer value);

  Integer getIdmedconcl2();

  void setIdmedconcl2(Integer value);

  String getNote();

  void setNote(String value);

  Integer getCompleto();

  void setCompleto(Integer value);

  Integer getIntchiusi();

  void setIntchiusi(Integer value);

  oracle.jbo.domain.Date getDtinserimento();

  void setDtinserimento(oracle.jbo.domain.Date value);

  String getOpinserimento();

  void setOpinserimento(String value);

  oracle.jbo.domain.Date getDtultmodifica();

  void setDtultmodifica(oracle.jbo.domain.Date value);

  String getOpultmodifica();

  void setOpultmodifica(String value);

  Integer getTpreferto();

  void setTpreferto(Integer value);

  Integer getIdallegato();

  void setIdallegato(Integer value);

  oracle.jbo.domain.Date getDtcreazione();

  void setDtcreazione(oracle.jbo.domain.Date value);

  oracle.jbo.domain.Date getDtspedizione();

  void setDtspedizione(oracle.jbo.domain.Date value);

  Integer getConsiglioRadio();

  void setConsiglioRadio(Integer value);

  String getGrConsiglioRadio();

  void setGrConsiglioRadio(String value);
}