package model.common;

import java.sql.Connection;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 21 14:27:50 CET 2018
// ---------------------------------------------------------------------
public interface Sched_AppModule extends ApplicationModule {
    Connection getDBConnection();
}

