package model.common;

import oracle.jbo.Row;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface Stats_StandardMatrixRow extends Row {
  String getRow_id();

  void setRow_id(String value);

  String getRow_label();

  void setRow_label(String value);

  String getField_0();

  void setField_0(String value);

  String getField_1();

  void setField_1(String value);

  String getField_2();

  void setField_2(String value);

  String getField_3();

  void setField_3(String value);

  String getField_4();

  void setField_4(String value);

  String getField_5();

  void setField_5(String value);

  String getField_6();

  void setField_6(String value);

  String getField_7();

  void setField_7(String value);

  String getField_8();

  void setField_8(String value);

  String getField_9();

  void setField_9(String value);

  String getField_10();

  void setField_10(String value);

  String getField_11();

  void setField_11(String value);

  String getField_12();

  void setField_12(String value);

  String getField_13();

  void setField_13(String value);

  String getField_14();

  void setField_14(String value);

  String getField_15();

  void setField_15(String value);

  String getField_16();

  void setField_16(String value);

  String getField_17();

  void setField_17(String value);

  String getField_18();

  void setField_18(String value);

  String getField_19();

  void setField_19(String value);

  String getField_20();

  void setField_20(String value);

  String getField_21();

  void setField_21(String value);

  String getField_22();

  void setField_22(String value);

  String getField_23();

  void setField_23(String value);

  String getField_24();

  void setField_24(String value);

  String getField_25();

  void setField_25(String value);

  String getField_26();

  void setField_26(String value);

  String getField_27();

  void setField_27(String value);

  String getField_28();

  void setField_28(String value);

  String getField_29();

  void setField_29(String value);
}