package model.common;

import oracle.jbo.Row;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface Stats_SoCnfSugg2livViewRow extends Row {
    Integer getIdsugg2l();

  void setIdsugg2l(Integer value);

  String getIdtpinvito();

  void setIdtpinvito(String value);

  String getEsitosugg();

  void setEsitosugg(String value);

  String getDescrizione();

  void setDescrizione(String value);

  Integer getGgrichiamo();

  void setGgrichiamo(Integer value);

  Integer getInvia2liv();

  void setInvia2liv(Integer value);

  Integer getInviaintervento();

  void setInviaintervento(Integer value);



  String getUlss();

  void setUlss(String value);

  String getTpscr();

  void setTpscr(String value);
}