package model.common;

import oracle.jbo.Row;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface Stats_SoCnfTpinvitoViewRow extends Row {
  String getIdtpinvito();

  void setIdtpinvito(String value);

  Integer getIdcateg();

  void setIdcateg(Integer value);

  String getDescrizione();

  void setDescrizione(String value);

  String getDescrbreve();

  void setDescrbreve(String value);

  Integer getAppuntamento();

  void setAppuntamento(Integer value);

  Integer getInvio2liv();

  void setInvio2liv(Integer value);

  String getCodregionale();

  void setCodregionale(String value);

  String getUlss();

  void setUlss(String value);

  String getTpscr();

  void setTpscr(String value);

  Integer getGgsollecito();

  void setGgsollecito(Integer value);

  String getIdtpinvSoll();

  void setIdtpinvSoll(String value);

  Integer getLivello();

  void setLivello(Integer value);

  Integer getOrdine();

  void setOrdine(Integer value);

  Integer getIdcateg1();

  void setIdcateg1(Integer value);

  String getDescrizione1();

  void setDescrizione1(String value);

  String getTpscr1();

  void setTpscr1(String value);
}