package model.client;

import oracle.jbo.client.remote.RowImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class A_SoOldRoundindivViewRowClient extends RowImpl 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public A_SoOldRoundindivViewRowClient()
  {
  }

  public String getCodts()
  {
    return (String)getAttribute("Codts");
  }

  public void setCodts(String value)
  {
    setAttribute("Codts", value);
  }

  public Integer getOldRoundindiv()
  {
    return (Integer)getAttribute("OldRoundindiv");
  }

  public void setOldRoundindiv(Integer value)
  {
    setAttribute("OldRoundindiv", value);
  }
}