package model.client;

import oracle.jbo.client.remote.RowImpl;

//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class A_SoCnfComuniZoneParamViewRowClient extends RowImpl {
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public A_SoCnfComuniZoneParamViewRowClient()
  {
  }


    public Integer getId() {
        return (Integer)getAttribute("Id");
    }

    public void setId(Integer value) {
        setAttribute("Id", value);
    }

    public String getCodcom() {
        return (String)getAttribute("Codcom");
    }

    public void setCodcom(String value) {
        setAttribute("Codcom", value);
    }

    public Integer getCoddistrzona() {
        return (Integer)getAttribute("Coddistrzona");
    }

    public void setCoddistrzona(Integer value) {
        setAttribute("Coddistrzona", value);
    }

    public String getTpscr() {
        return (String)getAttribute("Tpscr");
    }

    public void setTpscr(String value) {
        setAttribute("Tpscr", value);
    }

    public String getAltro() {
        return (String)getAttribute("Altro");
    }

    public void setAltro(String value) {
        setAttribute("Altro", value);
    }

    public String getUlss() {
        return (String)getAttribute("Ulss");
    }

    public void setUlss(String value) {
        setAttribute("Ulss", value);
    }
}
