package model.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Timestamp;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class AccCo_RicInvitiViewRowClient extends RowImpl {
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public AccCo_RicInvitiViewRowClient()
  {
  }


    public String getCf() {
        return (String)getAttribute("Cf");
    }

    public String getCodesitoinvito() {
        return (String)getAttribute("Codesitoinvito");
    }

    public String getCodts() {
        return (String)getAttribute("Codts");
    }

    public String getCognome() {
        return (String)getAttribute("Cognome");
    }

    public Integer getConsenso() {
        return (Integer)getAttribute("Consenso");
    }

    public Date getDataNascita() {
        return (Date)getAttribute("DataNascita");
    }

    public String getDescEsito() {
        return (String)getAttribute("DescEsito");
    }

    public String getDescTpinv() {
        return (String)getAttribute("DescTpinv");
    }

    public Date getDtapp() {
        return (Date)getAttribute("Dtapp");
    }

    public Timestamp getDtoraapp() {
        return (Timestamp)getAttribute("Dtoraapp");
    }

    public String getEscl() {
        return (String)getAttribute("Escl");
    }

    public Integer getEta() {
        return (Integer)getAttribute("Eta");
    }

    public Integer getIdcentroprelievo() {
        return (Integer)getAttribute("Idcentroprelievo");
    }

    public Integer getIdcref() {
        return (Integer)getAttribute("Idcref");
    }

    public Integer getIdinvito() {
        return (Integer)getAttribute("Idinvito");
    }

    public Integer getLivello() {
        return (Integer)getAttribute("Livello");
    }

    public String getNome() {
        return (String)getAttribute("Nome");
    }

    public String getTpscr() {
        return (String)getAttribute("Tpscr");
    }

    public String getUlss() {
        return (String)getAttribute("Ulss");
    }

    public void setCf(String value) {
        setAttribute("Cf", value);
    }

    public void setCodesitoinvito(String value) {
        setAttribute("Codesitoinvito", value);
    }

    public void setCodts(String value) {
        setAttribute("Codts", value);
    }

    public void setCognome(String value) {
        setAttribute("Cognome", value);
    }

    public void setConsenso(Integer value) {
        setAttribute("Consenso", value);
    }

    public void setDataNascita(Date value) {
        setAttribute("DataNascita", value);
    }

    public void setDescEsito(String value) {
        setAttribute("DescEsito", value);
    }

    public void setDescTpinv(String value) {
        setAttribute("DescTpinv", value);
    }

    public void setDtapp(Date value) {
        setAttribute("Dtapp", value);
    }

    public void setDtoraapp(Timestamp value) {
        setAttribute("Dtoraapp", value);
    }

    public void setEscl(String value) {
        setAttribute("Escl", value);
    }

    public void setEta(Integer value) {
        setAttribute("Eta", value);
    }

    public void setIdcentroprelievo(Integer value) {
        setAttribute("Idcentroprelievo", value);
    }

    public void setIdcref(Integer value) {
        setAttribute("Idcref", value);
    }

    public void setIdinvito(Integer value) {
        setAttribute("Idinvito", value);
    }

    public void setLivello(Integer value) {
        setAttribute("Livello", value);
    }

    public void setNome(String value) {
        setAttribute("Nome", value);
    }

    public void setTpscr(String value) {
        setAttribute("Tpscr", value);
    }

    public void setUlss(String value) {
        setAttribute("Ulss", value);
    }
}
