package model.client;

import oracle.jbo.client.remote.RowImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class Stats_SoCnfTpinvitoViewRowClient extends RowImpl {
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public Stats_SoCnfTpinvitoViewRowClient()
  {
  }


    public String getIdtpinvito() {
        return (String)getAttribute("Idtpinvito");
    }

    public void setIdtpinvito(String value) {
        setAttribute("Idtpinvito", value);
    }

    public Integer getIdcateg() {
        return (Integer)getAttribute("Idcateg");
    }

    public void setIdcateg(Integer value) {
        setAttribute("Idcateg", value);
    }

    public String getDescrizione() {
        return (String)getAttribute("Descrizione");
    }

    public void setDescrizione(String value) {
        setAttribute("Descrizione", value);
    }

    public String getDescrbreve() {
        return (String)getAttribute("Descrbreve");
    }

    public void setDescrbreve(String value) {
        setAttribute("Descrbreve", value);
    }

    public Integer getAppuntamento() {
        return (Integer)getAttribute("Appuntamento");
    }

    public void setAppuntamento(Integer value) {
        setAttribute("Appuntamento", value);
    }

    public Integer getInvio2liv() {
        return (Integer)getAttribute("Invio2liv");
    }

    public void setInvio2liv(Integer value) {
        setAttribute("Invio2liv", value);
    }

    public String getCodregionale() {
        return (String)getAttribute("Codregionale");
    }

    public void setCodregionale(String value) {
        setAttribute("Codregionale", value);
    }

    public String getUlss() {
        return (String)getAttribute("Ulss");
    }

    public void setUlss(String value) {
        setAttribute("Ulss", value);
    }

    public String getTpscr() {
        return (String)getAttribute("Tpscr");
    }

    public void setTpscr(String value) {
        setAttribute("Tpscr", value);
    }

    public Integer getGgsollecito() {
        return (Integer)getAttribute("Ggsollecito");
    }

    public void setGgsollecito(Integer value) {
        setAttribute("Ggsollecito", value);
    }

    public String getIdtpinvSoll() {
        return (String)getAttribute("IdtpinvSoll");
    }

    public void setIdtpinvSoll(String value) {
        setAttribute("IdtpinvSoll", value);
    }

    public Integer getLivello() {
        return (Integer)getAttribute("Livello");
    }

    public void setLivello(Integer value) {
        setAttribute("Livello", value);
    }

    public Integer getOrdine() {
        return (Integer)getAttribute("Ordine");
    }

    public void setOrdine(Integer value) {
        setAttribute("Ordine", value);
    }

    public Integer getIdcateg1() {
        return (Integer)getAttribute("Idcateg1");
    }

    public void setIdcateg1(Integer value) {
        setAttribute("Idcateg1", value);
    }

    public String getDescrizione1() {
        return (String)getAttribute("Descrizione1");
    }

    public void setDescrizione1(String value) {
        setAttribute("Descrizione1", value);
    }

    public String getTpscr1() {
        return (String)getAttribute("Tpscr1");
    }

    public void setTpscr1(String value) {
        setAttribute("Tpscr1", value);
    }
}
