package model.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Date;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class Transfer_SoCnfImpexpViewRowClient extends RowImpl {
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public Transfer_SoCnfImpexpViewRowClient()
  {
  }


    public Integer getProgrulss() {
        return (Integer)getAttribute("Progrulss");
    }

    public void setProgrulss(Integer value) {
        setAttribute("Progrulss", value);
    }

    public Integer getIdcentroref() {
        return (Integer)getAttribute("Idcentroref");
    }

    public void setIdcentroref(Integer value) {
        setAttribute("Idcentroref", value);
    }

    public String getNomefilepart() {
        return (String)getAttribute("Nomefilepart");
    }

    public void setNomefilepart(String value) {
        setAttribute("Nomefilepart", value);
    }

    public String getNomefilearr() {
        return (String)getAttribute("Nomefilearr");
    }

    public void setNomefilearr(String value) {
        setAttribute("Nomefilearr", value);
    }

    public String getPosizfilepart() {
        return (String)getAttribute("Posizfilepart");
    }

    public void setPosizfilepart(String value) {
        setAttribute("Posizfilepart", value);
    }

    public String getPosizfilearr() {
        return (String)getAttribute("Posizfilearr");
    }

    public void setPosizfilearr(String value) {
        setAttribute("Posizfilearr", value);
    }

    public String getIppart() {
        return (String)getAttribute("Ippart");
    }

    public void setIppart(String value) {
        setAttribute("Ippart", value);
    }

    public String getUsrftp() {
        return (String)getAttribute("Usrftp");
    }

    public void setUsrftp(String value) {
        setAttribute("Usrftp", value);
    }

    public String getPwdftp() {
        return (String)getAttribute("Pwdftp");
    }

    public void setPwdftp(String value) {
        setAttribute("Pwdftp", value);
    }

    public Integer getOrasched() {
        return (Integer)getAttribute("Orasched");
    }

    public void setOrasched(Integer value) {
        setAttribute("Orasched", value);
    }

    public Integer getIntervallo() {
        return (Integer)getAttribute("Intervallo");
    }

    public void setIntervallo(Integer value) {
        setAttribute("Intervallo", value);
    }

    public String getImpexp() {
        return (String)getAttribute("Impexp");
    }

    public void setImpexp(String value) {
        setAttribute("Impexp", value);
    }

    public String getTpdip() {
        return (String)getAttribute("Tpdip");
    }

    public void setTpdip(String value) {
        setAttribute("Tpdip", value);
    }

    public Integer getCancellazione() {
        return (Integer)getAttribute("Cancellazione");
    }

    public void setCancellazione(Integer value) {
        setAttribute("Cancellazione", value);
    }

    public String getIpdirvirtuale() {
        return (String)getAttribute("Ipdirvirtuale");
    }

    public void setIpdirvirtuale(String value) {
        setAttribute("Ipdirvirtuale", value);
    }

    public String getPosizdirvirtuale() {
        return (String)getAttribute("Posizdirvirtuale");
    }

    public void setPosizdirvirtuale(String value) {
        setAttribute("Posizdirvirtuale", value);
    }

    public String getDirvirtuale() {
        return (String)getAttribute("Dirvirtuale");
    }

    public void setDirvirtuale(String value) {
        setAttribute("Dirvirtuale", value);
    }

    public String getEmail() {
        return (String)getAttribute("Email");
    }

    public void setEmail(String value) {
        setAttribute("Email", value);
    }

    public BlobDomain getTemplate() {
        return (BlobDomain)getAttribute("Template");
    }

    public void setTemplate(BlobDomain value) {
        setAttribute("Template", value);
    }

    public String getUlss() {
        return (String)getAttribute("Ulss");
    }

    public void setUlss(String value) {
        setAttribute("Ulss", value);
    }

    public String getTpscr() {
        return (String)getAttribute("Tpscr");
    }

    public void setTpscr(String value) {
        setAttribute("Tpscr", value);
    }

    public BlobDomain getTemplateCompilato() {
        return (BlobDomain)getAttribute("TemplateCompilato");
    }

    public void setTemplateCompilato(BlobDomain value) {
        setAttribute("TemplateCompilato", value);
    }

    public Date getDttransfer() {
        return (Date)getAttribute("Dttransfer");
    }

    public void setDttransfer(Date value) {
        setAttribute("Dttransfer", value);
    }

    public Date getDtimport() {
        return (Date)getAttribute("Dtimport");
    }

    public void setDtimport(Date value) {
        setAttribute("Dtimport", value);
    }

    public BlobDomain getLogFile() {
        return (BlobDomain)getAttribute("LogFile");
    }

    public void setLogFile(BlobDomain value) {
        setAttribute("LogFile", value);
    }

    public Integer getFileparziale() {
        return (Integer)getAttribute("Fileparziale");
    }

    public void setFileparziale(Integer value) {
        setAttribute("Fileparziale", value);
    }

    public String getSuffisso() {
        return (String)getAttribute("Suffisso");
    }

    public void setSuffisso(String value) {
        setAttribute("Suffisso", value);
    }

    public String getFilevirtuale() {
        return (String)getAttribute("Filevirtuale");
    }

    public void setFilevirtuale(String value) {
        setAttribute("Filevirtuale", value);
    }

    public Integer getCancellazioneDip() {
        return (Integer)getAttribute("CancellazioneDip");
    }

    public void setCancellazioneDip(Integer value) {
        setAttribute("CancellazioneDip", value);
    }

    public Integer getFtpport() {
        return (Integer)getAttribute("Ftpport");
    }

    public void setFtpport(Integer value) {
        setAttribute("Ftpport", value);
    }

    public Integer getAttivo() {
        return (Integer)getAttribute("Attivo");
    }

    public Integer getLunghRecord() {
        return (Integer)getAttribute("LunghRecord");
    }

    public void setAttivo(Integer value) {
        setAttribute("Attivo", value);
    }

    public void setLunghRecord(Integer value) {
        setAttribute("LunghRecord", value);
    }
}
