package model.referto;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class Ref_SoCnfRef2livMXCONSViewImpl extends ViewObjectImpl {
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public Ref_SoCnfRef2livMXCONSViewImpl()
  {
  }
}