package model.referto;

import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 13 14:40:15 CEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Ref_SoCnfSuggCrit1livCitoViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_REF_SOCNFSUGG1LIV = 0;
    public static final int ENTITY_REF_SOCNFCRITERISUGG1LIV = 1;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Idsugg {
            public Object get(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj) {
                return obj.getIdsugg();
            }

            public void put(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj, Object value) {
                obj.setIdsugg((Integer) value);
            }
        }
        ,
        Ulss {
            public Object get(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj) {
                return obj.getUlss();
            }

            public void put(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj, Object value) {
                obj.setUlss((String) value);
            }
        }
        ,
        Tpscr {
            public Object get(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj) {
                return obj.getTpscr();
            }

            public void put(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj, Object value) {
                obj.setTpscr((String) value);
            }
        }
        ,
        Idtpinvito {
            public Object get(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj) {
                return obj.getIdtpinvito();
            }

            public void put(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj, Object value) {
                obj.setIdtpinvito((String) value);
            }
        }
        ,
        Esitosugg {
            public Object get(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj) {
                return obj.getEsitosugg();
            }

            public void put(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj, Object value) {
                obj.setEsitosugg((String) value);
            }
        }
        ,
        Descrizione {
            public Object get(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj) {
                return obj.getDescrizione();
            }

            public void put(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj, Object value) {
                obj.setDescrizione((String) value);
            }
        }
        ,
        Ggrichiamo {
            public Object get(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj) {
                return obj.getGgrichiamo();
            }

            public void put(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj, Object value) {
                obj.setGgrichiamo((Integer) value);
            }
        }
        ,
        Inviaintervento {
            public Object get(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj) {
                return obj.getInviaintervento();
            }

            public void put(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj, Object value) {
                obj.setInviaintervento((Integer) value);
            }
        }
        ,
        Tipoesame {
            public Object get(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj) {
                return obj.getTipoesame();
            }

            public void put(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj, Object value) {
                obj.setTipoesame((String) value);
            }
        }
        ,
        Invia2liv {
            public Object get(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj) {
                return obj.getInvia2liv();
            }

            public void put(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj, Object value) {
                obj.setInvia2liv((Integer) value);
            }
        }
        ,
        Giuddiagnostico {
            public Object get(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj) {
                return obj.getGiuddiagnostico();
            }

            public void put(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj, Object value) {
                obj.setGiuddiagnostico((Integer) value);
            }
        }
        ,
        Coddip {
            public Object get(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj) {
                return obj.getCoddip();
            }

            public void put(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj, Object value) {
                obj.setCoddip((String) value);
            }
        }
        ,
        Codregionale {
            public Object get(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj) {
                return obj.getCodregionale();
            }

            public void put(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj, Object value) {
                obj.setCodregionale((Integer) value);
            }
        }
        ,
        Ordine {
            public Object get(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj) {
                return obj.getOrdine();
            }

            public void put(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj, Object value) {
                obj.setOrdine((Integer) value);
            }
        }
        ,
        Dtfinevalidita {
            public Object get(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj) {
                return obj.getDtfinevalidita();
            }

            public void put(Ref_SoCnfSuggCrit1livCitoViewRowImpl obj, Object value) {
                obj.setDtfinevalidita((Date) value);
            }
        }
        ;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public abstract Object get(Ref_SoCnfSuggCrit1livCitoViewRowImpl object);

        public abstract void put(Ref_SoCnfSuggCrit1livCitoViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDSUGG = AttributesEnum.Idsugg.index();
    public static final int ULSS = AttributesEnum.Ulss.index();
    public static final int TPSCR = AttributesEnum.Tpscr.index();
    public static final int IDTPINVITO = AttributesEnum.Idtpinvito.index();
    public static final int ESITOSUGG = AttributesEnum.Esitosugg.index();
    public static final int DESCRIZIONE = AttributesEnum.Descrizione.index();
    public static final int GGRICHIAMO = AttributesEnum.Ggrichiamo.index();
    public static final int INVIAINTERVENTO = AttributesEnum.Inviaintervento.index();
    public static final int TIPOESAME = AttributesEnum.Tipoesame.index();
    public static final int INVIA2LIV = AttributesEnum.Invia2liv.index();
    public static final int GIUDDIAGNOSTICO = AttributesEnum.Giuddiagnostico.index();
    public static final int CODDIP = AttributesEnum.Coddip.index();
    public static final int CODREGIONALE = AttributesEnum.Codregionale.index();
    public static final int ORDINE = AttributesEnum.Ordine.index();
    public static final int DTFINEVALIDITA = AttributesEnum.Dtfinevalidita.index();

    /**
     * This is the default constructor (do not remove).
     */
    public Ref_SoCnfSuggCrit1livCitoViewRowImpl() {
    }

    /**
     * Gets Ref_SoCnfSugg1liv entity object.
     * @return the Ref_SoCnfSugg1liv
     */
    public Ref_SoCnfSugg1livImpl getRef_SoCnfSugg1liv() {
        return (Ref_SoCnfSugg1livImpl) getEntity(ENTITY_REF_SOCNFSUGG1LIV);
    }


    /**
     * Gets Ref_SoCnfCriteriSugg1liv entity object.
     * @return the Ref_SoCnfCriteriSugg1liv
     */
    public EntityImpl getRef_SoCnfCriteriSugg1liv() {
        return (EntityImpl) getEntity(ENTITY_REF_SOCNFCRITERISUGG1LIV);
    }

    /**
     * Gets the attribute value for IDSUGG using the alias name Idsugg.
     * @return the IDSUGG
     */
    public Integer getIdsugg() {
        return (Integer) getAttributeInternal(IDSUGG);
    }

    /**
     * Sets <code>value</code> as attribute value for IDSUGG using the alias name Idsugg.
     * @param value value to set the IDSUGG
     */
    public void setIdsugg(Integer value) {
        setAttributeInternal(IDSUGG, value);
    }

    /**
     * Gets the attribute value for ULSS using the alias name Ulss.
     * @return the ULSS
     */
    public String getUlss() {
        return (String) getAttributeInternal(ULSS);
    }

    /**
     * Sets <code>value</code> as attribute value for ULSS using the alias name Ulss.
     * @param value value to set the ULSS
     */
    public void setUlss(String value) {
        setAttributeInternal(ULSS, value);
    }

    /**
     * Gets the attribute value for TPSCR using the alias name Tpscr.
     * @return the TPSCR
     */
    public String getTpscr() {
        return (String) getAttributeInternal(TPSCR);
    }

    /**
     * Sets <code>value</code> as attribute value for TPSCR using the alias name Tpscr.
     * @param value value to set the TPSCR
     */
    public void setTpscr(String value) {
        setAttributeInternal(TPSCR, value);
    }

    /**
     * Gets the attribute value for IDTPINVITO using the alias name Idtpinvito.
     * @return the IDTPINVITO
     */
    public String getIdtpinvito() {
        return (String) getAttributeInternal(IDTPINVITO);
    }

    /**
     * Sets <code>value</code> as attribute value for IDTPINVITO using the alias name Idtpinvito.
     * @param value value to set the IDTPINVITO
     */
    public void setIdtpinvito(String value) {
        setAttributeInternal(IDTPINVITO, value);
    }

    /**
     * Gets the attribute value for ESITOSUGG using the alias name Esitosugg.
     * @return the ESITOSUGG
     */
    public String getEsitosugg() {
        return (String) getAttributeInternal(ESITOSUGG);
    }

    /**
     * Sets <code>value</code> as attribute value for ESITOSUGG using the alias name Esitosugg.
     * @param value value to set the ESITOSUGG
     */
    public void setEsitosugg(String value) {
        setAttributeInternal(ESITOSUGG, value);
    }

    /**
     * Gets the attribute value for DESCRIZIONE using the alias name Descrizione.
     * @return the DESCRIZIONE
     */
    public String getDescrizione() {
        return (String) getAttributeInternal(DESCRIZIONE);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIZIONE using the alias name Descrizione.
     * @param value value to set the DESCRIZIONE
     */
    public void setDescrizione(String value) {
        setAttributeInternal(DESCRIZIONE, value);
    }

    /**
     * Gets the attribute value for GGRICHIAMO using the alias name Ggrichiamo.
     * @return the GGRICHIAMO
     */
    public Integer getGgrichiamo() {
        return (Integer) getAttributeInternal(GGRICHIAMO);
    }

    /**
     * Sets <code>value</code> as attribute value for GGRICHIAMO using the alias name Ggrichiamo.
     * @param value value to set the GGRICHIAMO
     */
    public void setGgrichiamo(Integer value) {
        setAttributeInternal(GGRICHIAMO, value);
    }

    /**
     * Gets the attribute value for INVIAINTERVENTO using the alias name Inviaintervento.
     * @return the INVIAINTERVENTO
     */
    public Integer getInviaintervento() {
        return (Integer) getAttributeInternal(INVIAINTERVENTO);
    }

    /**
     * Sets <code>value</code> as attribute value for INVIAINTERVENTO using the alias name Inviaintervento.
     * @param value value to set the INVIAINTERVENTO
     */
    public void setInviaintervento(Integer value) {
        setAttributeInternal(INVIAINTERVENTO, value);
    }

    /**
     * Gets the attribute value for TIPOESAME using the alias name Tipoesame.
     * @return the TIPOESAME
     */
    public String getTipoesame() {
        return (String) getAttributeInternal(TIPOESAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TIPOESAME using the alias name Tipoesame.
     * @param value value to set the TIPOESAME
     */
    public void setTipoesame(String value) {
        setAttributeInternal(TIPOESAME, value);
    }

    /**
     * Gets the attribute value for INVIA2LIV using the alias name Invia2liv.
     * @return the INVIA2LIV
     */
    public Integer getInvia2liv() {
        return (Integer) getAttributeInternal(INVIA2LIV);
    }

    /**
     * Sets <code>value</code> as attribute value for INVIA2LIV using the alias name Invia2liv.
     * @param value value to set the INVIA2LIV
     */
    public void setInvia2liv(Integer value) {
        setAttributeInternal(INVIA2LIV, value);
    }

    /**
     * Gets the attribute value for GIUDDIAGNOSTICO using the alias name Giuddiagnostico.
     * @return the GIUDDIAGNOSTICO
     */
    public Integer getGiuddiagnostico() {
        return (Integer) getAttributeInternal(GIUDDIAGNOSTICO);
    }

    /**
     * Sets <code>value</code> as attribute value for GIUDDIAGNOSTICO using the alias name Giuddiagnostico.
     * @param value value to set the GIUDDIAGNOSTICO
     */
    public void setGiuddiagnostico(Integer value) {
        setAttributeInternal(GIUDDIAGNOSTICO, value);
    }

    /**
     * Gets the attribute value for CODDIP using the alias name Coddip.
     * @return the CODDIP
     */
    public String getCoddip() {
        return (String) getAttributeInternal(CODDIP);
    }

    /**
     * Sets <code>value</code> as attribute value for CODDIP using the alias name Coddip.
     * @param value value to set the CODDIP
     */
    public void setCoddip(String value) {
        setAttributeInternal(CODDIP, value);
    }

    /**
     * Gets the attribute value for CODREGIONALE using the alias name Codregionale.
     * @return the CODREGIONALE
     */
    public Integer getCodregionale() {
        return (Integer) getAttributeInternal(CODREGIONALE);
    }

    /**
     * Sets <code>value</code> as attribute value for CODREGIONALE using the alias name Codregionale.
     * @param value value to set the CODREGIONALE
     */
    public void setCodregionale(Integer value) {
        setAttributeInternal(CODREGIONALE, value);
    }

    /**
     * Gets the attribute value for ORDINE using the alias name Ordine.
     * @return the ORDINE
     */
    public Integer getOrdine() {
        return (Integer) getAttributeInternal(ORDINE);
    }

    /**
     * Sets <code>value</code> as attribute value for ORDINE using the alias name Ordine.
     * @param value value to set the ORDINE
     */
    public void setOrdine(Integer value) {
        setAttributeInternal(ORDINE, value);
    }

    /**
     * Gets the attribute value for DTFINEVALIDITA using the alias name Dtfinevalidita.
     * @return the DTFINEVALIDITA
     */
    public Date getDtfinevalidita() {
        return (Date) getAttributeInternal(DTFINEVALIDITA);
    }

    /**
     * Sets <code>value</code> as attribute value for DTFINEVALIDITA using the alias name Dtfinevalidita.
     * @param value value to set the DTFINEVALIDITA
     */
    public void setDtfinevalidita(Date value) {
        setAttributeInternal(DTFINEVALIDITA, value);
    }


    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}

