package model.referto;

import oracle.jbo.RowIterator;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Date;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class RefCa_SoCnfQuestionarioViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_REFCA_SOCNFQUESTIONARIO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Idcnfquest,
        DescrBreve,
        Descrizione,
        DtFineVal,
        Note,
        Tpscr,
        Dtinserimento,
        Opinserimento,
        Dtultimamodifica,
        Opultmodifica,
        Algoritmo,
        RefCa_SoCnfQuestDomandeView,
        RefCa_SoRefertocardioView;
        static AttributesEnum[] vals = null;
        ;
        private static final int        firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDCNFQUEST = AttributesEnum.Idcnfquest.index();
    public static final int DESCRBREVE = AttributesEnum.DescrBreve.index();
    public static final int DESCRIZIONE = AttributesEnum.Descrizione.index();
    public static final int DTFINEVAL = AttributesEnum.DtFineVal.index();
    public static final int NOTE = AttributesEnum.Note.index();
    public static final int TPSCR = AttributesEnum.Tpscr.index();
    public static final int DTINSERIMENTO = AttributesEnum.Dtinserimento.index();
    public static final int OPINSERIMENTO = AttributesEnum.Opinserimento.index();
    public static final int DTULTIMAMODIFICA = AttributesEnum.Dtultimamodifica.index();
    public static final int OPULTMODIFICA = AttributesEnum.Opultmodifica.index();
    public static final int ALGORITMO = AttributesEnum.Algoritmo.index();
    public static final int REFCA_SOCNFQUESTDOMANDEVIEW = AttributesEnum.RefCa_SoCnfQuestDomandeView.index();
    public static final int REFCA_SOREFERTOCARDIOVIEW = AttributesEnum.RefCa_SoRefertocardioView.index();

    /**
     *
     *  This is the default constructor (do not remove)
     */
	public RefCa_SoCnfQuestionarioViewRowImpl() {
	}

	/**
	 * 
	 *  Gets RefCa_SoCnfQuestionario entity object.
	 */
	public RefCa_SoCnfQuestionarioImpl getRefCa_SoCnfQuestionario() {
		return (RefCa_SoCnfQuestionarioImpl)getEntity(0);
	}

	/**
     *
     *  Gets the attribute value for IDCNFQUEST using the alias name Idcnfquest
     */
    public Integer getIdcnfquest() {
        return (Integer) getAttributeInternal(IDCNFQUEST);
    }

	/**
	 * 
	 *  Sets <code>value</code> as attribute value for IDCNFQUEST using the alias name Idcnfquest
	 */
	public void setIdcnfquest(Integer value) {
		setAttributeInternal(IDCNFQUEST, value);
	}

	/**
	 * 
	 *  Gets the attribute value for DESCR_BREVE using the alias name DescrBreve
	 */
	public String getDescrBreve() {
		return (String)getAttributeInternal(DESCRBREVE);
	}

	/**
	 * 
	 *  Sets <code>value</code> as attribute value for DESCR_BREVE using the alias name DescrBreve
	 */
	public void setDescrBreve(String value) {
		setAttributeInternal(DESCRBREVE, value);
	}

	/**
	 * 
	 *  Gets the attribute value for DESCRIZIONE using the alias name Descrizione
	 */
	public String getDescrizione() {
		return (String)getAttributeInternal(DESCRIZIONE);
	}

	/**
	 * 
	 *  Sets <code>value</code> as attribute value for DESCRIZIONE using the alias name Descrizione
	 */
	public void setDescrizione(String value) {
		setAttributeInternal(DESCRIZIONE, value);
	}

	/**
	 * 
	 *  Gets the attribute value for DT_FINE_VAL using the alias name DtFineVal
	 */
	public Date getDtFineVal() {
		return (Date)getAttributeInternal(DTFINEVAL);
	}

	/**
	 * 
	 *  Sets <code>value</code> as attribute value for DT_FINE_VAL using the alias name DtFineVal
	 */
	public void setDtFineVal(Date value) {
		setAttributeInternal(DTFINEVAL, value);
	}

	/**
	 * 
	 *  Gets the attribute value for NOTE using the alias name Note
	 */
	public String getNote() {
		return (String)getAttributeInternal(NOTE);
	}

	/**
	 * 
	 *  Sets <code>value</code> as attribute value for NOTE using the alias name Note
	 */
	public void setNote(String value) {
		setAttributeInternal(NOTE, value);
	}

	/**
	 * 
	 *  Gets the attribute value for TPSCR using the alias name Tpscr
	 */
	public String getTpscr() {
		return (String)getAttributeInternal(TPSCR);
	}

	/**
	 * 
	 *  Sets <code>value</code> as attribute value for TPSCR using the alias name Tpscr
	 */
	public void setTpscr(String value) {
		setAttributeInternal(TPSCR, value);
	}

	/**
	 * 
	 *  Gets the attribute value for DTINSERIMENTO using the alias name Dtinserimento
	 */
	public Date getDtinserimento() {
		return (Date)getAttributeInternal(DTINSERIMENTO);
	}

	/**
	 * 
	 *  Sets <code>value</code> as attribute value for DTINSERIMENTO using the alias name Dtinserimento
	 */
	public void setDtinserimento(Date value) {
		setAttributeInternal(DTINSERIMENTO, value);
	}

	/**
	 * 
	 *  Gets the attribute value for OPINSERIMENTO using the alias name Opinserimento
	 */
	public String getOpinserimento() {
		return (String)getAttributeInternal(OPINSERIMENTO);
	}

	/**
	 * 
	 *  Sets <code>value</code> as attribute value for OPINSERIMENTO using the alias name Opinserimento
	 */
	public void setOpinserimento(String value) {
		setAttributeInternal(OPINSERIMENTO, value);
	}

	/**
	 * 
	 *  Gets the attribute value for DTULTIMAMODIFICA using the alias name Dtultimamodifica
	 */
	public Date getDtultimamodifica() {
		return (Date)getAttributeInternal(DTULTIMAMODIFICA);
	}

	/**
	 * 
	 *  Sets <code>value</code> as attribute value for DTULTIMAMODIFICA using the alias name Dtultimamodifica
	 */
	public void setDtultimamodifica(Date value) {
		setAttributeInternal(DTULTIMAMODIFICA, value);
	}

	/**
	 * 
	 *  Gets the attribute value for OPULTMODIFICA using the alias name Opultmodifica
	 */
	public String getOpultmodifica() {
		return (String)getAttributeInternal(OPULTMODIFICA);
	}

	/**
	 * 
	 *  Sets <code>value</code> as attribute value for OPULTMODIFICA using the alias name Opultmodifica
	 */
	public void setOpultmodifica(String value) {
		setAttributeInternal(OPULTMODIFICA, value);
	}

	/**
	 * 
	 *  Gets the associated <code>RowIterator</code> using master-detail link RefCa_SoCnfQuestDomandeView
	 */
	public oracle.jbo.RowIterator getRefCa_SoCnfQuestDomandeView() {
		return (oracle.jbo.RowIterator)getAttributeInternal(REFCA_SOCNFQUESTDOMANDEVIEW);
	}


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link RefCa_SoRefertocardioView.
     */
    public RowIterator getRefCa_SoRefertocardioView() {
        return (RowIterator) getAttributeInternal(REFCA_SOREFERTOCARDIOVIEW);
    }

    /**
     *
     *  Gets the attribute value for ALGORITMO using the alias name Algoritmo
     */
	public String getAlgoritmo() {
		return (String)getAttributeInternal(ALGORITMO);
	}

	/**
	 * 
	 *  Sets <code>value</code> as attribute value for ALGORITMO using the alias name Algoritmo
	 */
	public void setAlgoritmo(String value) {
		setAttributeInternal(ALGORITMO, value);
	}




}